apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1     # never take more than 1 pod down at once
      maxSurge: 1           # never create more than 1 extra pod at once
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
        - name: web-api
          image: web-api:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              value: "orange"
