# A grouped inventory for the labs. Replace IPs with yours.
[web]
web01 ansible_host=192.168.64.11
web02 ansible_host=192.168.64.12

[lb]
proxy01 ansible_host=192.168.64.10

# A parent group made of other groups:
[prod:children]
web
lb

[all:vars]
ansible_user=ubuntu
