import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

from workbook_engine import run_exercises, choose_translation


exercises = [
    {
        "question": 'Translate: "I gave it to him."',
        "answer": ["se lo di", "se lo di a él"],
        "hint": "le lo → se lo",
        "explanation": "When 'le' (to him/her) combines with 'lo' (it), 'le' becomes 'se': se lo di.",
        "context": "You handed the keys to your neighbor.",
    },
    {
        "question": 'Translate: "I gave it to her."',
        "answer": ["se lo di", "se lo di a ella"],
        "hint": "le lo → se lo; clarify with 'a ella' if needed",
        "explanation": "'Se lo di' alone is ambiguous (him/her/you-formal). Add 'a ella' for clarity.",
        "context": "You gave the book to your friend María.",
    },
    {
        "question": 'Translate: "I gave it to you (formal)."',
        "answer": ["se lo di", "se lo di a usted"],
        "hint": "le lo → se lo; use 'a usted' to clarify",
        "explanation": "In Mexican Spanish, 'usted' is common in polite contexts. 'Se lo di a usted' removes ambiguity.",
        "context": "You're addressing your boss.",
    },
    {
        "question": 'Translate: "She told it to them."',
        "answer": "se lo dijo",
        "hint": "les lo → se lo",
        "explanation": "'Les lo dijo' becomes 'se lo dijo'. The 'les' transforms to 'se' before 'lo'.",
        "context": "A colleague shared the news with the team.",
    },
    {
        "question": 'Translate: "He bought them for her."',
        "answer": ["se las compró", "se las compró a ella"],
        "hint": "le las → se las",
        "explanation": "'Las flores' (feminine plural) → 'las'. 'Le las compró' → 'se las compró'.",
        "context": "He bought flowers for his mother on Día de las Madres.",
    },
    {
        "question": 'Translate: "We sent them to you (formal)."',
        "answer": ["se los enviamos", "se los enviamos a usted"],
        "hint": "le los → se los",
        "explanation": "'Los documentos' (masculine plural) → 'los'. 'Se los enviamos a usted' clarifies the recipient.",
        "context": "Your company sent the contracts to a client.",
    },
    {
        "question": 'Translate: "They explained it to us."',
        "answer": "nos lo explicaron",
        "hint": "nos + lo — no 'se' needed here",
        "explanation": "'Nos' is not 'le/les', so no 'se' transformation. Only 'le/les' becomes 'se' before lo/la/los/las.",
        "context": "The professors explained the topic to the students.",
    },
    {
        "question": 'Translate: "I want to give it to him." (attach pronouns to infinitive)',
        "answer": ["quiero dárselo", "se lo quiero dar"],
        "hint": "dar + se + lo = dárselo",
        "explanation": "With infinitives, pronouns attach to the end: 'dar' + 'se' + 'lo' = 'dárselo'. An accent mark appears on the stressed syllable.",
        "context": "You want to return the favor to a friend.",
    },
    {
        "question": 'Translate: "She is giving them to you (informal)." (attach to gerund)',
        "answer": ["está dándotelos", "te los está dando"],
        "hint": "dando + te + los = dándotelos",
        "explanation": "Pronouns can attach to gerunds: 'dando' + 'te' + 'los' = 'dándotelos'. An accent mark preserves stress.",
        "context": "Your sister is handing you the tickets right now.",
    },
    {
        "question": 'Translate: "Give it to her!" (affirmative command, tú)',
        "answer": ["¡dáselo!", "dáselo"],
        "hint": "da + se + lo = dáselo",
        "explanation": "Affirmative commands attach pronouns: 'da' + 'se' + 'lo' = 'dáselo'. Add 'a ella' if context is unclear.",
        "context": "Tell your friend to hand the phone to her mom.",
    },
    {
        "question": 'Translate: "I\'m counting on you for this." (Mexican: se lo encargo mucho)',
        "answer": ["se lo encargo mucho", "se lo encargo"],
        "hint": "encargar + se + lo",
        "explanation": "In Mexican Spanish, 'se lo encargo' is a very common phrase meaning 'I entrust this to you' or 'I\'m counting on you.'",
        "context": "Asking a trusted friend to handle something important.",
    },
    {
        "question": 'Translate: "The teacher explained it to us."',
        "answer": "la maestra nos lo explicó",
        "hint": "nos + lo — no se transformation",
        "explanation": "'Nos' stays 'nos' — only 'le/les' becomes 'se'. 'Nos lo explicó' is correct.",
        "context": "In a Mexican classroom, the teacher clarified a grammar point.",
    },
    {
        "question": 'Translate: "Don\'t give it to them!" (negative command, tú)',
        "answer": "no se lo des",
        "hint": "Negative command: pronouns go before the verb",
        "explanation": "In negative commands, pronouns precede the verb: 'no se lo des' (don't give it to them). No attachment.",
        "context": "Stop your friend from handing over the money to strangers.",
    },
    {
        "question": 'Translate: "I wrote them for him." (los reportes)',
        "answer": ["se los escribí", "se los escribí a él"],
        "hint": "le los → se los",
        "explanation": "'Los reportes' → 'los'. 'Le los escribí' → 'se los escribí'. Add 'a él' for clarity.",
        "context": "You wrote the reports for your supervisor.",
    },
    {
        "question": 'Translate: "She recommended it to them."',
        "answer": "se lo recomendó",
        "hint": "les lo → se lo",
        "explanation": "'Les lo recomendó' → 'se lo recomendó'. The restaurant, the movie — 'se lo' handles it all.",
        "context": "Your friend recommended a taco stand to the group.",
    },
    {
        "question": 'Translate: "I bought it for her."',
        "answer": ["se la compré", "se la compré a ella"],
        "hint": "le la → se la (la = feminine thing like la ropa)",
        "explanation": "'Le la' becomes 'se la'. 'La' agrees with a feminine direct object (e.g., la ropa, la comida).",
        "context": "You bought a dress for your sister at a mercado in CDMX.",
    },
    {
        "question": 'Translate: "She sent it (la carta) to them."',
        "answer": ["se la mandó", "se la envió"],
        "hint": "les la → se la",
        "explanation": "'Les la' becomes 'se la'. 'La' agrees with 'la carta' (feminine singular).",
        "context": "Your mom sent the letter to your cousins in Guadalajara.",
    },
    {
        "question": 'Translate: "They gave it (la noticia) to him."',
        "answer": "se la dieron",
        "hint": "le la → se la",
        "explanation": "'Le la' becomes 'se la'. 'La' agrees with 'la noticia' (feminine singular).",
        "context": "The team gave him the news about the project.",
    },
    {
        "question": 'Translate: "We recommended it (la comida) to you (formal)."',
        "answer": ["se la recomendamos", "se la recomendamos a usted"],
        "hint": "le la → se la; clarify with 'a usted'",
        "explanation": "'Le la' becomes 'se la'. Add 'a usted' to clarify the formal recipient.",
        "context": "You recommended the enchiladas to your client at a restaurant.",
    },
    {
        "question": 'Translate: "I wrote it (la carta) for him."',
        "answer": ["se la escribí", "se la escribí a él"],
        "hint": "le la → se la",
        "explanation": "'Le la' becomes 'se la'. 'La' agrees with 'la carta' (feminine singular).",
        "context": "You wrote the letter for your supervisor.",
    },
    {
        "question": 'Translate: "I sent them (los documentos) to her."',
        "answer": ["se los envié", "se los envié a ella", "se los mandé", "se los mandé a ella"],
        "hint": "le los → se los",
        "explanation": "'Le los' becomes 'se los'. 'Los' agrees with masculine plural (los documentos).",
        "context": "You sent the documents to your colleague at the office.",
    },
    {
        "question": 'Translate: "He gave them (los libros) to you (formal)."',
        "answer": "se los dio a usted",
        "hint": "le los → se los; 'a usted' clarifies",
        "explanation": "'Le los' becomes 'se los'. 'Los' agrees with masculine plural. 'A usted' clarifies the formal recipient.",
        "context": "The professor handed the books to you at the university.",
    },
    {
        "question": 'Translate: "I returned them (los papeles) to him."',
        "answer": ["se los devolví", "se los devolví a él"],
        "hint": "le los → se los",
        "explanation": "'Le los' becomes 'se los'. 'Devolver' = to return. 'Los' agrees with masculine plural.",
        "context": "You returned the papers to the government clerk.",
    },
    {
        "question": 'Translate: "They sold them (los productos) to the clients."',
        "answer": "se los vendieron a los clientes",
        "hint": "les los → se los; clarification with 'a los clientes'",
        "explanation": "'Les los' becomes 'se los'. 'Los' agrees with masculine plural. 'A los clientes' clarifies.",
        "context": "The market vendors sold the products to the clients.",
    },
    {
        "question": 'Translate: "I bought them (las flores) for my mom."',
        "answer": "se las compré a mi mamá",
        "hint": "le las → se las; 'a mi mamá' clarifies",
        "explanation": "'Le las' becomes 'se las'. 'Las' agrees with feminine plural (las flores). 'A mi mamá' clarifies.",
        "context": "You bought flowers for your mom on Día de las Madres.",
    },
    {
        "question": 'Translate: "She sent them (las invitaciones) to you (formal)."',
        "answer": "se las envió a usted",
        "hint": "le las → se las; 'a usted' clarifies",
        "explanation": "'Le las' becomes 'se las'. 'Las' agrees with feminine plural. 'A usted' clarifies the formal recipient.",
        "context": "The coordinator sent the invitations to your boss.",
    },
    {
        "question": 'Translate: "We gave them (las llaves) to the client."',
        "answer": "se las dimos al cliente",
        "hint": "le las → se las; 'al cliente' clarifies",
        "explanation": "'Le las' becomes 'se las'. 'Las' agrees with feminine plural (las llaves). 'Al cliente' clarifies.",
        "context": "You handed the keys to the client at the hotel.",
    },
    {
        "question": 'Translate: "They offered them (las opciones) to him."',
        "answer": ["se las ofrecieron", "se las ofrecieron a él"],
        "hint": "le las → se las",
        "explanation": "'Le las' becomes 'se las'. 'Las' agrees with feminine plural (las opciones).",
        "context": "The company offered the options to the new employee.",
    },
    {
        "question": 'Translate: "She has to tell it to them." (attach pronouns to infinitive)',
        "answer": ["tiene que decírselo", "se lo tiene que decir"],
        "hint": "decir + se + lo = decírselo",
        "explanation": "With infinitives, pronouns can attach: 'decir' + 'se' + 'lo' = 'decírselo'. Accent mark preserves stress.",
        "context": "Your coworker has to share the news with the team.",
    },
    {
        "question": 'Translate: "I want to send them (los paquetes) to her." (attach pronouns to infinitive)',
        "answer": ["quiero enviárselos", "se los quiero enviar", "quiero mandárselos", "se los quiero mandar"],
        "hint": "enviar + se + los = enviárselos",
        "explanation": "'Enviar' + 'se' + 'los' = 'enviárselos'. Accent on 'en-vi-ár-se-los' preserves original stress.",
        "context": "You want to send the packages to your mom in Monterrey.",
    },
    {
        "question": 'Translate: "He is going to give it (la oportunidad) to her." (attach pronouns to infinitive)',
        "answer": ["va a dársela", "se la va a dar"],
        "hint": "dar + se + la = dársela",
        "explanation": "'Dar' + 'se' + 'la' = 'dársela'. 'La' agrees with feminine singular (la oportunidad).",
        "context": "The manager is going to give the opportunity to a new employee.",
    },
    {
        "question": 'Translate: "We need to return them (los libros) to him." (attach pronouns to infinitive)',
        "answer": ["necesitamos devolvérselos", "se los necesitamos devolver"],
        "hint": "devolver + se + los = devolvérselos",
        "explanation": "'Devolver' + 'se' + 'los' = 'devolvérselos'. Accent preserves stress on original infinitive.",
        "context": "You need to return the library books to the librarian.",
    },
    {
        "question": 'Translate: "They want to show it to you (formal)." (attach pronouns to infinitive)',
        "answer": ["quieren mostrárselo", "se lo quieren mostrar"],
        "hint": "mostrar + se + lo = mostrárselo",
        "explanation": "'Mostrar' + 'se' + 'lo' = 'mostrárselo'. The accent mark on 'mos-trár-se-lo' preserves stress.",
        "context": "The team wants to show the project to the director.",
    },
    {
        "question": 'Translate: "She was explaining it to them." (gerund + pronouns)',
        "answer": ["estaba explicándoselo", "se lo estaba explicando"],
        "hint": "explicando + se + lo = explicándoselo",
        "explanation": "Pronouns can attach to gerunds: 'explicando' + 'se' + 'lo' = 'explicándoselo'. Accent preserves stress.",
        "context": "The professor was explaining the concept to the students.",
    },
    {
        "question": 'Translate: "He is sending them (las cartas) to her." (gerund + pronouns)',
        "answer": ["está enviándoselas", "se las está enviando", "está mandándoselas", "se las está mandando"],
        "hint": "enviando + se + las = enviándoselas",
        "explanation": "'Enviando' + 'se' + 'las' = 'enviándoselas'. 'Las' agrees with feminine plural (las cartas).",
        "context": "He is sending the letters to his girlfriend from the post office.",
    },
    {
        "question": 'Translate: "I am giving it to him." (gerund + pronouns)',
        "answer": ["estoy dándoselo", "se lo estoy dando"],
        "hint": "dando + se + lo = dándoselo",
        "explanation": "'Dando' + 'se' + 'lo' = 'dándoselo'. Accent preserves stress on the original gerund syllable.",
        "context": "You are handing the gift to your friend right now.",
    },
    {
        "question": 'Translate: "He was offering it to them." (gerund + pronouns)',
        "answer": ["estaba ofreciéndoselo", "se lo estaba ofreciendo"],
        "hint": "ofreciendo + se + lo = ofreciéndoselo",
        "explanation": "'Ofreciendo' + 'se' + 'lo' = 'ofreciéndoselo'. Accent on 'o-fre-cién-do-se-lo' preserves stress.",
        "context": "The seller was offering the discount to the customers at the tianguis.",
    },
    {
        "question": 'Translate: "Give them (los boletos) to him!" (affirmative tú command)',
        "answer": "¡dáselos!",
        "hint": "da + se + los = dáselos",
        "explanation": "Affirmative tú command: 'da' + 'se' + 'los' = 'dáselos'. Accent on stressed syllable.",
        "context": "Tell your friend to hand the concert tickets to his brother.",
    },
    {
        "question": 'Translate: "Send it (la carta) to them!" (affirmative tú command)',
        "answer": ["¡mándasela!", "mándasela"],
        "hint": "manda + se + la = mándasela",
        "explanation": "'Manda' + 'se' + 'la' = 'mándasela'. 'La' agrees with 'la carta' (feminine). Accent on original stress.",
        "context": "Tell your coworker to send the letter to the team.",
    },
    {
        "question": 'Translate: "Buy it for her!" (affirmative tú command)',
        "answer": ["¡cómpraselo!", "cómpraselo"],
        "hint": "compra + se + lo = cómpraselo",
        "explanation": "'Compra' + 'se' + 'lo' = 'cómpraselo'. 'Le lo' becomes 'se lo'. Accent on original stress.",
        "context": "Tell your brother to buy the gift for your mom.",
    },
    {
        "question": 'Translate: "Show them (las fotos) to him!" (affirmative tú command)',
        "answer": ["¡muéstraselas!", "muéstraselas"],
        "hint": "muestra + se + las = muéstraselas",
        "explanation": "'Muestra' + 'se' + 'las' = 'muéstraselas'. 'Las' agrees with feminine plural (las fotos).",
        "context": "Tell your friend to show the vacation photos to his dad.",
    },
    {
        "question": 'Translate: "Give it to them, sir." (affirmative usted command)',
        "answer": "déselo",
        "hint": "dé + se + lo = déselo",
        "explanation": "Usted command of 'dar' = 'dé'. 'Dé' + 'se' + 'lo' = 'déselo'. Accent preserves stress.",
        "context": "A polite instruction to hand the document to the group.",
    },
    {
        "question": 'Translate: "Send them (los reportes) to her, ma\'am." (affirmative usted command)',
        "answer": "mándeselos",
        "hint": "mande + se + los = mándeselos",
        "explanation": "Usted command of 'mandar' = 'mande'. 'Mande' + 'se' + 'los' = 'mándeselos'. Accent on original stress.",
        "context": "A respectful instruction to send the reports to the director.",
    },
    {
        "question": 'Translate: "Buy them (los ingredientes) for him, please." (affirmative usted command)',
        "answer": "cómpreselos",
        "hint": "compre + se + los = cómpreselos",
        "explanation": "Usted command of 'comprar' = 'compre'. 'Compre' + 'se' + 'los' = 'cómpreselos'. Accent on original stress.",
        "context": "Asking the vendor at the mercado to buy the ingredients for the chef.",
    },
    {
        "question": 'Translate: "Don\'t give it to her!" (negative tú command)',
        "answer": "no se lo des",
        "hint": "Negative command: pronouns before the verb; le lo → se lo",
        "explanation": "In negative commands, pronouns precede the verb: 'no se lo des'. 'Le lo' becomes 'se lo'.",
        "context": "Stop your friend from giving the password to his sister.",
    },
    {
        "question": 'Translate: "Don\'t tell it to them!" (negative tú command)',
        "answer": "no se lo digas",
        "hint": "Negative command: pronouns before the verb; les lo → se lo",
        "explanation": "In negative commands: 'no se lo digas'. 'Les lo' becomes 'se lo'. Pronouns never attach.",
        "context": "Tell your friend not to share the secret with the group.",
    },
    {
        "question": 'Translate: "Don\'t send them (los documentos) to him!" (negative tú command)',
        "answer": "no se los envíes",
        "hint": "Negative command: pronouns before the verb; le los → se los",
        "explanation": "In negative commands: 'no se los envíes'. 'Le los' becomes 'se los'. Pronouns precede the verb.",
        "context": "Tell your colleague not to send the documents to the competitor.",
    },
    {
        "question": 'Translate: "Don\'t buy them (las cosas) for her!" (negative tú command)',
        "answer": "no se las compres",
        "hint": "Negative command: pronouns before the verb; le las → se las",
        "explanation": "In negative commands: 'no se las compres'. 'Le las' becomes 'se las'. 'Las' = feminine plural.",
        "context": "Tell your friend not to buy things for his girlfriend at the mercado.",
    },
    {
        "question": 'Translate: "She gave it (el regalo) to her sister." (redundant clarification)',
        "answer": "se lo dio a su hermana",
        "hint": "le lo → se lo; 'a su hermana' clarifies who 'se' is",
        "explanation": "'Se lo dio' alone is ambiguous. 'A su hermana' clarifies the recipient. Redundant 'a' phrases are normal in Spanish.",
        "context": "She handed the gift to her sister at the posada.",
    },
    {
        "question": 'Translate: "I bought them (los zapatos) for my mom." (redundant clarification)',
        "answer": "se los compré a mi mamá",
        "hint": "le los → se los; 'a mi mamá' clarifies",
        "explanation": "'Se los compré' is ambiguous (him/her/you-formal). 'A mi mamá' clarifies. 'Los' = masculine plural.",
        "context": "You bought shoes for your mom at a mercado in Oaxaca.",
    },
    {
        "question": 'Translate: "He sent it (el paquete) to his boss." (redundant clarification)',
        "answer": "se lo envió a su jefe",
        "hint": "le lo → se lo; 'a su jefe' clarifies",
        "explanation": "'Se lo envió' alone is ambiguous. 'A su jefe' clarifies the recipient. 'Lo' = el paquete.",
        "context": "The employee sent the package to his boss at the office.",
    },
    {
        "question": 'Translate: "We gave them (las llaves) to the clients." (redundant clarification)',
        "answer": "se las dimos a los clientes",
        "hint": "les las → se las; 'a los clientes' clarifies",
        "explanation": "'Se las dimos' is ambiguous. 'A los clientes' clarifies. 'Las' = feminine plural (las llaves).",
        "context": "The hotel reception gave the keys to the clients.",
    },
    {
        "question": 'Translate: "She told it (el secreto) to her husband." (redundant clarification)',
        "answer": "se lo dijo a su esposo",
        "hint": "le lo → se lo; 'a su esposo' clarifies",
        "explanation": "'Se lo dijo' alone is ambiguous. 'A su esposo' clarifies. 'Lo' = el secreto (masculine).",
        "context": "She shared the secret with her husband during dinner.",
    },
    {
        "question": 'Translate: "I want you (tú) to give it to him." (subjunctive trigger)',
        "answer": "quiero que se lo des",
        "hint": "quiero que + subjunctive; le lo → se lo",
        "explanation": "'Quiero que' triggers the subjunctive. 'Des' (tú subjunctive of dar). 'Le lo' becomes 'se lo' even in subjunctive.",
        "context": "You want your friend to hand the keys to the neighbor.",
    },
    {
        "question": 'Translate: "It\'s necessary that we send it (la carta) to her." (subjunctive trigger)',
        "answer": "es necesario que se la mandemos",
        "hint": "es necesario que + subjunctive; le la → se la",
        "explanation": "'Es necesario que' triggers the subjunctive. 'Mandemos' (nosotros subjunctive). 'Le la' becomes 'se la'.",
        "context": "It's necessary to send the letter to the director.",
    },
    {
        "question": 'Translate: "I hope that she tells it to them." (subjunctive trigger)',
        "answer": "espero que se lo diga",
        "hint": "espero que + subjunctive; les lo → se lo",
        "explanation": "'Espero que' triggers the subjunctive. 'Diga' (ella subjunctive of decir). 'Les lo' becomes 'se lo'.",
        "context": "You hope your colleague shares the information with the team.",
    },
    {
        "question": 'Translate: "It\'s important that you (tú) send them (los documentos) to him." (subjunctive trigger)',
        "answer": "es importante que se los envíes",
        "hint": "es importante que + subjunctive; le los → se los",
        "explanation": "'Es importante que' triggers the subjunctive. 'Envíes' (tú subjunctive). 'Le los' becomes 'se los'.",
        "context": "It's important that you send the documents to the manager.",
    },
    {
        "question": 'Translate: "I\'m leaving it in your hands." (Mexican: se lo dejo)',
        "answer": "se lo dejo",
        "hint": "dejar + se + lo; common Mexican expression",
        "explanation": "'Se lo dejo' literally means 'I leave it to you' but is used in Mexico to mean 'I'm leaving it in your hands / I trust you with this.'",
        "context": "You entrust a task to a reliable coworker at the office.",
    },
    {
        "question": 'Translate: "Throw it to me!" (Mexican colloquial: ¡échamelo!)',
        "answer": ["¡échamelo!", "échamelo"],
        "hint": "echa + me + lo = échamelo; Mexican expression",
        "explanation": "'Échamelo' = echa + me + lo. In Mexican Spanish, 'echar' means 'to throw/pass'. Very common at gatherings.",
        "context": "You're at a carne asada and want someone to toss you the salsa.",
    },
    {
        "question": 'Translate: "Don\'t get ahead of me!" (Mexican: ¡no te me adelantes!)',
        "answer": ["¡no te me adelantes!", "no te me adelantes"],
        "hint": "adelantarse (reflexive) + me (indirect); Mexican expression",
        "explanation": "'No te me adelantes' uses 'te' (reflexive) and 'me' (indirect). Common Mexican expression meaning 'don't beat me to it.'",
        "context": "Your friend tries to answer before you at a trivia night.",
    },
]


pairs = [
    (
        "I gave it to him.",
        ["Le lo di", "Se lo di", "Lo di le", "Se lo dio"],
        2,
        "When 'le' and 'lo' combine, 'le' becomes 'se': se lo di.",
    ),
    (
        "She bought them for her mother.",
        ["Se las compró a su mamá", "Le las compró a su mamá", "Las compró se su mamá", "Se los compró a su mamá"],
        1,
        "'Las' agrees with feminine plural (e.g., las flores). 'Se las compró' is correct.",
    ),
    (
        "Give it to me! (tú command)",
        ["¡Dámelo!", "¡Me lo da!", "¡Deme lo!", "¡Se lo da!"],
        1,
        "Affirmative tú command: da + me + lo = dámelo. Accent on stressed syllable.",
    ),
    (
        "They explained it to us.",
        ["Les lo explicaron", "Se lo explicaron", "Nos lo explicaron", "Lo explicaron nos"],
        3,
        "'Nos' does not transform to 'se'. Only 'le/les' becomes 'se'. So: nos lo explicaron.",
    ),
    (
        "I want to show it to you (formal).",
        ["Quiero mostrárselo", "Quiero se lo mostrar", "Quiero mostrarle se lo", "Quiero lo mostrar se"],
        1,
        "With infinitives: mostrar + se + lo = mostrárselo. Or: 'Se lo quiero mostrar'.",
    ),
    (
        "Which is the correct Mexican phrase for 'I'm counting on you'?",
        ["Se lo encargo mucho", "Le lo encargo mucho", "Te lo encargo", "Me lo encargo"],
        1,
        "'Se lo encargo mucho' is a distinctly Mexican expression meaning 'I entrust this to you / I'm counting on you.'",
    ),
    (
        "He sent them to her.",
        ["Le los envió", "Se los envió", "Se las envió", "Los envió se"],
        2,
        "'Los' for masculine plural. 'Les los envió' → 'se los envió'. Use 'se los envió a ella' for clarity.",
    ),
    (
        "Don't tell it to them! (tú)",
        ["No se lo digas", "No les lo digas", "No digas se lo", "No se los digas"],
        1,
        "Negative command: pronouns before the verb. 'Les lo' → 'se lo'. 'No se lo digas' is correct.",
    ),
    (
        "I bought it for her. (la ropa)",
        ["Se la compré", "Le la compré", "Se lo compré", "La compré se"],
        1,
        "'Le la' → 'se la'. 'La' agrees with feminine 'la ropa'. Not 'se lo'.",
    ),
    (
        "She sent it (la carta) to them.",
        ["Se la mandó", "Les la mandó", "Se lo mandó", "La mandó se"],
        1,
        "'Les la' → 'se la'. 'La' agrees with feminine 'la carta'. Not 'se lo'.",
    ),
    (
        "I returned them (los papeles) to him.",
        ["Se los devolví", "Le los devolví", "Se las devolví", "Los devolví se"],
        1,
        "'Le los' → 'se los'. 'Los' agrees with masculine plural 'los papeles'.",
    ),
    (
        "Which is WRONG for 'I gave them (los libros) to her'?",
        ["Le las di", "Se los di", "Se los di a ella", "Se los regalé"],
        1,
        "'Le las di' is impossible because 'les' becomes 'se' before 'los'. All others are grammatical.",
    ),
    (
        "She has to tell it to them. (infinitive attachment)",
        ["Tiene que decírselo", "Tiene que se lo decir", "Tiene que le lo decir", "Tiene que decirselo"],
        1,
        "Infinitive attachment: 'decir' + 'se' + 'lo' = 'decírselo'. Accent mark is required.",
    ),
    (
        "I want to send them (los paquetes) to her. (infinitive attachment)",
        ["Quiero enviárselos", "Quiero se los enviar", "Quiero le los enviar", "Quiero enviarles los"],
        1,
        "Infinitive: 'enviar' + 'se' + 'los' = 'enviárselos'. Accent preserves stress.",
    ),
    (
        "He is going to give it (la oportunidad) to her.",
        ["Va a dársela", "Va a se la dar", "Va a le la dar", "Va a dar la se"],
        1,
        "Infinitive attachment: 'dar' + 'se' + 'la' = 'dársela'. 'La' agrees with feminine.",
    ),
    (
        "She was explaining it to them. (gerund)",
        ["Estaba explicándoselo", "Estaba se lo explicando", "Estaba les lo explicando", "Estaba explicando se lo"],
        1,
        "Gerund attachment: 'explicando' + 'se' + 'lo' = 'explicándoselo'. Accent preserves stress.",
    ),
    (
        "He is sending them (las cartas) to her. (gerund)",
        ["Está enviándoselas", "Está se las enviando", "Está le las enviando", "Está enviando se las"],
        1,
        "Gerund: 'enviando' + 'se' + 'las' = 'enviándoselas'. 'Las' agrees with feminine plural.",
    ),
    (
        "Give them (los boletos) to him! (tú command)",
        ["¡Dáselos!", "¡Le los da!", "¡Da se los!", "¡Dáselas!"],
        1,
        "Affirmative tú command: 'da' + 'se' + 'los' = 'dáselos'. 'Los' for masculine plural.",
    ),
    (
        "Send it (la carta) to them! (tú command)",
        ["¡Mándasela!", "¡Les la manda!", "¡Manda se la!", "¡Mándeselo!"],
        1,
        "Affirmative tú command: 'manda' + 'se' + 'la' = 'mándasela'. 'La' for feminine singular.",
    ),
    (
        "Buy them (las cosas) for her! (tú command)",
        ["¡Cómpraselas!", "¡Le las compra!", "¡Compra se las!", "¡Cómpraselos!"],
        1,
        "Affirmative tú command: 'compra' + 'se' + 'las' = 'cómpraselas'. 'Las' for feminine plural.",
    ),
    (
        "Give it to them, sir. (usted command)",
        ["Déselo", "Se lo dé", "Le lo dé", "Dé se lo"],
        1,
        "Usted command: 'dé' + 'se' + 'lo' = 'déselo'. Accent on 'dé' to distinguish from 'de'.",
    ),
    (
        "Don't give it to her! (tú)",
        ["No se lo des", "No le lo des", "No des se lo", "No se la des"],
        1,
        "Negative command: pronouns before the verb. 'Le lo' → 'se lo'. 'No se lo des' is correct.",
    ),
    (
        "Don't buy them (las cosas) for him! (tú)",
        ["No se las compres", "No le las compres", "No compres se las", "No se los compres"],
        1,
        "Negative command: 'le las' → 'se las'. 'Las' for feminine plural. Pronouns precede the verb.",
    ),
    (
        "She gave it to her sister. (clarification)",
        ["Se lo dio a su hermana", "Le lo dio a su hermana", "Se lo dio", "La dio a su hermana"],
        1,
        "'Se lo dio' is ambiguous. 'A su hermana' clarifies the recipient. 'Le lo' is ungrammatical.",
    ),
    (
        "I bought them (los zapatos) for my mom. (clarification)",
        ["Se los compré a mi mamá", "Le los compré a mi mamá", "Se los compré", "Los compré a mi mamá"],
        1,
        "'Se los compré a mi mamá' uses redundant 'a mi mamá' for clarity. 'Le los' is ungrammatical.",
    ),
    (
        "I want you to give it to him. (subjunctive)",
        ["Quiero que se lo des", "Quiero que le lo des", "Quiero que te lo des", "Quiero que lo des se"],
        1,
        "'Quiero que' + subjunctive. 'Le lo' → 'se lo' even in subjunctive: 'que se lo des'.",
    ),
    (
        "It's necessary that we send it (la carta) to her.",
        ["Es necesario que se la mandemos", "Es necesario que le la mandemos", "Es necesario que se lo mandemos", "Es necesario que mandemos se la"],
        1,
        "Subjunctive: 'mandemos'. 'Le la' → 'se la'. 'La' agrees with feminine 'la carta'.",
    ),
    (
        "What does 'se lo encargo mucho' mean in Mexico?",
        ["I'm counting on you / I entrust this to you", "I owe you a lot", "I'm sorry for bothering you", "I'll pay you later"],
        1,
        "'Se lo encargo mucho' is a very common Mexican expression meaning 'I'm counting on you.'",
    ),
    (
        "What does 'échamelo' mean in Mexican Spanish?",
        ["Throw it to me / Pass it to me", "Leave it here", "Give it back", "Throw it away"],
        1,
        "'Échamelo' = echa + me + lo. In Mexico, 'echar' often means 'to pass/throw' something to someone.",
    ),
    (
        "What does 'no te me adelantes' mean?",
        ["Don't get ahead of me / Don't beat me to it", "Don't go without me", "Don't worry about me", "Don't come closer"],
        1,
        "'No te me adelantes' uses 'te' (reflexive) + 'me' (indirect). Common Mexican expression.",
    ),
    (
        "Which is the correct combination of 'le' + 'lo'?",
        ["se lo", "le lo", "lo le", "se le"],
        1,
        "The rule: 'le/les' becomes 'se' before 'lo/la/los/las'. So 'le lo' → 'se lo'.",
    ),
    (
        "Which is the correct combination of 'les' + 'la'?",
        ["se la", "les la", "la les", "se las"],
        1,
        "'Les la' → 'se la'. 'Les' becomes 'se' before 'la'. Note: 'se las' would be for 'les' + 'las'.",
    ),
    (
        "Which is the correct combination of 'les' + 'los'?",
        ["se los", "les los", "los les", "se las"],
        1,
        "'Les los' → 'se los'. 'Les' becomes 'se' before 'los'. Note: 'se las' would be for 'les' + 'las'.",
    ),
    (
        "Which is WRONG? 'I gave it to them.'",
        ["Les lo di", "Se lo di", "Se lo di a ellos", "Se lo entregué"],
        1,
        "'Les lo di' is ungrammatical. 'Les' must become 'se' before 'lo'. All other forms are correct.",
    ),
    (
        "He sent them (los paquetes) to her.",
        ["Se los envió a ella", "Le los envió a ella", "Se las envió a ella", "Los envió se a ella"],
        1,
        "'Le los' → 'se los'. 'Los' for masculine plural. 'A ella' clarifies the recipient.",
    ),
    (
        "They sold them (las frutas) to the customers.",
        ["Se las vendieron a los clientes", "Le las vendieron a los clientes", "Se los vendieron a los clientes", "Las vendieron se a los clientes"],
        1,
        "'Les las' → 'se las'. 'Las' agrees with feminine plural 'las frutas'. 'A los clientes' clarifies.",
    ),
    (
        "I want you to give it to him. (subjunctive)",
        ["Quiero que se lo des", "Quiero que le lo des", "Quiero que te lo des", "Quiero que lo des se"],
        1,
        "'Quiero que' + subjunctive. 'Le lo' → 'se lo'. 'Quiero que se lo des' is correct.",
    ),
    (
        "She gave it (el regalo) to her sister. (clarification)",
        ["Se lo dio a su hermana", "Le lo dio a su hermana", "Se lo dio", "La dio a su hermana"],
        1,
        "'Se lo dio a su hermana' uses redundant 'a su hermana' for clarity. 'Le lo' is ungrammatical.",
    ),
]


if __name__ == "__main__":
    run_exercises(exercises, title="Lección 3: Se lo / Se la — Double Object Pronouns")
    choose_translation(pairs, title="Lección 3: Choose the Best Translation")