import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

from workbook_engine import run_exercises, choose_translation


exercises = [
    {
        "question": 'Translate: "He told her the truth."',
        "answer": ["le dijo la verdad", "él le dijo la verdad"],
        "hint": "decir uses indirect object: le",
        "explanation": "'Decir' always takes an indirect object for the person told: 'le dijo' (he told her/him). Not 'la dijo'.",
        "context": "A couple having an honest conversation.",
    },
    {
        "question": 'Translate: "The woman gave him the book."',
        "answer": ["la mujer le dio el libro", "le dio el libro"],
        "hint": "dar uses indirect object for the recipient: le",
        "explanation": "'Dar' takes indirect object for the person receiving: 'le dio' (gave to him/her). The book is the direct object.",
        "context": "A librarian handing a book to a patron.",
    },
    {
        "question": 'Translate: "I saw him at the market."',
        "answer": ["lo vi en el mercado", "lo vi en el tianguis"],
        "hint": "ver uses direct object: lo",
        "explanation": "'Ver' takes a direct object for the person seen: 'lo vi' (I saw him). Not 'le vi' — this is a common error.",
        "context": "You spotted your friend at a Mexican tianguis (open-air market).",
    },
    {
        "question": 'Translate: "They explained it to us."',
        "answer": "nos lo explicaron",
        "hint": "explicar: direct = lo (the thing), indirect = nos (to us)",
        "explanation": "'Explicar' uses indirect object for the audience and direct object for what's explained: 'nos lo explicaron'.",
        "context": "The guides explained the route to the group.",
    },
    {
        "question": 'Translate: "She asked him for the favor."',
        "answer": ["le pidió el favor", "ella le pidió el favor"],
        "hint": "pedir uses indirect object: le",
        "explanation": "'Pedir' (to ask for) uses indirect object for the person asked: 'le pidió' (she asked him). The favor is the direct object.",
        "context": "A coworker asking her supervisor for a favor.",
    },
    {
        "question": 'Translate: "He told them the story."',
        "answer": "les contó la historia",
        "hint": "contar uses indirect object: les (to them)",
        "explanation": "'Contar' (to tell/recount) uses indirect object: 'les contó' (told them). 'La historia' is the direct object.",
        "context": "A grandfather telling his grandchildren a story.",
    },
    {
        "question": 'Translate: "We sent you (informal) the message."',
        "answer": "te mandamos el mensaje",
        "hint": "mandar uses indirect object: te (to you)",
        "explanation": "'Mandar' (to send) uses indirect object for the recipient: 'te mandamos el mensaje'. In Mexico, 'mandar' is very common for sending messages.",
        "context": "Your friends sent you a WhatsApp message.",
    },
    {
        "question": 'Translate: "I gave it to her." (double pronoun)',
        "answer": ["se lo di", "se lo di a ella"],
        "hint": "le + lo → se lo",
        "explanation": "When 'le' (to her) combines with 'lo' (it), 'le' becomes 'se': 'se lo di'. Add 'a ella' for clarity.",
        "context": "You handed your friend the receipt at the restaurant.",
    },
    {
        "question": 'Translate: "He told Juan."',
        "answer": ["le dijo a juan", "a juan le dijo"],
        "hint": "Use 'a Juan' for clarification with indirect object",
        "explanation": "'Le dijo' alone is ambiguous (him/her/you-formal). 'Le dijo a Juan' uses the redundant 'a' phrase, which is normal and preferred in Spanish.",
        "context": "Clarifying exactly who was told.",
    },
    {
        "question": 'Translate: "The teacher gave us the homework."',
        "answer": ["la maestra nos dio la tarea", "nos dio la tarea"],
        "hint": "nos (to us) + direct object",
        "explanation": "'Nos' is the indirect object (to us). 'La tarea' is the direct object. No 'se' transformation needed.",
        "context": "A Mexican school assigning homework for the weekend.",
    },
    {
        "question": 'Translate: "Órale, I\'m counting on you." (Mexican phrase)',
        "answer": ["órale, se lo encargo", "órale, se lo encargo mucho"],
        "hint": "Common Mexican phrase combining órale + se lo encargo",
        "explanation": "'Órale' is a versatile Mexican interjection (okay, sure, wow). 'Se lo encargo' means 'I'm counting on you / I entrust this to you.' Together they form a very natural Mexican expression.",
        "context": "A friend asks you to pick up tamales for the party.",
    },
    {
        "question": 'Translate: "Throw it in!" (Mexican: ¡échale!)',
        "answer": ["¡échale!", "échale"],
        "hint": "écharle — common Mexican expression",
        "explanation": "'Échale' literally 'throw to it' but used as 'go for it / put some effort in'. The indirect 'le' references the situation.",
        "context": "Encouraging someone to give it their all at a fiesta.",
    },
    {
        "question": 'Translate: "She recommended the restaurant to me."',
        "answer": "me recomendó el restaurante",
        "hint": "recomendar: indirect = me, direct = el restaurante",
        "explanation": "'Me' (to me) is the indirect object. 'El restaurante' is the direct object. No double pronoun needed here.",
        "context": "A friend recommended a taco restaurant in CDMX.",
    },
    {
        "question": 'Translate: "They sent them (the documents) to us." (double pronoun)',
        "answer": "nos los mandaron",
        "hint": "nos (to us) + los (the documents)",
        "explanation": "'Nos' stays 'nos' — only 'le/les' transforms to 'se'. 'Nos los mandaron' is correct.",
        "context": "The office sent the documents to your team.",
    },
    {
        "question": 'Translate: "I wrote to her."',
        "answer": ["le escribí", "yo le escribí"],
        "hint": "escribir uses indirect object: le",
        "explanation": "'Escribir' (to write to someone) uses an indirect object: 'le escribí' (I wrote to her/him).",
        "context": "You wrote an email to your friend in Guadalajara.",
    },
    {
        "question": 'Translate: "She sent the package to him."',
        "answer": ["le envió el paquete", "ella le envió el paquete"],
        "hint": "enviar uses indirect object: le",
        "explanation": "'Enviar' (to send) uses indirect object for the recipient: 'le envió' (she sent to him/her). The package is the direct object.",
        "context": "Your coworker sent the package to the client in Monterrey.",
    },
    {
        "question": 'Translate: "I lent the book to her."',
        "answer": ["le presté el libro", "yo le presté el libro"],
        "hint": "prestar uses indirect object: le",
        "explanation": "'Prestar' (to lend) uses indirect object for the person receiving: 'le presté' (I lent to her/him).",
        "context": "You lent the novel to your classmate at the university.",
    },
    {
        "question": 'Translate: "He gave the gift to her."',
        "answer": ["le regaló el regalo", "él le regaló el regalo"],
        "hint": "regalar uses indirect object: le",
        "explanation": "'Regalar' (to give as a gift) uses indirect object: 'le regaló' (he gave the gift to her).",
        "context": "He gave a gift to his girlfriend on their anniversary.",
    },
    {
        "question": 'Translate: "I returned the money to him."',
        "answer": ["le devolví el dinero", "yo le devolví el dinero"],
        "hint": "devolver uses indirect object: le",
        "explanation": "'Devolver' (to return something to someone) uses indirect object: 'le devolví' (I returned to him/her).",
        "context": "You returned the borrowed money to your friend.",
    },
    {
        "question": 'Translate: "She showed the photo to them."',
        "answer": "les mostró la foto",
        "hint": "mostrar uses indirect object: les",
        "explanation": "'Mostrar' (to show) uses indirect object for the audience: 'les mostró' (she showed them). The photo is the direct object.",
        "context": "She showed the vacation photos to her family.",
    },
    {
        "question": 'Translate: "I introduced him to my parents."',
        "answer": ["le presenté a mis papás", "yo le presenté a mis papás"],
        "hint": "presentar uses indirect object: le; note 'a mis papás' is the indirect clarification",
        "explanation": "'Presentar' (to introduce) uses indirect object: 'le presenté a mis papás' (I introduced him to my parents).",
        "context": "You introduced your boyfriend to your parents at a family dinner.",
    },
    {
        "question": 'Translate: "I saw him at the tianguis." (direct object)',
        "answer": "lo vi en el tianguis",
        "hint": "ver uses direct object: lo",
        "explanation": "'Ver' takes a direct object: 'lo vi' (I saw him). Not 'le vi' — that would be leísmo.",
        "context": "You spotted your neighbor at the weekly open-air market.",
    },
    {
        "question": 'Translate: "I told him." (indirect object)',
        "answer": "le dije",
        "hint": "decir uses indirect object: le",
        "explanation": "'Decir' (to tell) uses indirect object for the person told: 'le dije' (I told him/her). Not 'lo dije'.",
        "context": "You told your friend about the party plans.",
    },
    {
        "question": 'Translate: "I know her." (direct object)',
        "answer": "la conozco",
        "hint": "conocer uses direct object: la",
        "explanation": "'Conocer' takes a direct object: 'la conozco' (I know her). Not 'le conozco' — that would be leísmo.",
        "context": "You're talking about a colleague at work.",
    },
    {
        "question": 'Translate: "I told the story to her." (indirect object)',
        "answer": "le conté la historia",
        "hint": "contar uses indirect object: le",
        "explanation": "'Contar' uses indirect object for the listener: 'le conté' (I told her). The story is the direct object.",
        "context": "You told your abuela the story about your day.",
    },
    {
        "question": 'Translate: "I wrote the letter to my wife." (clarification with a)',
        "answer": "le escribí la carta a mi esposa",
        "hint": "clarify 'le' with 'a mi esposa'",
        "explanation": "'Le escribí' alone is ambiguous. 'A mi esposa' clarifies the recipient. Redundant 'a' phrases are normal and preferred.",
        "context": "You wrote the letter to your wife while traveling for work.",
    },
    {
        "question": 'Translate: "She wrote to her boyfriend." (clarification with a)',
        "answer": "le escribió a su novio",
        "hint": "clarify 'le' with 'a su novio'",
        "explanation": "'Le escribió' alone is ambiguous (him/her/you-formal). 'A su novio' clarifies who she wrote to.",
        "context": "Your friend wrote a message to her boyfriend.",
    },
    {
        "question": 'Translate: "The teacher explained it to the students." (clarification with a)',
        "answer": "les explicó a los estudiantes",
        "hint": "clarify 'les' with 'a los estudiantes'",
        "explanation": "'Les explicó' alone is ambiguous. 'A los estudiantes' clarifies who was explained to. This redundancy is standard Spanish.",
        "context": "The teacher explained the grammar rule to the students in class.",
    },
    {
        "question": 'Translate: "He told the truth to his boss." (clarification with a)',
        "answer": "le dijo la verdad a su jefe",
        "hint": "clarify 'le' with 'a su jefe'",
        "explanation": "'Le dijo' is ambiguous. 'A su jefe' clarifies. 'A' phrases with indirect objects are standard, not redundant.",
        "context": "An employee told the truth about the situation to his supervisor.",
    },
    {
        "question": 'Translate: "She told me." (triple emphasis: me lo dijo a mí)',
        "answer": "me lo dijo a mí",
        "hint": "emphatic: me lo dijo + a mí",
        "explanation": "'Me lo dijo a mí' uses triple emphasis: 'me' (indirect pronoun) + 'lo' (direct pronoun) + 'a mí' (clarification). Common for emphasis.",
        "context": "Someone is surprised that she told YOU specifically.",
    },
    {
        "question": 'Translate: "I gave it to YOU." (emphatic: te lo regalé a ti)',
        "answer": "te lo regalé a ti",
        "hint": "emphatic: te lo + a ti",
        "explanation": "'Te lo regalé a ti' emphasizes that it was given to YOU specifically. 'Te' + 'lo' + 'a ti' triple pronoun reference.",
        "context": "You're emphasizing that the gift was specifically for your friend, not someone else.",
    },
    {
        "question": 'Translate: "She told it to US." (emphatic)',
        "answer": "nos lo dijo a nosotros",
        "hint": "emphatic: nos lo + a nosotros",
        "explanation": "'Nos lo dijo a nosotros' emphasizes that she told US specifically. 'Nos' + 'lo' + 'a nosotros' triple reference.",
        "context": "Your team is surprised that the boss told them directly.",
    },
    {
        "question": 'Translate: "I told her." (preterite)',
        "answer": "le dije",
        "hint": "decir, preterite: le dije",
        "explanation": "Preterite of 'decir' (yo): 'dije'. 'Le dije' = I told her/him. 'Le' is the indirect object.",
        "context": "You told your friend what happened at the party.",
    },
    {
        "question": 'Translate: "I was telling her." (imperfect progressive)',
        "answer": "le estaba diciendo",
        "hint": "imperfect progressive: le estaba diciendo",
        "explanation": "Imperfect progressive: 'estaba diciendo' (I was telling). 'Le' = indirect object for the person being told.",
        "context": "You were in the middle of telling your mom the story when the phone rang.",
    },
    {
        "question": 'Translate: "I had already told her." (past perfect)',
        "answer": "le había dicho",
        "hint": "past perfect: le había dicho",
        "explanation": "Past perfect (pluscuamperfecto): 'había dicho' (I had told). 'Le' = indirect object for the person told.",
        "context": "You had already told your friend about the change of plans.",
    },
    {
        "question": 'Translate: "I had already returned it to him." (past perfect + double pronoun)',
        "answer": ["se lo había devuelto", "se lo había devuelto a él"],
        "hint": "le lo → se lo; past perfect",
        "explanation": "Past perfect: 'había devuelto'. Double pronoun: 'le lo' → 'se lo'. 'Se lo había devuelto' = I had already returned it to him.",
        "context": "You confirmed that you had already given the document back to your boss.",
    },
    {
        "question": 'Translate: "She was showing it to them." (imperfect progressive + double pronoun)',
        "answer": "se lo estaba mostrando",
        "hint": "les lo → se lo; imperfect progressive",
        "explanation": "Imperfect progressive with double pronoun: 'se lo estaba mostrando' (or 'estaba mostrándoselo'). 'Les lo' → 'se lo'.",
        "context": "The salesperson was showing the product to the customers at the store.",
    },
    {
        "question": 'Translate: "I wrote the email to the client." (clarification with a)',
        "answer": "le escribí el correo al cliente",
        "hint": "clarify 'le' with 'al cliente'",
        "explanation": "'Le escribí' is ambiguous. 'Al cliente' clarifies. Redundant 'a' phrases are standard with indirect objects.",
        "context": "You wrote the email to the client at work.",
    },
    {
        "question": 'Translate: "The doctor explained it to the patient." (clarification with a)',
        "answer": "se lo explicó al paciente",
        "hint": "le lo → se lo; 'al paciente' clarifies",
        "explanation": "'Le lo' → 'se lo explicó'. 'Al paciente' clarifies the recipient. Double pronoun + redundant 'a' phrase.",
        "context": "The doctor explained the diagnosis to the patient at the clinic.",
    },
    {
        "question": 'Translate: "My mom gave it to me." (me lo dio a mí, emphatic)',
        "answer": "me lo dio a mí",
        "hint": "emphatic: me lo + a mí",
        "explanation": "'Me lo dio a mí' emphasizes that mom gave it to ME specifically. 'Me' + 'lo' + 'a mí' triple reference.",
        "context": "You're emphasizing that your mom gave the recipe specifically to you.",
    },
    {
        "question": 'Translate: "He sent the message to his girlfriend." (clarification with a)',
        "answer": "le mandó el mensaje a su novia",
        "hint": "clarify 'le' with 'a su novia'",
        "explanation": "'Le mandó' is ambiguous. 'A su novia' clarifies. 'Mandar' is very common in Mexican Spanish for sending messages.",
        "context": "He sent a WhatsApp message to his girlfriend.",
    },
    {
        "question": 'Translate: "They offered the job to her." (clarification with a)',
        "answer": "le ofrecieron el trabajo a ella",
        "hint": "clarify 'le' with 'a ella'",
        "explanation": "'Le ofrecieron' is ambiguous. 'A ella' clarifies. 'Ofrecer' uses indirect object for the person offered to.",
        "context": "The company offered the position to the candidate.",
    },
    {
        "question": 'Translate: "I paid him." (indirect object with pagar)',
        "answer": "le pagué",
        "hint": "pagar uses indirect object: le",
        "explanation": "'Pagar' (to pay someone) uses indirect object: 'le pagué' (I paid him/her). The amount, if specified, is the direct object.",
        "context": "You paid the mechanic who fixed your car.",
    },
    {
        "question": 'Translate: "I answered her." (indirect object with responder)',
        "answer": "le respondí",
        "hint": "responder uses indirect object: le",
        "explanation": "'Responder' (to answer/respond to someone) uses indirect object: 'le respondí' (I answered her/him).",
        "context": "You answered your friend's question about the meeting time.",
    },
    {
        "question": 'Translate: "I called her." (direct object with llamar)',
        "answer": "la llamé",
        "hint": "llamar uses direct object: la",
        "explanation": "'Llamar' (to call someone) takes a direct object: 'la llamé' (I called her). Not 'le llamé' — though 'le llamo' is sometimes heard in Mexico for 'I call you (formal)'.",
        "context": "You called your mom on the phone.",
    },
    {
        "question": 'Translate: "She cooked it for us." (indirect + direct)',
        "answer": "nos lo cocinó",
        "hint": "nos + lo; no se transformation needed",
        "explanation": "'Nos' stays 'nos' — only 'le/les' becomes 'se'. 'Nos lo cocinó' = she cooked it for us.",
        "context": "Your abuela cooked the meal for the whole family.",
    },
    {
        "question": 'Translate: "He read it to them." (les lo → se lo)',
        "answer": "se lo leyó",
        "hint": "les lo → se lo",
        "explanation": "'Les lo' becomes 'se lo'. 'Leyó' (preterite of leer). 'Se lo leyó' = he/she read it to them.",
        "context": "The teacher read the story to the children at school.",
    },
    {
        "question": 'Translate: "We brought it for her." (le lo → se lo)',
        "answer": ["se lo trajimos", "se lo trajimos a ella"],
        "hint": "le lo → se lo",
        "explanation": "'Le lo' becomes 'se lo'. 'Trajimos' (preterite of traer). Add 'a ella' for clarity.",
        "context": "You brought the gift from Mexico City for your friend.",
    },
    {
        "question": 'Translate: "She left it for me." (me lo dejó)',
        "answer": "me lo dejó",
        "hint": "me + lo; no se transformation",
        "explanation": "'Me' stays 'me' — only 'le/les' becomes 'se'. 'Me lo dejó' = she left it for me.",
        "context": "Your friend left the book for you at the coffee shop.",
    },
    {
        "question": 'Translate: "I asked him for it." (se lo pedí)',
        "answer": "se lo pedí",
        "hint": "le lo → se lo; pedir uses indirect object",
        "explanation": "'Pedir' uses indirect object: 'le pedí' (I asked him). With 'lo' (it): 'le lo' → 'se lo pedí'.",
        "context": "You asked your boss for the document.",
    },
    {
        "question": 'Translate: "I stole it from her." (se lo robé)',
        "answer": ["se lo robé", "se lo robé a ella"],
        "hint": "le lo → se lo; robar uses indirect for the victim",
        "explanation": "'Robar' uses indirect object for the victim: 'le robé' (I stole from him/her). 'Le lo' → 'se lo robé'.",
        "context": "In a joking conversation about someone taking the last taco.",
    },
    {
        "question": 'Translate: "She promised it to them." (se lo prometió)',
        "answer": "se lo prometió",
        "hint": "les lo → se lo; prometer uses indirect object",
        "explanation": "'Prometer' uses indirect object: 'les prometió' (she promised them). 'Les lo' → 'se lo prometió'.",
        "context": "The boss promised the bonus to the employees.",
    },
    {
        "question": 'Translate: "I forbade it to them." (se lo prohibí)',
        "answer": "se lo prohibí",
        "hint": "les lo → se lo; prohibir uses indirect object",
        "explanation": "'Prohibir' uses indirect object for the person forbidden: 'les prohibí' (I forbade them). 'Les lo' → 'se lo prohibí'.",
        "context": "You forbade your kids from eating the dessert before dinner.",
    },
    {
        "question": 'Translate: "He recommended it to me." (me lo recomendó)',
        "answer": "me lo recomendó",
        "hint": "me + lo; no se transformation",
        "explanation": "'Me' stays 'me'. 'Me lo recomendó' = he recommended it to me. No se transformation needed.",
        "context": "Your friend recommended a taco stand in CDMX to you.",
    },
    {
        "question": 'Translate: "He denied it to me." (me lo negó)',
        "answer": "me lo negó",
        "hint": "me + lo; negar uses indirect object",
        "explanation": "'Negar' (to deny) uses indirect object for the person denied: 'me lo negó' (he denied it to me). 'Me' stays 'me'.",
        "context": "Your boss denied your request for a day off.",
    },
    {
        "question": 'Translate: "She repeated it to us." (nos lo repitió)',
        "answer": "nos lo repitió",
        "hint": "nos + lo; no se transformation needed",
        "explanation": "'Nos' stays 'nos' — only 'le/les' becomes 'se'. 'Nos lo repitió' = she repeated it to us.",
        "context": "The teacher repeated the instructions to the class.",
    },
    {
        "question": 'Translate: "I owe it to him." (se lo debo)',
        "answer": ["se lo debo", "se lo debo a él"],
        "hint": "le lo → se lo; deber uses indirect object",
        "explanation": "'Deber' (to owe) uses indirect object: 'le debo' (I owe him). 'Le lo' → 'se lo debo'.",
        "context": "You owe your friend money for the tacos he bought you.",
    },
    {
        "question": 'Translate: "We explained it to her." (se lo explicamos)',
        "answer": ["se lo explicamos", "se lo explicamos a ella"],
        "hint": "le lo → se lo; explicar uses indirect object",
        "explanation": "'Explicar' uses indirect object for the listener: 'le explicamos' (we explained to her). 'Le lo' → 'se lo explicamos'.",
        "context": "We explained the schedule change to the coordinator.",
    },
    {
        "question": 'Translate: "She sent it (el mensaje) to them." (se lo mandó)',
        "answer": "se lo mandó",
        "hint": "les lo → se lo; mandar uses indirect object",
        "explanation": "'Mandar' uses indirect object: 'les mandó' (she sent to them). 'Les lo' → 'se lo mandó'. In Mexico, 'mandar' is very common.",
        "context": "She sent the WhatsApp message to her coworkers.",
    },
]


pairs = [
    (
        "He told her the truth.",
        ["La dijo la verdad", "Le dijo la verdad", "Se lo dijo la verdad", "Lo dijo la verdad"],
        2,
        "'Decir' takes an indirect object for the person: 'le dijo' (he told her). Not 'la dijo'.",
    ),
    (
        "I saw him at the market.",
        ["Le vi en el mercado", "Lo vi en el mercado", "Se lo vi en el mercado", "Lo vi a él mercado"],
        2,
        "'Ver' takes a direct object: 'lo vi' (I saw him). 'Le vi' is a common error — always 'lo vi'.",
    ),
    (
        "She asked him for a favor.",
        ["Lo pidió un favor", "Le pidió un favor", "Se pidió un favor", "Se lo pidió"],
        2,
        "'Pedir' uses indirect object for the person asked: 'le pidió' (she asked him).",
    ),
    (
        "I gave it to them. (double pronoun)",
        ["Les lo di", "Se lo di", "Los di", "Le lo di"],
        2,
        "'Les lo di' → 'se lo di'. When 'les' combines with 'lo/la/los/las', it becomes 'se'.",
    ),
    (
        "Which is the common Mexican expression meaning 'I'm counting on you'?",
        ["Te lo pido", "Se lo encargo mucho", "Me lo debes", "Le digo mucho"],
        2,
        "'Se lo encargo mucho' is a distinctly Mexican phrase meaning 'I entrust this to you / I'm counting on you.'",
    ),
    (
        "He told Juan.",
        ["Lo dijo a Juan", "Le dijo a Juan", "Se dijo a Juan", "Dijo Juan"],
        2,
        "'Decir' takes indirect object: 'le dijo a Juan'. The 'a Juan' clarifies who 'le' refers to.",
    ),
    (
        "Which pronoun pattern does 'contar' (to tell) use?",
        ["Direct object for the person", "Indirect object for the person", "No pronoun needed", "Reflexive pronoun"],
        2,
        "'Contar' uses indirect object for the person told: 'les conté' (I told them). The story is the direct object.",
    ),
    (
        "They sent them to us. (the packages)",
        ["Les los enviaron", "Se los enviaron", "Nos los enviaron", "Los nos enviaron"],
        3,
        "'Nos' does not become 'se'. Only 'le/les' transforms. 'Nos los enviaron' is correct.",
    ),
    (
        "I wrote to her.",
        ["La escribí", "Le escribí", "Se escribí", "Lo escribí"],
        2,
        "'Escribir' (to write to someone) uses indirect object: 'le escribí'. Not 'la escribí'.",
    ),
    (
        "She sent the package to him.",
        ["Le envió el paquete", "Lo envió el paquete", "Se envió el paquete", "La envió el paquete"],
        1,
        "'Enviar' uses indirect object for the recipient: 'le envió' (she sent to him).",
    ),
    (
        "I lent the book to her.",
        ["La presté el libro", "Le presté el libro", "Se presté el libro", "Lo presté el libro"],
        2,
        "'Prestar' (to lend) uses indirect object: 'le presté' (I lent to her). Not 'la presté'.",
    ),
    (
        "He gave the gift to her.",
        ["Le regaló el regalo", "La regaló el regalo", "Se regaló el regalo", "Lo regaló el regalo"],
        1,
        "'Regalar' (to give as a gift) uses indirect object: 'le regaló' (he gave to her).",
    ),
    (
        "I returned the money to him.",
        ["Le devolví el dinero", "Lo devolví el dinero", "Se devolví el dinero", "La devolví el dinero"],
        1,
        "'Devolver' (to return) uses indirect object: 'le devolví' (I returned to him).",
    ),
    (
        "She showed the photo to them.",
        ["Los mostró la foto", "Les mostró la foto", "Se mostró la foto", "La mostró la foto"],
        2,
        "'Mostrar' (to show) uses indirect object: 'les mostró' (she showed them).",
    ),
    (
        "I saw him at the tianguis.",
        ["Le vi en el tianguis", "Lo vi en el tianguis", "Se vi en el tianguis", "Lo vi a él tianguis"],
        2,
        "'Ver' takes a direct object: 'lo vi' (I saw him). 'Le vi' would be leísmo.",
    ),
    (
        "I told him.",
        ["Lo dije", "Le dije", "Se dije", "Lo dije a él"],
        2,
        "'Decir' uses indirect object for the person told: 'le dije' (I told him). Not 'lo dije'.",
    ),
    (
        "I know her.",
        ["Le conozco", "La conozco", "Se conozco", "Lo conozco"],
        2,
        "'Conocer' takes a direct object: 'la conozco' (I know her). Not 'le conozco'.",
    ),
    (
        "I told the story to her.",
        ["La conté la historia", "Le conté la historia", "Se conté la historia", "Lo conté la historia"],
        2,
        "'Contar' uses indirect object for the listener: 'le conté' (I told her).",
    ),
    (
        "Which verb uses a DIRECT object for the person?",
        ["Decir", "Contar", "Ver", "Escribir"],
        3,
        "'Ver' uses a direct object: 'lo vi' (I saw him). Decir, contar, and escribir use indirect objects.",
    ),
    (
        "Which verb uses an INDIRECT object for the person?",
        ["Conocer", "Ver", "Llamar", "Escribir"],
        4,
        "'Escribir' uses indirect object: 'le escribí' (I wrote to him). Conocer, ver, and llamar use direct objects.",
    ),
    (
        "She wrote to her boyfriend.",
        ["Le escribió a su novio", "La escribió a su novio", "Se escribió a su novio", "Lo escribió a su novio"],
        1,
        "'Escribir' uses indirect object: 'le escribió'. 'A su novio' clarifies the recipient.",
    ),
    (
        "The teacher explained it to the students.",
        ["Se lo explicó a los estudiantes", "Les lo explicó a los estudiantes", "Los explicó a los estudiantes", "Se la explicó a los estudiantes"],
        1,
        "'Les lo' → 'se lo explicó'. 'A los estudiantes' clarifies the recipient.",
    ),
    (
        "I had already told her. (past perfect)",
        ["Le había dicho", "La había dicho", "Se había dicho", "Lo había dicho"],
        1,
        "Past perfect: 'había dicho'. 'Decir' uses indirect object: 'le había dicho' (I had told her).",
    ),
    (
        "She was showing it to them. (imperfect progressive)",
        ["Se lo estaba mostrando", "Les lo estaba mostrando", "Los estaba mostrando", "Se la estaba mostrando"],
        1,
        "'Les lo' → 'se lo'. 'Estaba mostrando' = imperfect progressive. 'Se lo estaba mostrando' is correct.",
    ),
    (
        "He told the truth to his boss.",
        ["Le dijo la verdad a su jefe", "Lo dijo la verdad a su jefe", "Se dijo la verdad a su jefe", "La dijo la verdad a su jefe"],
        1,
        "'Decir' uses indirect object: 'le dijo'. 'A su jefe' clarifies the recipient.",
    ),
    (
        "Which is correct for 'I called her'?",
        ["Le llamé", "La llamé", "Se llamé", "Lo llamé"],
        2,
        "'Llamar' (to call) uses direct object: 'la llamé' (I called her). Not 'le llamé'.",
    ),
    (
        "She cooked it for us.",
        ["Nos lo cocinó", "Se lo cocinó", "Les lo cocinó", "Lo cocinó nos"],
        1,
        "'Nos' stays 'nos'. Only 'le/les' becomes 'se'. 'Nos lo cocinó' is correct.",
    ),
    (
        "He read it to them.",
        ["Les lo leyó", "Se lo leyó", "Los leyó", "Se la leyó"],
        2,
        "'Les lo' → 'se lo'. 'Se lo leyó' = he read it to them.",
    ),
    (
        "I paid him.",
        ["Lo pagué", "Le pagué", "Se pagué", "La pagué"],
        2,
        "'Pagar' (to pay someone) uses indirect object: 'le pagué' (I paid him).",
    ),
    (
        "I answered her.",
        ["La respondí", "Le respondí", "Se respondí", "Lo respondí"],
        2,
        "'Responder' (to answer someone) uses indirect object: 'le respondí' (I answered her).",
    ),
    (
        "She left it for me.",
        ["Me lo dejó", "Se lo dejó", "Le lo dejó", "Lo dejó me"],
        1,
        "'Me' stays 'me'. 'Me lo dejó' = she left it for me. No 'se' transformation.",
    ),
    (
        "I asked him for it.",
        ["Lo pedí", "Se lo pedí", "Le pedí lo", "Se la pedí"],
        2,
        "'Pedir' uses indirect object: 'le pedí' (I asked him). 'Le lo' → 'se lo pedí'.",
    ),
    (
        "He recommended it to me.",
        ["Me lo recomendó", "Se lo recomendó", "Lo recomendó me", "Le lo recomendó"],
        1,
        "'Me' stays 'me'. 'Me lo recomendó' = he recommended it to me. No 'se' transformation.",
    ),
    (
        "She promised it to them.",
        ["Se lo prometió", "Les lo prometió", "Los prometió", "Se la prometió"],
        1,
        "'Les lo' → 'se lo'. 'Se lo prometió' = she promised it to them.",
    ),
    (
        "What is 'leísmo'?",
        ["Using 'le' for a female direct object", "Using 'le' for a male direct object (instead of 'lo')", "Using 'lo' for an indirect object", "Using 'se' instead of 'le'"],
        2,
        "Leísmo is using 'le' for a male direct object (e.g., 'le vi' instead of 'lo vi'). It's somewhat accepted in Spain for males, but less common in Mexico.",
    ),
    (
        "In Mexico, which is more common for 'I saw him'?",
        ["Le vi", "Lo vi"],
        2,
        "In Mexico, 'lo vi' is the standard form. 'Le vi' (leísmo) is less common and generally considered incorrect in Mexican Spanish.",
    ),
    (
        "I wrote the email to the client.",
        ["Le escribí el correo al cliente", "Lo escribí el correo al cliente", "Se escribí el correo al cliente", "La escribí el correo al cliente"],
        1,
        "'Escribir' uses indirect object: 'le escribí'. 'Al cliente' clarifies the recipient.",
    ),
    (
        "I owe it to him.",
        ["Se lo debo", "Le lo debo", "Lo debo le", "Se la debo"],
        1,
        "'Deber' uses indirect object: 'le debo'. 'Le lo' → 'se lo debo'.",
    ),
]


if __name__ == "__main__":
    run_exercises(exercises, title="Lección 4: Object Reference — He told her / The woman gave him")
    choose_translation(pairs, title="Lección 4: Choose the Best Translation")