import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

from workbook_engine import run_exercises, choose_translation


exercises = [
    {
        "question": 'Translate: "I\'m looking for a person who knows how to cook." (unknown person)',
        "answer": ["busco una persona que sepa cocinar", "busco a una persona que sepa cocinar"],
        "hint": "Unknown antecedent → subjunctive (sepa, not sabe)",
        "explanation": "When the antecedent is unknown/hypothetical, Spanish uses the subjunctive: 'sepa' (not 'sabe'). You don't know if such a person exists yet.",
        "context": "You're posting a job ad at a restaurant in CDMX.",
    },
    {
        "question": 'Translate: "I have a person who knows how to cook." (known person)',
        "answer": ["tengo una persona que sabe cocinar", "tengo a una persona que sabe cocinar"],
        "hint": "Known antecedent → indicative (sabe, not sepa)",
        "explanation": "When you already have/know the person, the antecedent is definite → indicative 'sabe'. Compare: unknown → subjunctive, known → indicative.",
        "context": "You already hired someone at your fonda in Oaxaca.",
    },
    {
        "question": 'Translate: "I need a hotel that has a pool." (unknown which hotel)',
        "answer": ["necesito un hotel que tenga alberca", "necesito un hotel que tenga piscina"],
        "hint": "Unknown → subjunctive 'tenga'; Mexican: alberca (not piscina)",
        "explanation": "In Mexican Spanish, 'alberca' is the common word for pool (not 'piscina'). The hotel is unknown → subjunctive 'tenga'.",
        "context": "You're booking a hotel in Cancún for vacation.",
    },
    {
        "question": 'Translate: "So that you can rest, I\'ll make dinner."',
        "answer": ["para que descanses, yo hago la cena", "para que descanses, haré la cena", "para que puedas descansar, hago la cena"],
        "hint": "para que → always subjunctive",
        "explanation": "'Para que' always triggers the subjunctive because it expresses purpose/intent. 'Para que descanses' (so that you rest).",
        "context": "Your partner just came home tired from work in Monterrey.",
    },
    {
        "question": 'Translate: "We\'re saving money so that we can buy a house."',
        "answer": ["estamos ahorrando dinero para que podamos comprar una casa", "ahorramos dinero para que podamos comprar una casa"],
        "hint": "para que + subjunctive",
        "explanation": "'Para que' expresses purpose → subjunctive 'podamos'. In Mexican Spanish, buying a house ('casa') is a common life goal discussed openly.",
        "context": "You and your spouse are planning to buy a home in Guadalajara.",
    },
    {
        "question": 'Translate: "Although it rains, we\'re going to the mercado." (it IS raining, factual)',
        "answer": ["aunque llueve, vamos al mercado", "aunque llueve, vamos a ir al mercado", "aunque está lloviendo, vamos al mercado"],
        "hint": "aunque + indicative = factual 'although'",
        "explanation": "'Aunque' + indicative = you know it's a fact (it IS raining). 'Aunque llueve' = although it IS raining. Contrast with subjunctive 'aunque llueva' = even if it rains (hypothetical).",
        "context": "It's raining right now, but you still want to go to the tianguis.",
    },
    {
        "question": 'Translate: "Even if it rains, we\'re going to the mercado." (hypothetical)',
        "answer": ["aunque llueva, vamos al mercado", "aunque llueva, iremos al mercado"],
        "hint": "aunque + subjunctive = hypothetical 'even if'",
        "explanation": "'Aunque' + subjunctive = hypothetical/uncertain. 'Aunque llueva' = even IF it rains (not yet happening). This is the key contrast Mexican speakers make.",
        "context": "The sky looks cloudy but it hasn't started raining yet.",
    },
    {
        "question": 'Translate: "As soon as you arrive, call me." (future arrival)',
        "answer": ["en cuanto llegues, llámame", "tan pronto como llegues, llámame", "en cuanto llegues, márcame"],
        "hint": "en cuanto + subjunctive for future/unknown",
        "explanation": "Time clauses ('en cuanto', 'tan pronto como') use subjunctive when referring to future/unknown events. 'Llegues' (subjunctive) because the arrival hasn't happened yet.",
        "context": "Your friend is traveling to CDMX and you want them to call when they get there.",
    },
    {
        "question": 'Translate: "I\'ll wait until you finish." (future completion)',
        "answer": ["esperaré hasta que termines", "espero hasta que termines", "esperaré hasta que acabes"],
        "hint": "hasta que + subjunctive for future/unknown",
        "explanation": "'Hasta que' uses subjunctive when the event is future/unknown: 'hasta que termines'. If it were a known/habitual fact: 'hasta que terminas' (indicative).",
        "context": "You're waiting at a café in Roma Norte for your friend to finish work.",
    },
    {
        "question": 'Translate: "Before you leave, turn off the lights."',
        "answer": ["antes de que salgas, apaga las luces", "antes de que te vayas, apaga las luces", "antes de que salgas, apaga la luz"],
        "hint": "antes de que → always subjunctive",
        "explanation": "'Antes de que' ALWAYS takes the subjunctive because the event hasn't happened yet. 'Antes de que salgas' — the leaving is still in the future.",
        "context": "Reminding your roommate before they head out in the evening.",
    },
    {
        "question": 'Translate: "She left without saying goodbye."',
        "answer": ["se fue sin que nadie se despidiera", "se fue sin despedirse", "se fue sin que se despidiera"],
        "hint": "sin que → always subjunctive",
        "explanation": "'Sin que' always requires subjunctive because it describes an absence of an action. 'Se fue sin despedirse' (reflexive) is more common in casual Mexican speech; 'sin que + subjunctive' is more formal.",
        "context": "Your coworker at the office in Polanco left abruptly.",
    },
    {
        "question": 'Translate: "Provided that you study, you\'ll pass the exam."',
        "answer": ["con tal de que estudies, aprobarás el examen", "con tal de que estudies, pasarás el examen"],
        "hint": "con tal de que → always subjunctive",
        "explanation": "'Con tal de que' (provided that) always triggers subjunctive. 'Con tal de que estudies' — the studying is conditional/hypothetical.",
        "context": "Your mamá is encouraging you before finals at UNAM.",
    },
    {
        "question": 'Translate: "You can go to the party on the condition that you come home by midnight."',
        "answer": ["puedes ir a la fiesta a condición de que llegues a casa antes de las doce", "puedes ir a la fiesta a condición de que llegues a casa antes de la medianoche", "puedes ir a la fiesta con la condición de que vuelvas a casa antes de las doce"],
        "hint": "a condición de que → always subjunctive",
        "explanation": "'A condición de que' (on the condition that) always requires subjunctive. In Mexican Spanish, parents commonly set this condition for parties ('pachangas').",
        "context": "A Mexican parent setting conditions for their teenager.",
    },
    {
        "question": 'Translate: "Whenever it rains, the streets flood." (habitual fact)',
        "answer": ["siempre que llueve, se inundan las calles", "siempre que llueve, las calles se inundan", "cuando llueve, se inundan las calles"],
        "hint": "siempre que + indicative = habitual/general",
        "explanation": "'Siempre que' + indicative = whenever (habitual fact). 'Siempre que llueve' = whenever it rains (it's a known pattern). Subjunctive 'siempre que llueva' = 'provided that it rains' (conditional).",
        "context": "Describing CDMX's rainy season flooding — it happens every time.",
    },
    {
        "question": 'Translate: "After you eat, we can go to the zócalo." (future meal)',
        "answer": ["después de que comas, podemos ir al zócalo", "después de que comas, podemos ir a la plaza", "después de que comas, podremos ir al zócalo"],
        "hint": "después de que + subjunctive for future",
        "explanation": "'Después de que' uses subjunctive for future events: 'después de que comas'. If describing a habitual past action: 'después de que comía' (imperfect indicative). The zócalo is the main plaza in Mexican cities.",
        "context": "Planning an afternoon walk after lunch in Puebla.",
    },
    {
        "question": 'Translate: "I want to find a restaurant that serves mole." (unknown which restaurant)',
        "answer": ["quiero encontrar un restaurante que sirva mole", "quiero encontrar un lugar que sirva mole"],
        "hint": "Unknown restaurant → subjunctive 'sirva'",
        "explanation": "You don't know which restaurant serves mole → subjunctive 'sirva'. If you said 'El restaurante que sirve mole' (the one that DOES serve mole) → indicative 'sirve'. Mole is an iconic Mexican dish.",
        "context": "You're visiting Oaxaca and want authentic mole negro.",
    },
    {
        "question": 'Translate: "There is no one who can fix this."',
        "answer": ["no hay nadie que pueda arreglar esto", "no hay nadie que pueda reparar esto", "no hay nadie que pueda componer esto"],
        "hint": "Negative antecedent → subjunctive",
        "explanation": "Negative/indefinite antecedents ('no hay nadie que') always trigger subjunctive: 'pueda'. In Mexican Spanish, 'arreglar' or 'componer' are common for 'fix'.",
        "context": "Your car broke down on the highway near Querétaro and no mechanic is available.",
    },
    {
        "question": 'Translate: "I\'m looking for a place that has good WiFi." (unknown place)',
        "answer": ["busco un lugar que tenga buen wifi", "busco un lugar que tenga buena conexión"],
        "hint": "Unknown antecedent → subjunctive 'tenga'",
        "explanation": "You don't know which place has WiFi → subjunctive 'tenga'. In Mexican Spanish, 'wifi' is commonly used (pronounced 'wiffi').",
        "context": "You're in a café in Condesa and need to get some work done.",
    },
    {
        "question": 'Translate: "There\'s nothing that can compare to Mexican food."',
        "answer": ["no hay nada que pueda compararse con la comida mexicana", "no hay nada que se compare con la comida mexicana"],
        "hint": "Negative/indefinite antecedent → subjunctive 'pueda' or 'se compare'",
        "explanation": "'No hay nada que' is a negative/indefinite antecedent → subjunctive 'pueda' or 'se compare'. Mexican food is world-renowned, from tacos to mole.",
        "context": "Discussing cuisine with a foreign friend visiting Mexico.",
    },
    {
        "question": 'Translate: "Whoever comes to the party is welcome."',
        "answer": ["quienquiera que venga a la fiesta es bienvenido", "quienquiera que venga a la fiesta, es bienvenido", "quienquiera que venga a la fiesta es bienvenida"],
        "hint": "quienquiera que → always subjunctive",
        "explanation": "'Quienquiera que' (whoever) is an indefinite relative → subjunctive 'venga'. The subjunctive emphasizes that you don't know who specifically will come.",
        "context": "You're hosting a posada and telling your friends everyone is invited.",
    },
    {
        "question": 'Translate: "Wherever you are, I\'ll find you."',
        "answer": ["dondequiera que estés, te encontraré", "dondequiera que estés, yo te encuentro"],
        "hint": "dondequiera que → always subjunctive",
        "explanation": "'Dondequiera que' (wherever) is an indefinite relative → subjunctive 'estés'. The subjunctive expresses uncertainty about the location.",
        "context": "A dramatic text message to a friend who moved to another state in Mexico.",
    },
    {
        "question": 'Translate: "Whatever it may be, we\'ll solve it."',
        "answer": ["cualquiera que sea, lo resolveremos", "cualquiera que sea, lo solucionaremos"],
        "hint": "cualquiera que → always subjunctive 'sea'",
        "explanation": "'Cualquiera que sea' (whatever it may be) uses subjunctive 'sea' because the specific thing is unknown. This is a set phrase in Mexican Spanish.",
        "context": "Your coworker at the office is worried about an unspecified problem.",
    },
    {
        "question": 'Translate: "I turned off my phone so that nobody would call me."',
        "answer": ["apagué mi celular para que nadie me llamara", "apagué mi teléfono para que nadie me llamara", "apagué mi celular para que nadie me llame"],
        "hint": "para que → always subjunctive; past context → imperfect subjunctive",
        "explanation": "'Para que' always triggers subjunctive. Since the main verb is past ('apagué'), the subjunctive should be imperfect: 'llamara'. In Mexican Spanish, 'celular' is preferred over 'teléfono móvil'.",
        "context": "You wanted to sleep through the night without interruptions in your apartment in Monterrey.",
    },
    {
        "question": 'Translate: "They organized the event so that everyone could participate." (a fin de que)',
        "answer": ["organizaron el evento a fin de que todos pudieran participar", "organizaron el evento a fin de que todos participaran"],
        "hint": "a fin de que → always subjunctive; past context → imperfect subjunctive",
        "explanation": "'A fin de que' (in order that/so that) always triggers subjunctive, just like 'para que'. With past main verb → imperfect subjunctive 'pudieran'. Formal synonym of 'para que'.",
        "context": "A university in Guadalajara organized a cultural festival for inclusivity.",
    },
    {
        "question": 'Translate: "I wrote the email with the purpose of clarifying the situation."',
        "answer": ["escribí el correo con el propósito de que se aclarara la situación", "escribí el correo con el propósito de que la situación se aclarara"],
        "hint": "con el propósito de que → always subjunctive",
        "explanation": "'Con el propósito de que' (with the purpose of) always triggers subjunctive. Past context → imperfect subjunctive 'aclarara'. Formal way to express purpose.",
        "context": "You sent a clarification email to your team at work in Santa Fe, CDMX.",
    },
    {
        "question": 'Translate: "Even if it\'s expensive, I\'m going to buy it." (hypothetical)',
        "answer": ["aunque esté caro, lo voy a comprar", "aunque esté caro, lo compro"],
        "hint": "aunque + subjunctive = hypothetical 'even if'",
        "explanation": "'Aunque esté caro' = even IF it's expensive (you don't know the price yet, or it's hypothetical). Subjunctive 'esté' signals uncertainty. Mexican: 'caro' for expensive.",
        "context": "You really want those huaraches at the artisan market and don't care about the price.",
    },
    {
        "question": 'Translate: "Although it\'s expensive, I\'m buying it." (factual — you know the price)',
        "answer": ["aunque está caro, lo compro", "aunque es caro, lo compro", "aunque está caro, lo voy a comprar"],
        "hint": "aunque + indicative = factual 'although'",
        "explanation": "'Aunque está caro' = although it IS expensive (you already know the price — factual). Indicative 'está' vs subjunctive 'esté' is the key contrast in Mexican Spanish.",
        "context": "You already saw the price tag at Liverpool but you're buying it anyway.",
    },
    {
        "question": 'Translate: "Despite the fact that it might rain, we\'re going to the tianguis."',
        "answer": ["a pesar de que pueda llover, vamos al tianguis", "a pesar de que llueva, vamos al tianguis"],
        "hint": "a pesar de que + subjunctive = hypothetical/concessive",
        "explanation": "'A pesar de que' + subjunctive = despite the possibility (hypothetical). 'Pueda llover' or 'llueva' = it might rain, but we're going anyway. 'Tianguis' is the Mexican word for open-air market.",
        "context": "The sky looks threatening but you need to buy produce at the weekly tianguis.",
    },
    {
        "question": 'Translate: "No matter how much you practice, you won\'t beat me."',
        "answer": ["por más que practiques, no me vas a ganar", "por mucho que practiques, no me vas a ganar"],
        "hint": "por más que + subjunctive = concessive 'no matter how much'",
        "explanation": "'Por más que' (no matter how much) + subjunctive = concessive. 'Practiques' is subjunctive because the amount of practice is hypothetical. Very common in competitive Mexican contexts, especially fútbol.",
        "context": "Trash-talking your friend before a FIFA match.",
    },
    {
        "question": 'Translate: "Although the team lost, the fans supported them." (factual past)',
        "answer": ["aunque el equipo perdió, la afición los apoyó", "si bien el equipo perdió, la afición los apoyó"],
        "hint": "aunque/si bien + indicative for factual statements about the past",
        "explanation": "'Aunque perdió' or 'si bien perdió' + indicative = factual concession (the loss is a known fact). 'Afición' is the Mexican term for fans/fanbase. 'Si bien' is a more formal alternative to 'aunque'.",
        "context": "Discussing how Cruz Azul's fans stayed loyal despite a tough loss.",
    },
    {
        "question": 'Translate: "When you get to Puebla, call me." (future arrival)',
        "answer": ["cuando llegues a Puebla, llámame", "cuando llegues a Puebla, márcame"],
        "hint": "cuando + subjunctive for future/unknown events",
        "explanation": "'Cuando' + subjunctive for future arrival: 'llegues'. If it were a habitual action: 'cuando llegas' (indicative). Mexican: 'llámame' or 'márcame' for 'call me'.",
        "context": "Your friend is taking a bus to Puebla and you want them to call when they arrive.",
    },
    {
        "question": 'Translate: "As soon as the metro arrives, we\'ll get on."',
        "answer": ["en cuanto llegue el metro, nos subiremos", "tan pronto como llegue el metro, nos subimos"],
        "hint": "en cuanto + subjunctive for future events",
        "explanation": "'En cuanto' + subjunctive 'llegue' for future/unknown arrival. 'Metro' is the Mexico City subway system. 'Nos subiremos' (future) or 'nos subimos' (present with future meaning).",
        "context": "Waiting on the platform at a metro station in CDMX during rush hour.",
    },
    {
        "question": 'Translate: "We\'ll order as soon as the waiter comes."',
        "answer": ["pediremos tan pronto como venga el mesero", "vamos a pedir tan pronto como venga el mesero", "pediremos tan pronto como llegue el mesero"],
        "hint": "tan pronto como + subjunctive for future events",
        "explanation": "'Tan pronto como' + subjunctive 'venga' for future/unknown arrival. In Mexican Spanish, 'mesero' is preferred over 'camarero'. 'Pedir' = to order (food).",
        "context": "You're at a restaurant in San Ángel waiting for the waiter.",
    },
    {
        "question": 'Translate: "I won\'t leave until you come back."',
        "answer": ["no me voy hasta que regreses", "no me voy hasta que vuelvas", "no me iré hasta que regreses"],
        "hint": "hasta que + subjunctive for future/unknown",
        "explanation": "'Hasta que' + subjunctive 'regreses' because the return is future/uncertain. In Mexican Spanish, 'regresar' is more common than 'volver' for 'to return'.",
        "context": "Waiting for your friend at a café in Roma Norte who stepped out.",
    },
    {
        "question": 'Translate: "Before they start the meeting, let me check something."',
        "answer": ["antes de que empiece la junta, déjame revisar algo", "antes de que comience la junta, déjame revisar algo"],
        "hint": "antes de que → always subjunctive",
        "explanation": "'Antes de que' ALWAYS triggers subjunctive: 'empiece'. The meeting hasn't started yet. 'Junta' is the common Mexican word for a business meeting.",
        "context": "At the office in Polanco, you need to verify something before the meeting starts.",
    },
    {
        "question": 'Translate: "After you graduate, you can look for a job."',
        "answer": ["después de que te gradúes, puedes buscar trabajo", "después de que te gradúes, puedes buscar chamba"],
        "hint": "después de que + subjunctive for future events",
        "explanation": "'Después de que' + subjunctive 'te gradúes' because graduation is future. In Mexican Spanish, 'chamba' is colloquial for 'work/job', while 'trabajo' is standard.",
        "context": "Advising a student at UNAM about their post-graduation plans.",
    },
    {
        "question": 'Translate: "She left the meeting without anyone noticing."',
        "answer": ["se fue de la junta sin que nadie se diera cuenta", "se fue de la reunión sin que nadie se diera cuenta"],
        "hint": "sin que → always subjunctive; past context → imperfect subjunctive",
        "explanation": "'Sin que' always requires subjunctive. Past context → imperfect subjunctive 'se diera cuenta'. 'Darse cuenta' = to realize/notice. Very common Mexican expression.",
        "context": "A coworker slipped out of the meeting in Santa Fe without anyone noticing.",
    },
    {
        "question": 'Translate: "You can use my computer provided that you don\'t download anything."',
        "answer": ["puedes usar mi computadora con tal de que no descargues nada", "puedes usar mi computadora con tal de que no bajes nada"],
        "hint": "con tal de que → always subjunctive",
        "explanation": "'Con tal de que' (provided that) always triggers subjunctive: 'descargues'. Mexican: 'computadora' (not 'ordenador'), 'descargar' or colloquially 'bajar'.",
        "context": "Lending your laptop to a classmate at Tec de Monterrey.",
    },
    {
        "question": 'Translate: "I\'ll go to the wedding on the condition that you come with me."',
        "answer": ["iré a la boda a condición de que vayas conmigo", "iré a la boda con la condición de que vayas conmigo"],
        "hint": "a condición de que → always subjunctive",
        "explanation": "'A condición de que' always requires subjunctive: 'vayas'. The condition is future/hypothetical. Mexican weddings are big social events.",
        "context": "You don't want to go alone to a friend's wedding in Jalisco.",
    },
    {
        "question": 'Translate: "Whenever you want, we can practice Spanish." (conditional)',
        "answer": ["siempre que quieras, podemos practicar español", "siempre y cuando quieras, podemos practicar español"],
        "hint": "siempre que + subjunctive = 'whenever/provided that' (conditional)",
        "explanation": "'Siempre que' + subjunctive = 'provided that/whenever' (conditional meaning). If it were a habitual fact: 'siempre que quiero' (indicative) = 'whenever I want' (general truth).",
        "context": "Offering a language exchange partner flexibility in scheduling.",
    },
    {
        "question": 'Translate: "You can stay here as long as you follow the rules."',
        "answer": ["puedes quedarte aquí siempre y cuando sigas las reglas", "puedes quedarte aquí siempre y cuando cumplas las reglas"],
        "hint": "siempre y cuando → always subjunctive",
        "explanation": "'Siempre y cuando' (as long as) always triggers subjunctive: 'sigas' or 'cumplas'. Very common in Mexican Spanish for setting conditions. 'Reglas' or 'reglamento'.",
        "context": "Your landlord in CDMX is explaining the terms of your lease renewal.",
    },
    {
        "question": 'Translate: "I won\'t go unless they invite me."',
        "answer": ["no iré a menos que me inviten", "no voy a menos que me inviten"],
        "hint": "a menos que → always subjunctive",
        "explanation": "'A menos que' (unless) always triggers subjunctive: 'inviten'. The invitation is hypothetical/uncertain. Common in Mexican social contexts.",
        "context": "You don't want to crash a party in Colonia del Valle without an invitation.",
    },
    {
        "question": 'Translate: "As long as you study, you\'ll pass." (conditional)',
        "answer": ["mientras estudies, aprobarás", "mientras estudies, pasarás"],
        "hint": "mientras + subjunctive = 'as long as' (conditional)",
        "explanation": "'Mientras' + subjunctive = 'as long as' (conditional): 'mientras estudies'. Contrast with 'mientras' + indicative = 'while' (simultaneous action): 'mientras estudias' = while you're studying.",
        "context": "A parent in Guadalajara encouraging their child before final exams.",
    },
    {
        "question": 'Translate: "While you\'re studying, I\'ll make dinner." (simultaneous action)',
        "answer": ["mientras estudias, hago la cena", "mientras estudias, haré la cena", "mientras tú estudias, yo hago la cena"],
        "hint": "mientras + indicative = 'while' (simultaneous, factual)",
        "explanation": "'Mientras' + indicative = 'while' (simultaneous factual action): 'mientras estudias'. Contrast with 'mientras' + subjunctive = 'as long as' (conditional). This is a key distinction.",
        "context": "Your roommate is studying and you're making dinner at your apartment.",
    },
    {
        "question": 'Translate: "This is the best taquería that exists in the neighborhood."',
        "answer": ["esta es la mejor taquería que haya en la colonia", "esta es la mejor taquería que existe en la colonia"],
        "hint": "Superlative + relative clause can use subjunctive (que haya)",
        "explanation": "After superlatives, both subjunctive 'que haya' and indicative 'que existe' are acceptable. Subjunctive 'que haya' emphasizes the uniqueness claim. 'Colonia' is the Mexican term for 'neighborhood'.",
        "context": "Recommending your favorite taco spot in your colonia to a friend.",
    },
    {
        "question": 'Translate: "That\'s the best movie I\'ve ever seen."',
        "answer": ["esa es la mejor película que haya visto jamás", "esa es la mejor película que he visto jamás", "esa es la mejor película que haya visto nunca"],
        "hint": "Superlative + present perfect subjunctive: que haya visto",
        "explanation": "After superlatives, the present perfect subjunctive 'que haya visto' is common in Mexican Spanish. Also valid: 'que he visto' (indicative). 'Jamás' or 'nunca' = ever.",
        "context": "After watching Roma by Alfonso Cuarón, you're raving about it.",
    },
    {
        "question": 'Translate: "Maybe it\'ll rain this afternoon." (future possibility)',
        "answer": ["quizás llueva esta tarde", "tal vez llueva esta tarde"],
        "hint": "quizás/tal vez + subjunctive for future possibility",
        "explanation": "'Quizás' or 'tal vez' + subjunctive for future uncertain events: 'llueva'. If referring to past or present, indicative is also used. For future possibility, subjunctive is preferred in Mexican Spanish.",
        "context": "Looking at the clouds over CDMX during the rainy season.",
    },
    {
        "question": 'Translate: "Perhaps they\'ll arrive early." (future possibility)',
        "answer": ["tal vez lleguen temprano", "quizás lleguen temprano"],
        "hint": "tal vez + subjunctive for future possibility",
        "explanation": "'Tal vez' + subjunctive for future possibility: 'lleguen'. Both 'quizás' and 'tal vez' work identically. In Mexican Spanish, 'tal vez' is slightly more colloquial.",
        "context": "Wondering if your friends will get to the cantina before you.",
    },
    {
        "question": 'Translate: "I need a mechanic who can fix my car." (unknown mechanic)',
        "answer": ["necesito un mecánico que pueda arreglar mi coche", "necesito un mecánico que pueda componer mi coche", "necesito un mecánico que pueda reparar mi coche"],
        "hint": "Unknown antecedent → subjunctive 'pueda'",
        "explanation": "You don't know which mechanic can fix it → subjunctive 'pueda'. Mexican: 'coche' or 'carro' (not 'auto'), 'arreglar' or 'componer' for 'fix'.",
        "context": "Your car broke down on the Periférico and you need someone reliable.",
    },
    {
        "question": 'Translate: "There\'s no one who knows this neighborhood better than me."',
        "answer": ["no hay nadie que conozca esta colonia mejor que yo", "no hay nadie que sepa esta colonia mejor que yo"],
        "hint": "Negative antecedent → subjunctive 'conozca' or 'sepa'",
        "explanation": "'No hay nadie que' (negative antecedent) always triggers subjunctive: 'conozca' or 'sepa'. 'Colonia' is the Mexican term for neighborhood.",
        "context": "You grew up in Coyoacán and know every street.",
    },
    {
        "question": 'Translate: "Whatever happens, we\'ll stay calm."',
        "answer": ["pase lo que pase, nos mantendremos tranquilos", "pase lo que pase, estaremos tranquilos"],
        "hint": "pase lo que pase = set phrase with double subjunctive",
        "explanation": "'Pase lo que pase' (whatever happens) is a set phrase using subjunctive in both clauses. The first 'pase' is subjunctive of 'pasar' (whatever may happen), the second reinforces it.",
        "context": "Reassuring your family during uncertain times in Mexico.",
    },
    {
        "question": 'Translate: "Speak louder so that everyone can hear you."',
        "answer": ["habla más fuerte para que todos puedan escucharte", "habla más fuerte para que todos te escuchen", "habla más alto para que todos puedan escucharte"],
        "hint": "para que → always subjunctive",
        "explanation": "'Para que' always triggers subjunctive: 'puedan' or 'escuchen'. In Mexican Spanish, 'hablar más fuerte' or 'hablar más alto' for 'speak louder'.",
        "context": "At a family gathering, your abuela can't hear you from across the room.",
    },
    {
        "question": 'Translate: "We brought jackets in case it gets cold."',
        "answer": ["trajimos chamarras en caso de que haga frío", "trajimos chamarras por si hace frío"],
        "hint": "en caso de que → always subjunctive; 'por si' takes indicative",
        "explanation": "'En caso de que' + subjunctive 'haga' = in case (formal). Alternatively, 'por si' + indicative 'hace' = in case (more casual). Mexican: 'chamarra' for jacket/coat.",
        "context": "Going to the mountains near Nevado de Toluca and preparing for cold weather.",
    },
    {
        "question": 'Translate: "Although they\'re siblings, they\'re very different." (factual)',
        "answer": ["aunque son hermanos, son muy diferentes", "aunque son hermanos, son muy distintos"],
        "hint": "aunque + indicative for factual statements",
        "explanation": "'Aunque son' = although they ARE (factual). You know they're siblings. Compare: 'aunque sean hermanos' = even if they were siblings (hypothetical), which makes no sense here.",
        "context": "Commenting on how different two Mexican siblings are from each other.",
    },
    {
        "question": 'Translate: "Even if they offered me a million pesos, I wouldn\'t sell it."',
        "answer": ["aunque me ofrecieran un millón de pesos, no lo vendería", "aunque me ofrecieran un millón de pesos, no lo vendería"],
        "hint": "aunque + imperfect subjunctive = hypothetical concession",
        "explanation": "'Aunque' + imperfect subjunctive 'ofrecieran' for a hypothetical/unreal concession. Conditional 'vendería' in the main clause. This is a 'si' clause pattern with 'aunque'.",
        "context": "Refusing to sell your family home in San Miguel de Allende no matter the offer.",
    },
    {
        "question": 'Translate: "No matter how much you explain it, I don\'t get it."',
        "answer": ["por más que lo expliques, no lo entiendo", "por mucho que lo expliques, no lo entiendo"],
        "hint": "por más que + subjunctive = 'no matter how much'",
        "explanation": "'Por más que' + subjunctive 'expliques' = no matter how much you explain (hypothetical/repeated effort). Contrast: 'por más que lo explicas' (indicative) = no matter how much you explain it (you actually are explaining it).",
        "context": "Your friend is trying to explain a complicated Mexican tax rule and you're lost.",
    },
    {
        "question": 'Translate: "Before you sign, read the contract carefully."',
        "answer": ["antes de que firmes, lee el contrato con cuidado", "antes de que firmes, lee bien el contrato"],
        "hint": "antes de que → always subjunctive",
        "explanation": "'Antes de que' ALWAYS takes subjunctive: 'firmes'. The signing hasn't happened yet. Very common in legal/formal Mexican contexts.",
        "context": "A notario in Mexico advising you before signing a property deed.",
    },
    {
        "question": 'Translate: "I won\'t believe it until I see it with my own eyes."',
        "answer": ["no lo creeré hasta que lo vea con mis propios ojos", "no lo voy a creer hasta que lo vea con mis propios ojos"],
        "hint": "hasta que + subjunctive for future/unknown",
        "explanation": "'Hasta que' + subjunctive 'vea' because the seeing is future/uncertain. This is a common Mexican expression showing skepticism.",
        "context": "Your friend claims they saw a celebrity at the airport and you don't believe it.",
    },
    {
        "question": 'Translate: "You can go out to play as long as you do your homework first."',
        "answer": ["puedes salir a jugar siempre y cuando hagas tu tarea primero", "puedes salir a jugar siempre y cuando primero hagas tu tarea"],
        "hint": "siempre y cuando → always subjunctive",
        "explanation": "'Siempre y cuando' (as long as) always triggers subjunctive: 'hagas'. Common condition parents set for children in Mexico. 'Tarea' = homework.",
        "context": "A Mexican parent setting conditions before letting their kid go out to play.",
    },
    {
        "question": 'Translate: "Unless it rains, we\'ll have the barbecue."',
        "answer": ["a menos que llueva, haremos la carne asada", "a menos que llueva, vamos a hacer carne asada"],
        "hint": "a menos que → always subjunctive",
        "explanation": "'A menos que' (unless) always triggers subjunctive: 'llueva'. 'Carne asada' is a beloved Mexican tradition, especially in northern Mexico.",
        "context": "Planning a Sunday carne asada in Monterrey and checking the weather.",
    },
    {
        "question": 'Translate: "This is the worst traffic I\'ve ever seen."',
        "answer": ["este es el peor tráfico que haya visto jamás", "este es el peor tráfico que he visto jamás"],
        "hint": "Superlative + present perfect subjunctive: que haya visto",
        "explanation": "After superlatives, both subjunctive 'que haya visto' and indicative 'que he visto' are acceptable. Subjunctive emphasizes the extreme claim. CDMX traffic is notoriously bad.",
        "context": "Stuck in traffic on Periférico during rush hour in Mexico City.",
    },
    {
        "question": 'Translate: "Maybe the exam will be postponed." (future possibility)',
        "answer": ["quizás se posponga el examen", "tal vez se posponga el examen"],
        "hint": "quizás/tal vez + subjunctive for future possibility",
        "explanation": "'Quizás' + subjunctive 'se posponga' for future possibility. 'Posponer' → 'se posponga' (subjunctive). In Mexican schools, exams sometimes get postponed.",
        "context": "Students at IPN hoping the exam gets postponed after a holiday weekend.",
    },
    {
        "question": 'Translate: "I\'m looking for a restaurant that serves cochinita pibil." (unknown which restaurant)',
        "answer": ["busco un restaurante que sirva cochinita pibil", "busco un lugar que sirva cochinita pibil"],
        "hint": "Unknown restaurant → subjunctive 'sirva'",
        "explanation": "Unknown antecedent → subjunctive 'sirva'. 'Cochinita pibil' is an iconic dish from the Yucatán Peninsula, now popular throughout Mexico.",
        "context": "You're visiting Mérida and craving authentic cochinita pibil.",
    },
    {
        "question": 'Translate: "She studies hard so that she can get a scholarship."',
        "answer": ["ella estudia mucho para que pueda obtener una beca", "estudia mucho para que pueda conseguir una beca"],
        "hint": "para que → always subjunctive",
        "explanation": "'Para que' + subjunctive 'pueda' expresses purpose. 'Beca' = scholarship, highly valued in Mexican universities like UNAM and Tec.",
        "context": "A student at UNAM studying hard to maintain her scholarship.",
    },
    {
        "question": 'Translate: "I want a room that has air conditioning." (unknown which room)',
        "answer": ["quiero un cuarto que tenga aire acondicionado", "quiero una habitación que tenga aire acondicionado"],
        "hint": "Unknown room → subjunctive 'tenga'",
        "explanation": "Unknown antecedent → subjunctive 'tenga'. 'Aire acondicionado' is essential in hot Mexican cities. 'Cuarto' or 'habitación' for room.",
        "context": "Booking a hotel in Mérida during the scorching summer.",
    },
]


pairs = [
    (
        "I'm looking for a person who knows how to cook. (unknown person)",
        ["Busco una persona que sabe cocinar", "Busco una persona que sepa cocinar", "Busco una persona que cocina", "Busco a una persona que sabe cocinar"],
        2,
        "Unknown antecedent → subjunctive: 'sepa'. If the person were known/found: 'sabe' (indicative).",
    ),
    (
        "Although it IS raining, we're going. (factual)",
        ["Aunque llueva, vamos", "Aunque llueve, vamos", "Aunque llovía, vayamos", "Aunque llover, vamos"],
        2,
        "'Aunque' + indicative = factual 'although'. 'Aunque llueve' = it IS raining. Subjunctive 'aunque llueva' = even IF it rains.",
    ),
    (
        "Even if it rains, we're going. (hypothetical)",
        ["Aunque llueve, vamos", "Aunque llueva, vamos", "Aunque lloviera, vamos", "Aunque va a llover, vamos"],
        2,
        "'Aunque' + subjunctive = hypothetical 'even if'. 'Llueva' because the rain is uncertain/conditional.",
    ),
    (
        "As soon as you arrive, call me. (future arrival)",
        ["En cuanto llegas, llámame", "En cuanto llegues, llámame", "En cuanto llegabas, llámame", "En cuanto llegar, llámame"],
        2,
        "Time clauses with future/unknown events take subjunctive: 'en cuanto llegues'. If habitual present: 'en cuanto llegas' (indicative).",
    ),
    (
        "Before you leave, turn off the lights.",
        ["Antes de que sales, apaga las luces", "Antes de que saldrás, apaga las luces", "Antes de que salgas, apaga las luces", "Antes que salgas, apaga las luces"],
        3,
        "'Antes de que' ALWAYS requires subjunctive: 'salgas'. The event hasn't happened yet.",
    ),
    (
        "She left without anyone saying goodbye to her.",
        ["Se fue sin que nadie se despidió de ella", "Se fue sin que nadie se despidiera de ella", "Se fue sin nadie se despidió", "Se fue sin que nadie se despide"],
        2,
        "'Sin que' ALWAYS requires subjunctive: 'se despidiera' (imperfect subjunctive for past context). Note: 'se fue sin despedirse' is a simpler reflexive alternative.",
    ),
    (
        "Provided that you study, you'll pass.",
        ["Con tal de que estudias, aprobarás", "Con tal de que estudies, aprobarás", "Con tal que estudias, aprobarás", "Con tal de estudias, aprobarás"],
        2,
        "'Con tal de que' always takes subjunctive: 'estudies'. These conditional conjunctions always trigger subjunctive.",
    ),
    (
        "Which sentence correctly uses the subjunctive in an adjective clause?",
        ["Tengo un amigo que hable tres idiomas", "Conozco a alguien que hable tres idiomas", "Busco al amigo que habla tres idiomas", "El hombre que hable tres idiomas es Juan"],
        2,
        "'Conozco a alguien que hable...' — 'alguien' is indefinite/unknown → subjunctive. Known antecedents ('tengo un amigo que...', 'el hombre que...') take indicative.",
    ),
    (
        "I need a hotel that has a pool. (Cancún vacation)",
        ["Necesito un hotel que tiene alberca", "Necesito un hotel que tenga alberca", "Necesito un hotel que tenga piscina", "Necesito el hotel que tiene alberca"],
        2,
        "Unknown hotel → subjunctive 'tenga'. Also note: in Mexican Spanish, 'alberca' is the standard word for pool, not 'piscina'.",
    ),
    (
        "You can go to the party on the condition that you come home by midnight.",
        ["Puedes ir a la fiesta a condición de que llegas a casa antes de las doce", "Puedes ir a la fiesta a condición de que llegues a casa antes de las doce", "Puedes ir a la fiesta a condición de que llegar a casa antes de las doce", "Puedes ir a la fiesta a condición que llegues a casa antes de las doce"],
        2,
         "'A condición de que' always requires subjunctive: 'llegues'. The condition is future/hypothetical.",
    ),
    (
        "I'm looking for a place that has good WiFi. (unknown place)",
        ["Busco un lugar que tiene buen wifi", "Busco un lugar que tenga buen wifi", "Busco el lugar que tiene buen wifi", "Busco un lugar que tengas buen wifi"],
        2,
        "Unknown antecedent → subjunctive 'tenga'. 'Buen wifi' is common in Mexican Spanish for good WiFi connection.",
    ),
    (
        "Whoever comes to the party is welcome.",
        ["Quienquiera que viene a la fiesta es bienvenido", "Quienquiera que venga a la fiesta es bienvenido", "Quienquiera que vine a la fiesta es bienvenido", "Quienquiera que venía a la fiesta es bienvenido"],
        2,
        "'Quienquiera que' (whoever) is indefinite → subjunctive 'venga'. If it were a known group, indicative would be used.",
    ),
    (
        "Wherever you are, I'll find you.",
        ["Dondequiera que estás, te encontraré", "Dondequiera que estés, te encontraré", "Dondequiera que estar, te encontraré", "Dondequiera que estabas, te encontraré"],
        2,
        "'Dondequiera que' (wherever) is indefinite → subjunctive 'estés'. The location is unknown/hypothetical.",
    ),
    (
        "Whatever it may be, we'll solve it.",
        ["Cualquiera que es, lo resolveremos", "Cualquiera que sea, lo resolveremos", "Cualquiera que fue, lo resolveremos", "Cualquiera que siendo, lo resolveremos"],
        2,
        "'Cualquiera que sea' uses subjunctive 'sea' because the specific thing is unknown. This is a set phrase.",
    ),
    (
        "I turned off my phone so that nobody would call me.",
        ["Apagué mi celular para que nadie me llamó", "Apagué mi celular para que nadie me llame", "Apagué mi celular para que nadie me llamara", "Apagué mi celular para que nadie me llama"],
        3,
        "'Para que' always requires subjunctive. Past context → imperfect subjunctive 'llamara', not present subjunctive 'llame' or indicative 'llamó'.",
    ),
    (
        "They organized the event so that everyone could participate. (a fin de que)",
        ["Organizaron el evento a fin de que todos puedan participar", "Organizaron el evento a fin de que todos pudieran participar", "Organizaron el evento a fin de que todos pueden participar", "Organizaron el evento a fin de que todos participaban"],
        2,
        "'A fin de que' always requires subjunctive. Past main verb → imperfect subjunctive 'pudieran', not present subjunctive 'puedan'.",
    ),
    (
        "Which conjunction ALWAYS requires the subjunctive?",
        ["Aunque", "Después de que", "Antes de que", "Cuando"],
        3,
        "'Antes de que' ALWAYS requires subjunctive because the event hasn't happened yet. 'Aunque', 'después de que', and 'cuando' can use indicative for factual/habitual/completed actions.",
    ),
    (
        "Even if it's expensive, I'm buying it. (hypothetical)",
        ["Aunque está caro, lo compro", "Aunque es caro, lo compro", "Aunque esté caro, lo compro", "Aunque estaba caro, lo compro"],
        3,
        "'Aunque' + subjunctive 'esté' = hypothetical 'even if'. You don't know the price yet. Indicative 'está/es' = factual 'although it IS expensive'.",
    ),
    (
        "Despite the fact that it might rain, we're going to the tianguis.",
        ["A pesar de que llueve, vamos al tianguis", "A pesar de que llovía, vamos al tianguis", "A pesar de que llueva, vamos al tianguis", "A pesar de que llover, vamos al tianguis"],
        3,
        "'A pesar de que' + subjunctive 'llueva' = despite the possibility (hypothetical). 'Tianguis' is the Mexican word for open-air market.",
    ),
    (
        "No matter how much you practice, you won't beat me.",
        ["Por más que practicas, no me vas a ganar", "Por más que practiques, no me vas a ganar", "Por más que practicabas, no me vas a ganar", "Por más que practicar, no me vas a ganar"],
        2,
        "'Por más que' + subjunctive 'practiques' = no matter how much (hypothetical). Indicative 'practicas' = you actually are practicing (factual).",
    ),
    (
        "Although the team lost, the fans supported them. (factual past)",
        ["Aunque el equipo perdiera, la afición los apoyó", "Aunque el equipo perdió, la afición los apoyó", "Aunque el equipo pierda, la afición los apoyó", "Aunque el equipo pierde, la afición los apoyó"],
        2,
        "Known factual past event → indicative 'perdió'. 'Si bien el equipo perdió' is also valid. 'Afición' is the Mexican term for fans.",
    ),
    (
        "When you get to Puebla, call me. (future arrival)",
        ["Cuando llegas a Puebla, llámame", "Cuando llegabas a Puebla, llámame", "Cuando llegues a Puebla, llámame", "Cuando llegar a Puebla, llámame"],
        3,
        "'Cuando' + subjunctive 'llegues' for future/unknown arrival. 'Cuando llegas' would mean 'whenever you arrive' (habitual).",
    ),
    (
        "We'll order as soon as the waiter comes.",
        ["Pediremos tan pronto como viene el mesero", "Pediremos tan pronto como vino el mesero", "Pediremos tan pronto como venga el mesero", "Pediremos tan pronto como venir el mesero"],
        3,
        "'Tan pronto como' + subjunctive 'venga' for future events. 'Mesero' is the Mexican Spanish word for waiter (not 'camarero').",
    ),
    (
        "I won't leave until you come back.",
        ["No me voy hasta que vuelves", "No me voy hasta que regreses", "No me voy hasta que regresas", "No me voy hasta que regresabas"],
        2,
        "'Hasta que' + subjunctive 'regreses' because the return is future/uncertain. In Mexican Spanish, 'regresar' is preferred over 'volver'.",
    ),
    (
        "After you graduate, you can look for a job.",
        ["Después de que te gradúas, puedes buscar trabajo", "Después de que te graduabas, puedes buscar trabajo", "Después de que te gradúes, puedes buscar trabajo", "Después de que graduarte, puedes buscar trabajo"],
        3,
        "'Después de que' + subjunctive 'gradúes' for future graduation. 'Chamba' is colloquial Mexican for job, 'trabajo' is standard.",
    ),
    (
        "She left the meeting without anyone noticing.",
        ["Se fue de la junta sin que nadie se dio cuenta", "Se fue de la junta sin que nadie se diera cuenta", "Se fue de la junta sin que nadie se da cuenta", "Se fue de la junta sin nadie se dio cuenta"],
        2,
        "'Sin que' ALWAYS requires subjunctive. Past context → imperfect subjunctive 'se diera cuenta'. 'Junta' is Mexican for business meeting.",
    ),
    (
        "You can use my computer provided that you don't download anything.",
        ["Puedes usar mi computadora con tal de que no descargas nada", "Puedes usar mi computadora con tal de que no descargues nada", "Puedes usar mi computadora con tal de que no descargar nada", "Puedes usar mi computadora con tal de que no descargabas nada"],
        2,
        "'Con tal de que' always takes subjunctive: 'descargues'. Mexican: 'computadora' (not 'ordenador').",
    ),
    (
        "Whenever you want, we can practice Spanish. (conditional)",
        ["Siempre que quieres, podemos practicar español", "Siempre que quieras, podemos practicar español", "Siempre que querías, podemos practicar español", "Siempre que querer, podemos practicar español"],
        2,
        "'Siempre que' + subjunctive 'quieras' = 'provided that/whenever' (conditional). Indicative 'quieres' = 'whenever you want' (habitual fact).",
    ),
    (
        "You can stay here as long as you follow the rules.",
        ["Puedes quedarte aquí siempre y cuando sigues las reglas", "Puedes quedarte aquí siempre y cuando sigas las reglas", "Puedes quedarte aquí siempre y cuando seguías las reglas", "Puedes quedarte aquí siempre y cuando seguir las reglas"],
        2,
        "'Siempre y cuando' always requires subjunctive: 'sigas' or 'cumplas'. It expresses a condition, not a habitual fact.",
    ),
    (
        "I won't go unless they invite me.",
        ["No iré a menos que me invitan", "No iré a menos que me invitan", "No iré a menos que me inviten", "No iré a menos que me invitaban"],
        3,
        "'A menos que' (unless) always triggers subjunctive: 'inviten'. The invitation is hypothetical/uncertain.",
    ),
    (
        "As long as you study, you'll pass. (conditional)",
        ["Mientras estudias, aprobarás", "Mientras estudies, aprobarás", "Mientras estudiabas, aprobarás", "Mientras estudiar, aprobarás"],
        2,
        "'Mientras' + subjunctive 'estudies' = 'as long as' (conditional). Indicative 'estudias' = 'while' (simultaneous factual action).",
    ),
    (
        "While you're studying, I'll make dinner. (simultaneous action)",
        ["Mientras estudies, hago la cena", "Mientras estudias, hago la cena", "Mientras estudiaras, hago la cena", "Mientras estudiando, hago la cena"],
        2,
        "'Mientras' + indicative 'estudias' = 'while' (simultaneous, factual). Contrast with 'mientras estudies' = 'as long as' (conditional).",
    ),
    (
        "This is the best taquería that exists in the neighborhood.",
        ["Esta es la mejor taquería que existe en la colonia", "Esta es la mejor taquería que exista en la colonia", "Esta es la mejor taquería que existen en la colonia", "Esta es la mejor taquería que existiendo en la colonia"],
        2,
        "After superlatives, subjunctive 'que exista/haya' is common to emphasize uniqueness, though indicative 'que existe' is also acceptable. 'Colonia' = Mexican for neighborhood.",
    ),
    (
        "That's the best movie I've ever seen.",
        ["Esa es la mejor película que he visto jamás", "Esa es la mejor película que haya visto jamás", "Esa es la mejor película que he visto jamás", "Both 'que haya visto' and 'que he visto' are correct after superlatives"],
        4,
        "After superlatives, BOTH subjunctive 'que haya visto' and indicative 'que he visto' are correct. Subjunctive emphasizes the uniqueness claim more strongly.",
    ),
    (
        "Maybe it'll rain this afternoon. (future possibility)",
        ["Quizás llueve esta tarde", "Quizás llueva esta tarde", "Quizás llovió esta tarde", "Quizás llover esta tarde"],
        2,
        "'Quizás/tal vez' + subjunctive for future possibility: 'llueva'. For present/past, indicative is also used.",
    ),
    (
        "Perhaps they'll arrive early. (future possibility)",
        ["Tal vez llegan temprano", "Tal vez lleguen temprano", "Tal vez llegaban temprano", "Tal vez llegando temprano"],
        2,
        "'Tal vez' + subjunctive 'lleguen' for future possibility. Indicative 'llegan' would be used for present probability or known information.",
    ),
    (
        "I need a mechanic who can fix my car. (unknown mechanic)",
        ["Necesito un mecánico que puede arreglar mi coche", "Necesito un mecánico que pueda arreglar mi coche", "Necesito el mecánico que puede arreglar mi coche", "Necesito un mecánico que pudiera arreglar mi coche"],
        2,
        "Unknown mechanic → subjunctive 'pueda'. If you knew which mechanic: 'el mecánico que puede' (indicative). Mexican: 'coche' or 'carro'.",
    ),
    (
        "Whatever happens, we'll stay calm.",
        ["Pasa lo que pasa, nos mantendremos tranquilos", "Pase lo que pase, nos mantendremos tranquilos", "Pase lo que pasa, nos mantendremos tranquilos", "Pasando lo que pase, nos mantendremos tranquilos"],
        2,
        "'Pase lo que pase' is a set phrase using subjunctive in both clauses. It literally means 'whatever may happen, whatever may happen.'",
    ),
    (
        "Unless it rains, we'll have the barbecue.",
        ["A menos que llueve, haremos la carne asada", "A menos que llueva, haremos la carne asada", "A menos que llovía, haremos la carne asada", "A menos que llover, haremos la carne asada"],
        2,
        "'A menos que' (unless) always triggers subjunctive: 'llueva'. 'Carne asada' is a beloved Mexican tradition, especially in the north.",
    ),
    (
        "We brought jackets in case it gets cold.",
        ["Trajimos chamarras en caso de que hace frío", "Trajimos chamarras en caso de que haga frío", "Trajimos chamarras en caso de que hacía frío", "Trajimos chamarras en caso de que hacer frío"],
        2,
        "'En caso de que' always triggers subjunctive: 'haga'. 'Chamarra' is Mexican Spanish for jacket/coat. Alternative: 'por si hace frío' (indicative).",
    ),
]


if __name__ == "__main__":
    run_exercises(exercises, title="Lección 7: Subjunctive in Adjective & Adverbial Clauses")
    choose_translation(pairs, title="Lección 7: Choose the Best Translation")