import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

from workbook_engine import run_exercises, choose_translation


exercises = [
    {
        "question": 'Translate: "I have eaten tamales."',
        "answer": ["he comido tamales", "yo he comido tamales"],
        "hint": "Present perfect: he + past participle",
        "explanation": "Present perfect: 'he comido' (he + comido). However, in Mexican Spanish, the preterite 'comí tamales' is often preferred in casual speech for completed past actions.",
        "context": "You're telling a friend what you had for breakfast.",
    },
    {
        "question": 'Translate: "She has written the report."',
        "answer": ["ella ha escrito el reporte", "ha escrito el reporte", "ella ha escrito el informe"],
        "hint": "ha + escrito (irregular participle: escribir → escrito)",
        "explanation": "'Escribir' has the irregular past participle 'escrito'. 'Ha escrito' is present perfect. Note: Mexican Spanish often prefers 'escribió' (preterite) in casual speech.",
        "context": "Your colleague at work in Santa Fe finished the report.",
    },
    {
        "question": 'Translate: "We have seen that movie."',
        "answer": ["hemos visto esa película", "nosotros hemos visto esa película"],
        "hint": "hemos + visto (irregular participle: ver → visto)",
        "explanation": "'Ver' → irregular participle 'visto'. 'Hemos visto' = present perfect. In Mexican Spanish, 'ya vimos esa película' (preterite with 'ya') is more common.",
        "context": "Discussing whether to go to the cine in Guadalajara.",
    },
    {
        "question": 'Translate: "They had already left when we arrived."',
        "answer": ["ya se habían ido cuando llegamos", "se habían ido cuando llegamos", "ya habían salido cuando llegamos"],
        "hint": "Past perfect: habían + past participle; 'ya' = already",
        "explanation": "Past perfect (pluperfect): 'habían ido' (habían + ido). 'Ya' precedes the auxiliary. This tense is used consistently across Spanish dialects for 'had done' before another past action.",
        "context": "You arrived at a friend's house in Coyoacán but they'd already left.",
    },
    {
        "question": 'Translate: "I had said that before."',
        "answer": ["yo había dicho eso antes", "había dicho eso antes", "había dicho eso anteriormente"],
        "hint": "había + dicho (irregular participle: decir → dicho)",
        "explanation": "'Decir' → irregular participle 'dicho'. 'Había dicho' = past perfect. In Mexican Spanish this tense is used exactly as in other dialects.",
        "context": "You're pointing out that you'd warned someone about something at the office.",
    },
    {
        "question": 'Translate: "By next year, I will have finished my degree."',
        "answer": ["para el año que viene, habré terminado mi carrera", "para el próximo año, habré terminado mi carrera", "para el año que viene, habré acabado mi carrera"],
        "hint": "Future perfect: habré + past participle",
        "explanation": "Future perfect: 'habré terminado' (habré + terminado). Used for actions completed before a future point. 'Carrera' is the Mexican term for university degree.",
        "context": "You're planning your graduation from UNAM.",
    },
    {
        "question": 'Translate: "We will have left by the time you call."',
        "answer": ["habremos salido para cuando llames", "habremos salido cuando llames", "ya habremos salido cuando llames"],
        "hint": "Future perfect: habremos + past participle",
        "explanation": "Future perfect: 'habremos salido'. This form is rare in everyday Mexican speech but appears in formal contexts. Most Mexicans would say 'ya vamos a haber salido' or simply 'ya salimos'.",
        "context": "You're explaining that you'll be gone before your friend can reach you.",
    },
    {
        "question": 'Translate: "She would have gone to the party."',
        "answer": ["ella habría ido a la fiesta", "habría ido a la fiesta"],
        "hint": "Conditional perfect: habría + past participle",
        "explanation": "Conditional perfect: 'habría ido' (habría + ido). Used for hypothetical past actions. Also for probability/conjecture about the past: 'Habría sido las tres' = 'It must have been three o'clock.'",
        "context": "Your friend didn't go to the pachanga but would have if she'd known about it.",
    },
    {
        "question": 'Translate: "You would have been able to come." (formal usted)',
        "answer": ["usted habría podido venir", "habría podido venir"],
        "hint": "habría + podido (poder → podido, regular participle)",
        "explanation": "'Poder' has a regular past participle 'podido'. Conditional perfect: 'habría podido'. In Mexican Spanish, 'habría podido venir' sounds formal; casually: 'podrías haber venido' (tú).",
        "context": "Politely telling a colleague they could have attended the meeting in Paseo de la Reforma.",
    },
    {
        "question": 'Translate: "The door is open." (using haber + abierto)',
        "answer": "la puerta ha sido abierta",
        "hint": "abierto: irregular participle of abrir",
        "explanation": "'Abrir' → irregular participle 'abierto'. 'Ha sido abierta' (passive with ser). More commonly in Mexican Spanish you'd just say 'la puerta está abierta', but the perfect forms exist: 'he abierto la puerta' = I have opened the door.",
        "context": "A formal announcement about a museum in CDMX.",
    },
    {
        "question": 'Translate: "They have broken the window."',
        "answer": ["han roto la ventana", "ellos han roto la ventana"],
        "hint": "roto: irregular participle of romper",
        "explanation": "'Romper' → irregular participle 'roto'. 'Han roto' = present perfect. In Mexican Spanish, 'rompieron la ventana' (preterite) is far more common for completed actions.",
        "context": "Kids playing fútbol in the street broke a neighbor's window.",
    },
    {
        "question": 'Translate: "She has put the tamales on the table."',
        "answer": ["ella ha puesto los tamales en la mesa", "ha puesto los tamales en la mesa"],
        "hint": "puesto: irregular participle of poner",
        "explanation": "'Poner' → irregular participle 'puesto'. 'Ha puesto' = present perfect. In Mexican Spanish, 'ya puso los tamales en la mesa' (preterite) is more natural in casual speech.",
        "context": "Your abuela set the food on the table for the family meal.",
    },
    {
        "question": 'Translate: "I have returned home early."',
        "answer": ["he vuelto a casa temprano", "he vuelto a casa pronto", "yo he vuelto a casa temprano"],
        "hint": "vuelto: irregular participle of volver",
        "explanation": "'Volver' → irregular participle 'vuelto'. 'He vuelto' = present perfect. In Mexican Spanish, 'regresé a casa temprano' is more common. 'Volver' is less used in Mexico than 'regresar'.",
        "context": "You came home earlier than usual from work in Monterrey.",
    },
    {
        "question": 'Translate: "They have done a great job."',
        "answer": ["han hecho un gran trabajo", "han hecho un buen trabajo", "ellos han hecho un gran trabajo"],
        "hint": "hecho: irregular participle of hacer",
        "explanation": "'Hacer' → irregular participle 'hecho'. 'Han hecho' = present perfect. Very common form. In Mexican Spanish also: 'hicieron un buen trabajo' (preterite).",
        "context": "Praising your team at work for completing a project.",
    },
    {
        "question": 'Translate: "I have resolved the problem."',
        "answer": ["he resuelto el problema", "yo he resuelto el problema"],
        "hint": "resuelto: irregular participle of resolver",
        "explanation": "'Resolver' → irregular participle 'resuelto'. 'He resuelto' = present perfect. In Mexican Spanish, 'resolví el problema' (preterite) is more common in everyday speech.",
        "context": "You fixed a technical issue at the office in Polanco.",
    },
    {
        "question": 'Translate: "I already finished." (Mexican preference — use preterite with ya)',
        "answer": ["ya terminé", "ya acabé"],
        "hint": "Mexican Spanish prefers preterite: ya + preterite",
        "explanation": "In Mexican Spanish, 'ya terminé' (preterite) is strongly preferred over 'ya he terminado' (present perfect) for completed actions. This is a key dialect difference — Peninsular Spanish prefers 'ya he terminado'.",
        "context": "You finished your meal at a taquería and want to pay.",
    },
    {
        "question": 'Translate: "I have already told you." (Mexican preference — use preterite with ya)',
        "answer": ["ya te lo dije", "ya se lo dije"],
        "hint": "Mexican: ya + preterite, NOT ya + present perfect",
        "explanation": "In Mexican Spanish, 'ya te lo dije' (preterite) is far more natural than 'ya te lo he dicho' (present perfect). Mexicans use the preterite for completed past actions, unlike Peninsular Spanish which favors the present perfect.",
        "context": "You're reminding a friend in Mexico City about something you already explained.",
    },
    {
        "question": 'Translate: "I have said what I needed to say."',
        "answer": ["he dicho lo que necesitaba decir", "yo he dicho lo que necesitaba decir"],
        "hint": "he + dicho (irregular participle: decir → dicho)",
        "explanation": "'Decir' → irregular participle 'dicho'. 'He dicho' = present perfect. In Mexican Spanish, 'dije lo que necesitaba decir' (preterite) is more natural for completed actions.",
        "context": "You've made your point clear at a team meeting at work in CDMX.",
    },
    {
        "question": 'Translate: "What have you done?" (informal tú)',
        "answer": ["¿qué has hecho?", "¿qué has hecho tú?"],
        "hint": "has + hecho (irregular participle: hacer → hecho)",
        "explanation": "'Hacer' → irregular participle 'hecho'. 'Has hecho' = present perfect (tú). Very common question form. In Mexican Spanish, '¿qué hiciste?' is preferred in casual speech.",
        "context": "Your friend came back from a trip to Guadalajara and you're asking about it.",
    },
    {
        "question": 'Translate: "They have seen the new museum."',
        "answer": ["han visto el museo nuevo", "ellos han visto el museo nuevo"],
        "hint": "han + visto (irregular participle: ver → visto)",
        "explanation": "'Ver' → irregular participle 'visto'. 'Han visto' = present perfect. Mexican preference: 'ya vieron el museo nuevo' (preterite with ya).",
        "context": "Friends visited the new Museo Soumaya in CDMX.",
    },
    {
        "question": 'Translate: "We have put the groceries in the fridge."',
        "answer": ["hemos puesto las compras en el refrigerador", "hemos puesto las compras en la nevera", "hemos puesto los mandados en el refri"],
        "hint": "hemos + puesto (irregular participle: poner → puesto)",
        "explanation": "'Poner' → irregular participle 'puesto'. Mexican: 'refrigerador' or 'refri' (not 'nevera', which is Peninsular). 'Compras' or 'mandados' for groceries.",
        "context": "You just got back from Soriana and put everything away.",
    },
    {
        "question": 'Translate: "They have opened a new branch in Monterrey."',
        "answer": ["han abierto una nueva sucursal en Monterrey", "ellos han abierto una nueva sucursal en Monterrey"],
        "hint": "han + abierto (irregular participle: abrir → abierto)",
        "explanation": "'Abrir' → irregular participle 'abierto'. 'Han abierto' = present perfect. 'Sucursal' is the Mexican term for a business branch. 'Abrieron una nueva sucursal' (preterite) is more common in Mexican speech.",
        "context": "A bank opened a new location in Monterrey's financial district.",
    },
    {
        "question": 'Translate: "She had returned to her hometown."',
        "answer": ["ella había vuelto a su pueblo", "había vuelto a su pueblo", "ella había regresado a su pueblo"],
        "hint": "había + vuelto (irregular participle: volver → vuelto)",
        "explanation": "'Volver' → irregular participle 'vuelto'. 'Había vuelto' = past perfect. Note: 'había regresado' uses the regular participle of 'regresar'. In Mexican Spanish, 'regresar' is more common than 'volver'.",
        "context": "Your friend moved back to her pueblo in Oaxaca after years in CDMX.",
    },
    {
        "question": 'Translate: "We had written the report before the meeting."',
        "answer": ["habíamos escrito el reporte antes de la junta", "habíamos escrito el informe antes de la junta"],
        "hint": "habíamos + escrito (irregular participle: escribir → escrito)",
        "explanation": "'Escribir' → irregular participle 'escrito'. 'Habíamos escrito' = past perfect (pluperfect). 'Junta' is Mexican for business meeting. 'Reporte' or 'informe' for report.",
        "context": "Your team finished the report before the morning meeting in Santa Fe.",
    },
    {
        "question": 'Translate: "They had resolved the issue before the client called."',
        "answer": ["habían resuelto el problema antes de que llamara el cliente", "habían resuelto el problema antes de que el cliente llamara"],
        "hint": "habían + resuelto (irregular participle: resolver → resuelto)",
        "explanation": "'Resolver' → irregular participle 'resuelto'. 'Habían resuelto' = past perfect. In Mexican office Spanish, this tense is used for actions completed before another past action.",
        "context": "The IT team fixed the server issue before the client even noticed.",
    },
    {
        "question": 'Translate: "I will have finished the project by Friday."',
        "answer": ["habré terminado el proyecto para el viernes", "habré acabado el proyecto para el viernes"],
        "hint": "Future perfect: habré + past participle",
        "explanation": "Future perfect: 'habré terminado'. Used for actions completed before a future point. 'Para el viernes' (by Friday). This tense is formal; many Mexicans would say 'voy a terminar el proyecto antes del viernes'.",
        "context": "Committing to a deadline at your tech job in Guadalajara.",
    },
    {
        "question": 'Translate: "We will have seen everything by the end of the trip."',
        "answer": ["habremos visto todo para el final del viaje", "habremos visto todo al final del viaje"],
        "hint": "Future perfect: habremos + visto",
        "explanation": "Future perfect: 'habremos visto'. 'Ver' → irregular participle 'visto'. This tense is rare in everyday Mexican speech but appears in formal contexts.",
        "context": "Planning a trip through the Yucatán Peninsula and scheduling activities.",
    },
    {
        "question": 'Translate: "By the time you arrive, I will have left."',
        "answer": ["para cuando llegues, habré salido", "para cuando llegues, yo ya habré salido"],
        "hint": "Future perfect: habré + salido",
        "explanation": "Future perfect: 'habré salido' — I will have left before you arrive. Common in scheduling contexts. Mexicans might more casually say 'para cuando llegues, ya salí' (present with future meaning).",
        "context": "Telling your friend you'll be gone before they get to the meeting point.",
    },
    {
        "question": 'Translate: "She would have told the truth."',
        "answer": ["ella habría dicho la verdad", "habría dicho la verdad"],
        "hint": "Conditional perfect: habría + dicho (decir → dicho)",
        "explanation": "Conditional perfect: 'habría dicho'. 'Decir' → irregular participle 'dicho'. Used for hypothetical past actions. In Mexican Spanish, 'hubiera dicho' (past perfect subjunctive) is also used colloquially for this meaning.",
        "context": "Discussing what someone should have done in a difficult situation.",
    },
    {
        "question": 'Translate: "They would have done it differently."',
        "answer": ["habrían hecho las cosas diferente", "habrían hecho las cosas de manera diferente", "ellos habrían hecho las cosas diferente"],
        "hint": "Conditional perfect: habrían + hecho (hacer → hecho)",
        "explanation": "Conditional perfect: 'habrían hecho'. 'Hacer' → irregular participle 'hecho'. Very common form for hypothetical past scenarios.",
        "context": "Reflecting on how a different team would have handled the project in Monterrey.",
    },
    {
        "question": 'Translate: "She would have been able to come, but she was busy."',
        "answer": ["habría podido venir, pero estaba ocupada", "habría podido ir, pero estaba ocupada"],
        "hint": "Conditional perfect: habría + podido (poder → podido, regular)",
        "explanation": "'Poder' has a regular participle 'podido'. Conditional perfect: 'habría podido'. 'Venir' is preferred when the speaker is at the destination. In casual Mexican Spanish: 'pudo haber venido' is also common.",
        "context": "Explaining why a friend missed the party in Coyoacán.",
    },
    {
        "question": 'Translate: "The table is covered with a tablecloth."',
        "answer": ["la mesa está cubierta con un mantel", "la mesa está cubierta con manteles"],
        "hint": "cubierto: irregular participle of cubrir",
        "explanation": "'Cubrir' → irregular participle 'cubierto'. As an adjective: 'cubierta' (covered). 'Mantel' = tablecloth. This is an adjective use of the irregular participle.",
        "context": "Describing the table setup at a family dinner in Puebla.",
    },
    {
        "question": 'Translate: "The fried fish is delicious."',
        "answer": ["el pescado frito está delicioso", "el pescado frito está riquísimo"],
        "hint": "frito: irregular participle of freír (used as adjective)",
        "explanation": "'Freír' → irregular participle 'frito'. As an adjective: 'pescado frito' (fried fish). While 'freído' also exists, 'frito' is overwhelmingly more common and the standard form.",
        "context": "Enjoying pescado frito at a coastal restaurant in Veracruz.",
    },
    {
        "question": 'Translate: "The book is printed on recycled paper."',
        "answer": ["el libro está impreso en papel reciclado", "el libro está impreso sobre papel reciclado"],
        "hint": "impreso: irregular participle of imprimir (used as adjective)",
        "explanation": "'Imprimir' → two participles: 'impreso' (irregular, used as adjective) and 'imprimido' (regular, used in compound tenses). 'Impreso' is the standard form as adjective: 'libro impreso'.",
        "context": "Looking at an eco-friendly book published by a Mexican press.",
    },
    {
        "question": 'Translate: "I doubt that they have done the work." (present perfect subjunctive)',
        "answer": ["dudo que hayan hecho el trabajo", "dudo que hayan hecho la tarea"],
        "hint": "Present perfect subjunctive: hayan + hecho",
        "explanation": "Present perfect subjunctive: 'hayan hecho'. Triggered by expressions of doubt. 'Dudar que' + present perfect subjunctive = doubting a completed action. In Mexican Spanish, 'dudo que hayan hecho' or more casually 'dudo que hayan hecho' is standard.",
        "context": "You're skeptical that your coworkers at the office finished their part.",
    },
    {
        "question": 'Translate: "It\'s possible that she has seen the message." (present perfect subjunctive)',
        "answer": ["es posible que haya visto el mensaje", "puede que haya visto el mensaje"],
        "hint": "Present perfect subjunctive: haya + visto",
        "explanation": "Present perfect subjunctive: 'haya visto'. Triggered by 'es posible que' or 'puede que'. Expresses possibility about a completed past action.",
        "context": "You sent a WhatsApp message and are wondering if she read it.",
    },
    {
        "question": 'Translate: "I\'m glad you have told me the truth." (present perfect subjunctive)',
        "answer": ["me alegra que me hayas dicho la verdad", "me da gusto que me hayas dicho la verdad"],
        "hint": "Present perfect subjunctive: hayas + dicho",
        "explanation": "Present perfect subjunctive: 'hayas dicho'. Triggered by emotion expressions ('me alegra que', 'me da gusto que'). In Mexican Spanish, 'me da gusto' is very common for 'I'm glad'.",
        "context": "Your friend finally confessed something important and you appreciate the honesty.",
    },
    {
        "question": 'Translate: "If I had known, I would have gone." (past perfect subjunctive + conditional perfect)',
        "answer": ["si hubiera sabido, habría ido", "si hubiese sabido, habría ido"],
        "hint": "Past perfect subjunctive: hubiera/hubiese + past participle",
        "explanation": "Past perfect subjunctive: 'hubiera/hubiese sabido'. Both forms are valid. This is the standard 'si' clause pattern for hypothetical past situations. In Mexican Spanish, 'hubiera' is more common than 'hubiese'.",
        "context": "You missed a concert at the Palacio de Bellas Artes and are expressing regret.",
    },
    {
        "question": 'Translate: "If they had arrived earlier, they would have seen the sunset." (past perfect subjunctive)',
        "answer": ["si hubieran llegado más temprano, habrían visto el atardecer", "si hubiesen llegado más temprano, habrían visto el atardecer"],
        "hint": "Past perfect subjunctive: hubieran/hubiesen + past participle",
        "explanation": "Past perfect subjunctive: 'hubieran llegado'. Conditional perfect in main clause: 'habrían visto'. In Mexican Spanish, 'hubieran' is preferred over 'hubiesen'. 'Atardecer' = sunset.",
        "context": "Friends arrived late to a lookout point in Taxco and missed the beautiful sunset.",
    },
    {
        "question": 'Translate: "I already ate." (Mexican preference — use preterite with ya)',
        "answer": ["ya comí", "ya cené", "ya almorcé"],
        "hint": "Mexican: ya + preterite, NOT present perfect",
        "explanation": "In Mexican Spanish, 'ya comí' (preterite) is the natural way to say 'I already ate'. Peninsular Spanish would say 'ya he comido' (present perfect). Mexicans strongly prefer the preterite for completed past actions.",
        "context": "Your mom asks if you've had lunch and you respond that you already ate.",
    },
    {
        "question": 'Translate: "I have already seen that movie." (Mexican preference — preterite with ya)',
        "answer": ["ya vi esa película", "ya vi esa peli"],
        "hint": "Mexican: ya + preterite for completed actions",
        "explanation": "In Mexican Spanish, 'ya vi esa película' (preterite) is more natural than 'ya he visto esa película' (present perfect). 'Peli' is colloquial Mexican for 'película'. This is a key dialect difference from Peninsular Spanish.",
        "context": "Discussing movies with a friend who recommends one you've already seen.",
    },
    {
        "question": 'Translate: "They have already left." (Mexican preference — preterite with ya)',
        "answer": ["ya se fueron", "ya salieron"],
        "hint": "Mexican: ya + preterite, NOT present perfect",
        "explanation": "In Mexican Spanish, 'ya se fueron' (preterite) is far more natural than 'ya se han ido' (present perfect). This is one of the most noticeable differences between Mexican and Peninsular Spanish.",
        "context": "You arrive at a friend's house and they've already left for the party.",
    },
    {
        "question": 'Translate: "We have already paid the bill." (Mexican preference — preterite with ya)',
        "answer": ["ya pagamos la cuenta", "ya pagamos la cuenta", "ya pagamos lo nuestro"],
        "hint": "Mexican: ya + preterite for completed actions",
        "explanation": "In Mexican Spanish, 'ya pagamos la cuenta' (preterite) is more natural than 'ya hemos pagado la cuenta' (present perfect). 'Cuenta' = bill/check in Mexican restaurants.",
        "context": "At a restaurant in Polanco, confirming to friends that the bill is taken care of.",
    },
    {
        "question": 'Translate: "He had already died when the ambulance arrived."',
        "answer": ["ya había muerto cuando llegó la ambulancia", "había muerto cuando llegó la ambulancia"],
        "hint": "había + muerto (irregular participle: morir → muerto)",
        "explanation": "'Morir' → irregular participle 'muerto'. 'Había muerto' = past perfect. The past perfect is used consistently across dialects for an action completed before another past action.",
        "context": "Describing a tragic event where the person had already passed before help arrived.",
    },
    {
        "question": 'Translate: "She has broken her promise."',
        "answer": ["ha roto su promesa", "ella ha roto su promesa"],
        "hint": "ha + roto (irregular participle: romper → roto)",
        "explanation": "'Romper' → irregular participle 'roto'. 'Ha roto' = present perfect. In Mexican Spanish, 'rompió su promesa' (preterite) is more natural for a completed action.",
        "context": "A friend promised to help you move but didn't show up.",
    },
    {
        "question": 'Translate: "We have covered all the topics on the agenda."',
        "answer": ["hemos cubierto todos los temas de la agenda", "hemos cubierto todos los puntos del orden del día"],
        "hint": "hemos + cubierto (irregular participle: cubrir → cubierto)",
        "explanation": "'Cubrir' → irregular participle 'cubierto'. 'Hemos cubierto' = present perfect. In Mexican business Spanish, 'orden del día' is also used for 'agenda' (meeting agenda).",
        "context": "At the end of a meeting at the office in Santa Fe, confirming all topics were discussed.",
    },
    {
        "question": 'Translate: "The printer has printed the document." (using imprimir)',
        "answer": ["la impresora ha imprimido el documento", "la impresora ha impreso el documento", "la impresora imprimió el documento"],
        "hint": "imprimir has two participles: imprimido/imprimido (compound tenses) and impreso (adjective)",
        "explanation": "'Imprimir' has two past participles: 'imprimido/imprimido' (used in compound tenses like 'ha imprimido') and 'impreso' (used mainly as adjective: 'documento impreso'). In practice, 'la impresora imprimió el documento' (preterite) is most natural in Mexican Spanish.",
        "context": "At the office, confirming that the printer has produced the document.",
    },
    {
        "question": 'Translate: "They had fried the tacos."',
        "answer": ["habían freído los tacos", "habían frito los tacos", "ellos habían freído los tacos"],
        "hint": "freír has two participles: freído (compound tenses) and frito (adjective)",
        "explanation": "'Freír' has two past participles: 'freído' (used in compound tenses like 'han freído') and 'frito' (used mainly as adjective: 'tacos fritos'). Both 'habían freído' and 'habían frito' can appear in compound tenses, but 'frito' is more common as adjective.",
        "context": "Describing how the street vendor had already fried the tacos before you arrived.",
    },
    {
        "question": 'Translate: "I\'m surprised that she has resolved the problem so quickly." (present perfect subjunctive)',
        "answer": ["me sorprende que haya resuelto el problema tan rápido", "me sorprende que haya resuelto el problema tan deprisa"],
        "hint": "Present perfect subjunctive: haya + resuelto",
        "explanation": "Present perfect subjunctive: 'haya resuelto'. Triggered by 'me sorprende que'. 'Resolver' → irregular participle 'resuelto'. In Mexican Spanish, 'tan rápido' or 'tan deprisa' for 'so quickly'.",
        "context": "Impressed that a new hire at work solved a complex issue in record time.",
    },
    {
        "question": 'Translate: "I don\'t think they have seen the news." (present perfect subjunctive)',
        "answer": ["no creo que hayan visto las noticias", "no creo que hayan visto las noticias"],
        "hint": "Present perfect subjunctive: hayan + visto",
        "explanation": "Present perfect subjunctive: 'hayan visto'. Triggered by 'no creo que' (negative opinion → subjunctive). 'Ver' → irregular participle 'visto'.",
        "context": "Discussing with a friend whether your mutual friends watched the important news broadcast.",
    },
    {
        "question": 'Translate: "It\'s a pity that they have broken the window." (present perfect subjunctive)',
        "answer": ["es una lástima que hayan roto la ventana", "qué lástima que hayan roto la ventana"],
        "hint": "Present perfect subjunctive: hayan + roto",
        "explanation": "Present perfect subjunctive: 'hayan roto'. Triggered by 'es una lástima que' (emotion). 'Romper' → irregular participle 'roto'. 'Qué lástima' is very common in Mexican Spanish.",
        "context": "Kids were playing fútbol in the street and broke a neighbor's window.",
    },
    {
        "question": 'Translate: "If we had had time, we would have visited the museum." (past perfect subjunctive)',
        "answer": ["si hubiéramos tenido tiempo, habríamos visitado el museo", "si hubiésemos tenido tiempo, habríamos visitado el museo"],
        "hint": "Past perfect subjunctive: hubiéramos/hubiésemos + past participle",
        "explanation": "Past perfect subjunctive: 'hubiéramos/hubiésemos tenido'. Conditional perfect in main clause: 'habríamos visitado'. 'Hubiéramos' is more common in Mexican Spanish than 'hubiésemos'.",
        "context": "You were visiting CDMX and ran out of time before seeing the Museo Nacional de Antropología.",
    },
    {
        "question": 'Translate: "If she had put the keys on the table, they would still be there." (past perfect subjunctive)',
        "answer": ["si hubiera puesto las llaves en la mesa, todavía estarían ahí", "si hubiese puesto las llaves en la mesa, seguirían ahí"],
        "hint": "Past perfect subjunctive: hubiera/hubiese + puesto",
        "explanation": "Past perfect subjunctive: 'hubiera puesto'. 'Poner' → irregular participle 'puesto'. Conditional in main clause. 'Todavía estarían ahí' or 'seguirían ahí' for 'they would still be there'.",
        "context": "You can't find your keys and are reasoning about where they might be.",
    },
    {
        "question": 'Translate: "If you had told me, I would have helped you." (past perfect subjunctive)',
        "answer": ["si me hubieras dicho, te habría ayudado", "si me hubieses dicho, te habría ayudado", "si me hubieras dicho, te habría ayudado"],
        "hint": "Past perfect subjunctive: hubieras/hubieses + dicho",
        "explanation": "Past perfect subjunctive: 'hubieras dicho'. 'Decir' → irregular participle 'dicho'. Conditional perfect: 'habría ayudado'. Very common hypothetical past pattern.",
        "context": "Your friend didn't tell you about their problem and you wish they had.",
    },
    {
        "question": 'Translate: "If they had written the email, I would have replied." (past perfect subjunctive)',
        "answer": ["si hubieran escrito el correo, habría contestado", "si hubiesen escrito el correo, habría respondido"],
        "hint": "Past perfect subjunctive: hubieran/hubiesen + escrito",
        "explanation": "Past perfect subjunctive: 'hubieran escrito'. 'Escribir' → irregular participle 'escrito'. In Mexican Spanish, 'contestar' or 'responder' for 'to reply'. 'Correo' for email.",
        "context": "A work situation where colleagues didn't send an email and you couldn't respond.",
    },
    {
        "question": 'Translate: "I already finished my homework." (Mexican preference — preterite with ya)',
        "answer": ["ya terminé mi tarea", "ya acabé mi tarea"],
        "hint": "Mexican: ya + preterite for completed past actions",
        "explanation": "In Mexican Spanish, 'ya terminé mi tarea' (preterite) is strongly preferred over 'ya he terminado mi tarea' (present perfect). This is a defining feature of Mexican Spanish vs Peninsular Spanish.",
        "context": "A student at UNAM telling their parent they're done with homework.",
    },
    {
        "question": 'Translate: "We have returned the books to the library."',
        "answer": ["hemos devuelto los libros a la biblioteca", "nosotros hemos devuelto los libros a la biblioteca"],
        "hint": "hemos + devuelto (irregular participle: devolver → devuelto)",
        "explanation": "'Devolver' → irregular participle 'devuelto'. 'Hemos devuelto' = present perfect. In Mexican Spanish, 'ya devolvimos los libros' (preterite) is more natural. Note: 'volver' → 'vuelto', 'devolver' → 'devuelto'.",
        "context": "Returning books to the Biblioteca de México in CDMX.",
    },
    {
        "question": 'Translate: "By December, they will have opened the new highway."',
        "answer": ["para diciembre, habrán abierto la nueva autopista", "para diciembre, habrán abierto la nueva carretera"],
        "hint": "Future perfect: habrán + abierto",
        "explanation": "Future perfect: 'habrán abierto'. 'Abrir' → irregular participle 'abierto'. Used for actions completed before a future point. 'Autopista' is the Mexican term for highway.",
        "context": "Discussing infrastructure projects near CDMX that are scheduled to finish.",
    },
    {
        "question": 'Translate: "He would have returned earlier but there was traffic."',
        "answer": ["habría regresado más temprano pero había tráfico", "habría vuelto más temprano pero había tráfico"],
        "hint": "Conditional perfect: habría + regresado/vuelto",
        "explanation": "Conditional perfect: 'habría regresado' or 'habría vuelto'. In Mexican Spanish, 'regresado' (from 'regresar') is more common than 'vuelto' (from 'volver'). 'Había tráfico' for past traffic.",
        "context": "Explaining why you were late to dinner because of traffic on Periférico.",
    },
]


pairs = [
    (
        "Which is the more natural Mexican Spanish for 'I already finished'?",
        ["Ya he terminado", "Ya terminé", "Ya he acabado", "Ya acababa"],
        2,
        "Mexican Spanish strongly prefers the preterite with 'ya': 'ya terminé'. Peninsular Spanish would say 'ya he terminado'.",
    ),
    (
        "She had already left when we arrived.",
        ["Ya se había ido cuando llegamos", "Ya se ha ido cuando llegamos", "Ya se fue cuando llegamos", "Ya se iba cuando llegamos"],
        1,
        "Past perfect (pluperfect) is used consistently across dialects: 'se había ido'. The earlier of two past actions always uses past perfect.",
    ),
    (
        "I have written the email.",
        ["He escrito el correo", "He escribido el correo", "Yo he escribido el correo", "Hemos escrito el correo"],
        1,
        "'Escribir' → irregular participle 'escrito' (not 'escribido'). 'He escrito' is correct.",
    ),
    (
        "They have broken the window.",
        ["Han rompido la ventana", "Han roto la ventana", "Hicieron roto la ventana", "Han rota la ventana"],
        2,
        "'Romper' → irregular participle 'roto' (not 'rompido'). 'Han roto' is correct.",
    ),
    (
        "Which is the correct irregular past participle?",
        ["Hacer → hacido", "Hacer → hecho", "Decir → decido", "Poner → ponido"],
        2,
        "Irregular participles: hacer → hecho, decir → dicho, poner → puesto. None of these end in -ido.",
    ),
    (
        "She would have gone to the party.",
        ["Ella iría a la fiesta", "Ella habría ido a la fiesta", "Ella haya ido a la fiesta", "Ella fuera a la fiesta"],
        2,
        "Conditional perfect: 'habría ido' (habría + ido). Not 'iría' (conditional alone = would go, not would have gone).",
    ),
    (
        "By next year, I will have finished my degree.",
        ["Para el año que viene, terminaré mi carrera", "Para el año que viene, habré terminado mi carrera", "Para el año que viene, he terminado mi carrera", "Para el año que viene, habré acabando mi carrera"],
        2,
        "Future perfect: 'habré terminado' — action completed before a future point. 'Terminaré' (simple future) doesn't convey the completion-before-deadline meaning.",
    ),
    (
        "I have returned home early. (using volver)",
        ["He vuelto a casa temprano", "He volvido a casa temprano", "He vuelta a casa temprano", "Ha vuelto a casa temprano"],
        1,
        "'Volver' → irregular participle 'vuelto' (not 'volvido'). 'He vuelto' is correct.",
    ),
    (
        "Which sentence shows the MEXICAN preference for completed past actions?",
        ["Ya he desayunado", "Ya desayuné", "Ya había desayunado", "Ya desayuno"],
        2,
        "Mexican Spanish prefers the preterite for completed actions: 'ya desayuné'. 'Ya he desayunado' sounds Peninsular/overly formal in Mexico.",
    ),
    (
        "They have fried the fish. (using freír)",
        ["Han frito el pescado", "Han freído el pescado", "Han frio el pescado", "Han freír el pescado"],
        1,
         "'Freír' → irregular participle 'frito'. While 'freído' also exists, 'frito' is standard and much more common, especially in 'pescado frito'.",
    ),
    (
        "I have said what I needed to say.",
        ["He dicho lo que necesitaba decir", "He decido lo que necesitaba decir", "Ha dicho lo que necesitaba decir", "He diciendo lo que necesitaba decir"],
        1,
        "'Decir' → irregular participle 'dicho' (not 'decido'). 'He dicho' = present perfect. Mexican preference: 'dije lo que necesitaba decir' (preterite).",
    ),
    (
        "What have you done? (informal tú)",
        ["¿Qué has hecho?", "¿Qué has hacido?", "¿Qué hiciste hecho?", "¿Qué ha hecho tú?"],
        1,
        "'Hacer' → irregular participle 'hecho' (not 'hacido'). 'Has hecho' = present perfect (tú). Mexican preference: '¿qué hiciste?' (preterite).",
    ),
    (
        "They have opened a new branch in Monterrey.",
        ["Han abrido una nueva sucursal en Monterrey", "Han abierto una nueva sucursal en Monterrey", "Han abriendo una nueva sucursal en Monterrey", "Han aperto una nueva sucursal en Monterrey"],
        2,
        "'Abrir' → irregular participle 'abierto' (not 'abrido'). 'Han abierto' = present perfect. Mexican preference: 'abrieron una nueva sucursal' (preterite).",
    ),
    (
        "We have put the groceries in the fridge.",
        ["Hemos ponido las compras en el refrigerador", "Hemos puesto las compras en el refrigerador", "Hemos puestos las compras en el refrigerador", "Hemos ponidas las compras en el refrigerador"],
        2,
        "'Poner' → irregular participle 'puesto' (not 'ponido'). 'Hemos puesto' is correct. Mexican: 'refrigerador' or 'refri', not 'nevera'.",
    ),
    (
        "She had returned to her hometown.",
        ["Ella había volvido a su pueblo", "Ella había vuelto a su pueblo", "Ella había vuelta a su pueblo", "Ella ha vuelto a su pueblo"],
        2,
        "'Volver' → irregular participle 'vuelto' (not 'volvido'). 'Había vuelto' = past perfect. Mexican preference: 'regresó a su pueblo' (preterite of 'regresar').",
    ),
    (
        "We had written the report before the meeting.",
        ["Habíamos escrito el reporte antes de la junta", "Habíamos escribido el reporte antes de la junta", "Hemos escrito el reporte antes de la junta", "Habíamos escritos el reporte antes de la junta"],
        1,
        "'Escribir' → irregular participle 'escrito' (not 'escribido'). 'Habíamos escrito' = past perfect. 'Junta' = Mexican for business meeting.",
    ),
    (
        "They had resolved the issue before the client called.",
        ["Habían resolvado el problema antes de que llamara el cliente", "Habían resuelto el problema antes de que llamara el cliente", "Habían resueltos el problema antes de que llamara el cliente", "Han resuelto el problema antes de que llamara el cliente"],
        2,
        "'Resolver' → irregular participle 'resuelto' (not 'resolvado'). 'Habían resuelto' = past perfect.",
    ),
    (
        "I will have finished the project by Friday.",
        ["Habré terminado el proyecto para el viernes", "He terminado el proyecto para el viernes", "Habré terminando el proyecto para el viernes", "Terminaré el proyecto para el viernes"],
        1,
        "Future perfect: 'habré terminado'. 'Terminaré' is simple future (doesn't convey completion before a deadline). 'Para el viernes' = by Friday.",
    ),
    (
        "By the time you arrive, I will have left.",
        ["Para cuando llegues, he salido", "Para cuando llegues, habré salido", "Para cuando llegues, habré saliendo", "Para cuando llegues, saldré"],
        2,
        "Future perfect: 'habré salido' — action completed before a future point. 'He salido' (present perfect) doesn't convey future completion. 'Saldré' is simple future.",
    ),
    (
        "She would have told the truth.",
        ["Ella habría dicho la verdad", "Ella habría decido la verdad", "Ella habría diciendo la verdad", "Ella diría la verdad"],
        1,
        "Conditional perfect: 'habría dicho' (decir → dicho). 'Diría' is conditional (would tell, not would have told).",
    ),
    (
        "They would have done it differently.",
        ["Habrían hecho las cosas diferente", "Habrían hacido las cosas diferente", "Hicieran las cosas diferente", "Harían las cosas diferente"],
        1,
        "Conditional perfect: 'habrían hecho' (hacer → hecho). 'Harían' is conditional (would do, not would have done).",
    ),
    (
        "The table is covered with a tablecloth.",
        ["La mesa está cubierta con un mantel", "La mesa está cubrida con un mantel", "La mesa es cubierto con un mantel", "La mesa está cubriendo con un mantel"],
        1,
        "'Cubrir' → irregular participle 'cubierto' (not 'cubrido'). As adjective: 'cubierta' (feminine). Used as adjective here, not in a compound tense.",
    ),
    (
        "Which irregular past participle is correct?",
        ["Abrir → abrido", "Cubrir → cubrido", "Morir → muerto", "Resolver → resolvado"],
        3,
        "Irregular participles: abrir → abierto (not abrido), cubrir → cubierto (not cubrido), morir → muerto ✓, resolver → resuelto (not resolvado).",
    ),
    (
        "I doubt that they have done the work. (present perfect subjunctive)",
        ["Dudo que han hecho el trabajo", "Dudo que hayan hecho el trabajo", "Dudo que hicieron el trabajo", "Dudo que habrán hecho el trabajo"],
        2,
        "Present perfect subjunctive: 'hayan hecho'. Triggered by 'dudar que' → subjunctive. 'Han hecho' is indicative, which doesn't follow the subjunctive trigger.",
    ),
    (
        "It's possible that she has seen the message.",
        ["Es posible que ha visto el mensaje", "Es posible que haya visto el mensaje", "Es posible que vio el mensaje", "Es posible que vea el mensaje"],
        2,
        "Present perfect subjunctive: 'haya visto'. 'Es posible que' triggers subjunctive. 'Vea' (present subjunctive) = 'might see' (not yet), not 'has seen' (completed action).",
    ),
    (
        "I'm glad you have told me the truth. (present perfect subjunctive)",
        ["Me alegra que me has dicho la verdad", "Me alegra que me hayas dicho la verdad", "Me alegra que me dijiste la verdad", "Me alegra que me dirás la verdad"],
        2,
        "Present perfect subjunctive: 'hayas dicho'. Triggered by 'me alegra que' (emotion). 'Has dicho' is indicative, which doesn't follow the subjunctive trigger.",
    ),
    (
        "If I had known, I would have gone. (past perfect subjunctive)",
        ["Si sabía, habría ido", "Si hubiera sabido, habría ido", "Si habría sabido, iría", "Si supe, habría ido"],
        2,
        "Past perfect subjunctive: 'hubiera sabido' + conditional perfect 'habría ido'. This is the standard 'si' clause pattern for hypothetical past situations.",
    ),
    (
        "If they had arrived earlier, they would have seen the sunset.",
        ["Si llegaban más temprano, habrían visto el atardecer", "Si hubieran llegado más temprano, habrían visto el atardecer", "Si habrían llegado más temprano, vieran el atardecer", "Si llegaron más temprano, habrían visto el atardecer"],
        2,
        "Past perfect subjunctive: 'hubieran llegado' + conditional perfect 'habrían visto'. 'Llegaban' (imperfect) and 'llegaron' (preterite) don't form the hypothetical 'si' clause.",
    ),
    (
        "Which is the more natural MEXICAN Spanish for 'I already ate'?",
        ["Ya he comido", "Ya comí", "Ya había comido", "Ya como"],
        2,
        "Mexican Spanish strongly prefers preterite with 'ya': 'ya comí'. 'Ya he comido' sounds Peninsular Spanish.",
    ),
    (
        "Which is the more natural MEXICAN Spanish for 'They have already left'?",
        ["Ya se han ido", "Ya se fueron", "Ya se iban", "Ya se van"],
        2,
        "Mexican Spanish: 'ya se fueron' (preterite). 'Ya se han ido' (present perfect) sounds Peninsular. This is one of the most noticeable dialect differences.",
    ),
    (
        "I already finished my homework. (Mexican preference)",
        ["Ya he terminado mi tarea", "Ya terminé mi tarea", "Ya había terminado mi tarea", "Ya terminaré mi tarea"],
        2,
        "Mexican preference: 'ya terminé mi tarea' (preterite). 'Ya he terminado' is Peninsular Spanish style.",
    ),
    (
        "The fried fish is delicious.",
        ["El pescado freído está delicioso", "El pescado frito está delicioso", "El pescado frio está delicioso", "El pescado freír está delicioso"],
        2,
        "'Freír' → irregular participle 'frito'. While 'freído' exists, 'frito' is the standard form, especially as adjective: 'pescado frito'.",
    ),
    (
        "The book is printed on recycled paper.",
        ["El libro está imprimido en papel reciclado", "El libro está impreso en papel reciclado", "El libro está imprimiendo en papel reciclado", "El libro es impreso en papel reciclado"],
        2,
        "'Imprimir' has two participles: 'imprimido/imprimido' (compound tenses) and 'impreso' (adjective). As adjective: 'libro impreso' or 'está impreso'.",
    ),
    (
        "I'm surprised that she has resolved the problem so quickly.",
        ["Me sorprende que ha resuelto el problema tan rápido", "Me sorprende que haya resuelto el problema tan rápido", "Me sorprende que resolvió el problema tan rápido", "Me sorprende que resuelve el problema tan rápido"],
        2,
        "Present perfect subjunctive: 'haya resuelto'. 'Me sorprende que' triggers subjunctive. 'Resolver' → irregular participle 'resuelto'.",
    ),
    (
        "I don't think they have seen the news.",
        ["No creo que han visto las noticias", "No creo que hayan visto las noticias", "No creo que vieron las noticias", "No creo que veían las noticias"],
        2,
        "Present perfect subjunctive: 'hayan visto'. 'No creo que' triggers subjunctive. 'Han visto' is indicative, which doesn't follow the negative opinion trigger.",
    ),
    (
        "It's a pity that they have broken the window.",
        ["Es una lástima que han roto la ventana", "Es una lástima que hayan roto la ventana", "Es una lástima que rompieron la ventana", "Es una lástima que rompían la ventana"],
        2,
        "Present perfect subjunctive: 'hayan roto'. 'Es una lástima que' (emotion) triggers subjunctive. 'Romper' → irregular participle 'roto'.",
    ),
    (
        "If we had had time, we would have visited the museum.",
        ["Si teníamos tiempo, habríamos visitado el museo", "Si hubiéramos tenido tiempo, habríamos visitado el museo", "Si tendríamos tiempo, habríamos visitado el museo", "Si tuvimos tiempo, habríamos visitado el museo"],
        2,
        "Past perfect subjunctive: 'hubiéramos tenido' + conditional perfect 'habríamos visitado'. 'Teníamos' and 'tuvimos' don't form the hypothetical 'si' clause.",
    ),
    (
        "If you had told me, I would have helped you.",
        ["Si me decías, te habría ayudado", "Si me hubieras dicho, te habría ayudado", "Si me habrías dicho, te ayudaría", "Si me dijiste, te habría ayudado"],
        2,
        "Past perfect subjunctive: 'hubieras dicho' + conditional perfect 'habría ayudado'. 'Decías' (imperfect) and 'dijiste' (preterite) don't form the hypothetical 'si' clause.",
    ),
    (
        "We have returned the books to the library.",
        ["Hemos devueltos los libros a la biblioteca", "Hemos devuelto los libros a la biblioteca", "Hemos devolvído los libros a la biblioteca", "Hemos vuelto los libros a la biblioteca"],
        2,
        "'Devolver' → irregular participle 'devuelto' (not 'devueltos' or 'devolvído'). 'Hemos devuelto' is correct. Note: 'volver' → 'vuelto', but 'devolver' → 'devuelto'.",
    ),
    (
        "By December, they will have opened the new highway.",
        ["Para diciembre, han abierto la nueva autopista", "Para diciembre, habrán abierto la nueva autopista", "Para diciembre, abrirán la nueva autopista", "Para diciembre, habrán abriendo la nueva autopista"],
        2,
        "Future perfect: 'habrán abierto'. 'Han abierto' is present perfect, 'abrirán' is simple future — neither conveys completion before a future deadline.",
    ),
    (
        "He would have returned earlier but there was traffic.",
        ["Habría regresado más temprano pero había tráfico", "Habría vuelto más temprano pero había tráfico", "Regresaría más temprano pero había tráfico", "Both 1 and 2 are correct"],
        4,
        "Both 'habría regresado' (from 'regresar') and 'habría vuelto' (from 'volver') are correct. In Mexican Spanish, 'regresar' is more common than 'volver'. 'Regresaría' is conditional (would return, not would have returned).",
    ),
]


if __name__ == "__main__":
    run_exercises(exercises, title="Lección 8: Perfect Tenses & Irregular Past Participles")
    choose_translation(pairs, title="Lección 8: Choose the Best Translation")