import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

from workbook_engine import run_exercises, choose_translation


exercises = [
    {
        "question": 'Translate: "What did you say?" (Mexican polite form)',
        "answer": ["¿mande?", "mande"],
        "hint": "A uniquely Mexican way to ask someone to repeat themselves",
        "explanation": "¿Mande? is the standard Mexican response when you didn't hear someone. It comes from 'mandar' (to command/order) — literally 'Command me?' It's more polite than ¿Qué? or ¿Cómo?.",
        "context": "Your abuelita said something and you didn't catch it.",
    },
    {
        "question": "Translate: \"Wow, that's incredible!\" (Mexican exclamation)",
        "answer": ["¡híjole!", "híjole", "¡órale!", "órale"],
        "hint": "A very Mexican expression of surprise",
        "explanation": "Híjole expresses surprise, concern, or emphasis — like 'Wow!' or 'Oh man!' It's a softened form of 'hijo de...' Órale can also express surprise but is more versatile (agreement, encouragement, surprise).",
        "context": "Your friend tells you the price of something expensive.",
    },
    {
        "question": 'Translate: "For real? No way!"',
        "answer": ["¿neta?", "neta"],
        "hint": "Mexican slang for 'really?' or 'for real'",
        "explanation": "Neta means 'the truth' or 'for real.' As a question ¿Neta? = 'Really? / For real?' As a statement, 'Es neta' = 'It's true / No joke.' Very common in Mexican Spanish.",
        "context": "Your friend tells you some surprising chisme (gossip).",
    },
    {
        "question": 'Translate: "Do it right away!" (Mexican expression)',
        "answer": ["hazlo luego luego", "luego luego"],
        "hint": "Mexican reduplication for emphasis",
        "explanation": "Luego luego means 'right away' or 'immediately.' The repetition of 'luego' adds emphasis — a uniquely Mexican construction. It's stronger than just 'luego' (later).",
        "context": "Your boss wants the report done without delay.",
    },
    {
        "question": "Translate: \"That's really cool!\" (Mexican slang)",
        "answer": ["¡está chido!", "está chido", "¡está padre!", "está padre", "¡qué chido!", "qué chido", "¡qué padre!", "qué padre"],
        "hint": "Two common Mexican words for 'cool'",
        "explanation": "Chido and padre are the two most common Mexican words for 'cool/great.' Both are used all over Mexico. '¡Qué chido!' = 'How cool!' 'Está padre' = 'It's great.' Neither is used much outside Mexico.",
        "context": "Your friend shows you their new car.",
    },
    {
        "question": 'Translate: "I\'ll do it in a little bit." (with Mexican ambiguity)',
        "answer": ["lo hago ahorita", "ahorita lo hago"],
        "hint": "The famously ambiguous Mexican time word",
        "explanation": "Ahorita is one of the trickiest Mexican words. It literally means 'a little now' but can mean 'right now,' 'in a bit,' or even 'never.' Context and tone determine the meaning. When your mom says 'ahorita,' it means NOW.",
        "context": "Your mom asked you to clean your room and you're procrastinating.",
    },
    {
        "question": 'Translate: "What\'s up?" (Mexican informal)',
        "answer": ["¿qué onda?", "qué onda"],
        "hint": "Very common Mexican greeting",
        "explanation": "¿Qué onda? is the classic Mexican casual greeting, equivalent to 'What's up?' Often shortened to just ¿Onda? among close friends. Very Mexican — not commonly used in other Spanish-speaking countries.",
        "context": "You run into a friend at the tianguis (street market).",
    },
    {
        "question": 'Translate: "He\'s really laid-back." (Mexican expression)',
        "answer": ["es muy fresco", "está muy fresco", "es bien fresco"],
        "hint": "Mexican word for relaxed/chill",
        "explanation": "Fresco in Mexican Spanish means relaxed, easygoing, chill. 'Estar fresco' = to be relaxed. Don't confuse with 'al fresco' (which can mean 'in the open air' or, in some contexts, 'buck naked'!).",
        "context": "Describing a friend who never stresses about anything.",
    },
    {
        "question": 'Translate: "That\'s really uncool / bad." (Mexican slang)',
        "answer": ["¡qué gacho!", "qué gacho", "está gacho", "¡está gacho!"],
        "hint": "The opposite of chido/padre",
        "explanation": "Gacho means bad, uncool, unfair, or ugly (in character). '¡Qué gacho!' = 'How uncool!' or 'That sucks!' It's the opposite of chido/padre. Very Mexican.",
        "context": "Someone cancels plans at the last minute.",
    },
    {
        "question": 'Translate: "Put some effort into it!" (Mexican expression)',
        "answer": ["¡échale ganas!", "échale ganas"],
        "hint": "A very Mexican motivational phrase",
        "explanation": "Echar ganas literally means 'to throw desire at it' — it means to put effort, enthusiasm, or heart into something. It's one of the most Mexican motivational phrases. Parents, teachers, and friends all say ¡Échale ganas!",
        "context": "Your friend is struggling with their thesis and needs encouragement.",
    },
    {
        "question": 'Translate: "I think that..." (Mexican hedging expression)',
        "answer": ["se me hace que...", "se me hace que"],
        "hint": "A uniquely Mexican way to express an opinion tentatively",
        "explanation": "Se me hace que... literally 'it makes itself to me that...' is a very Mexican way to say 'I think that...' or 'It seems to me that...' It softens the statement, similar to 'I kinda think...' It's used constantly in everyday Mexican speech.",
        "context": "You're not 100% sure, but you think the restaurant is on the next block.",
    },
    {
        "question": 'Translate: "A little coffee, please" (using Mexican diminutive for affection)',
        "answer": ["un cafecito, por favor", "un cafecito por favor"],
        "hint": "Add -ito to café for warmth, not just size",
        "explanation": "In Mexican Spanish, -ito/-ita isn't just for small things — it adds warmth, affection, or friendliness. Un cafecito isn't necessarily a small coffee; it's a coffee offered with warmth. Similarly: ahorita, rapidito, poquito, besito.",
        "context": "You're at a café in Coyoacán and want to sound friendly.",
    },
    {
        "question": 'Translate: "Come here quickly!" (using Mexican diminutive for softening)',
        "answer": ["¡ven rapidito!", "ven rapidito", "¡ven aquilito!", "ven aquilito"],
        "hint": "Mexicans soften commands with -ito",
        "explanation": "Mexicans often add -ito to soften commands: ven rapidito (come quickly) sounds friendlier than ven rápido. Aquilito = right here. The diminutive doesn't change the meaning much — it changes the TONE to be warmer and less harsh.",
        "context": "Calling a child to come eat their tamales.",
    },
    {
        "question": 'Fill in the blank: "In Mexico, you use ___ (informal you), not vos."',
        "answer": "tú",
        "hint": "Mexican Spanish uses this pronoun for informal 'you'",
        "explanation": "Mexican Spanish uses tú (not vos) for informal 'you.' Voseo is used in Argentina, Uruguay, Central America, and parts of Colombia, but never in Mexico. If you learned Argentine Spanish, switch to tú in Mexico!",
        "context": "Explaining Mexican Spanish to an Argentine friend.",
    },
    {
        "question": 'Translate: "Um, I mean, like..." (Mexican filler words)',
        "answer": ["este, o sea, bueno"],
        "hint": "Three common Mexican filler words",
        "explanation": "Mexican Spanish has distinct filler words: 'este' (um/uh), 'o sea' (I mean/like — very common among young Mexicans), and 'bueno' (well/so). These fill pauses just like English filler words. 'O sea' is especially characteristic of Mexican youth speech.",
        "context": "You're telling a story and pausing to think.",
    },
    {
        "question": "Translate: \"No way! You've got to be kidding!\" (polite Mexican slang)",
        "answer": ["¡no manches!", "no manches"],
        "hint": "Polite Mexican expression of disbelief — the family-friendly version",
        "explanation": "¡No manches! is the polite version of a stronger expression. It means 'No way!' or 'You've got to be kidding!' Extremely common in Mexican Spanish to express disbelief without being offensive.",
        "context": "Your friend tells you they won the lottery.",
    },
    {
        "question": "Translate: \"No freaking way! You're lying!\" (stronger Mexican slang)",
        "answer": ["¡no mames!", "no mames"],
        "hint": "Vulgar Mexican expression of disbelief — NOT for polite company",
        "explanation": "¡No mames! is the vulgar version of ¡No manches! Both express disbelief, but ¡No mames! is crude and should never be used in formal settings or with strangers. Very common among close male friends in Mexico.",
        "context": "Your compa tells you something absolutely unbelievable.",
    },
    {
        "question": "Translate: \"What's up?\" (old-school Mexican slang)",
        "answer": ["¿qué pachuca?", "qué pachuca"],
        "hint": "A classic older-generation Mexican greeting",
        "explanation": "¿Qué pachuca? is an older Mexican slang greeting meaning 'What's up?' It's associated with an earlier generation and has a nostalgic feel. Younger Mexicans say ¿Qué onda? but ¿Qué pachuca? is still understood.",
        "context": "Running into an older uncle at the mercado.",
    },
    {
        "question": "Translate: \"He was carrying a gun\" (Mexican slang for gun)",
        "answer": ["traía una fusca", "andaba con fusca", "cargaba una fusca"],
        "hint": "Mexican slang word for a firearm",
        "explanation": "Fusca is Mexican slang for 'gun' or 'firearm.' It's informal and associated with criminal or rough contexts. Don't use it in polite conversation — it's like saying 'piece' or 'gat' in English slang.",
        "context": "Describing a sketchy situation at the tianguis.",
    },
    {
        "question": "Translate: \"I have a lot of work\" (Mexican slang for work/job)",
        "answer": ["tengo mucha chamba", "tengo mucha chamba que hacer"],
        "hint": "Mexican slang word for 'work' or 'job'",
        "explanation": "Chamba is Mexican slang for 'work' or 'job.' It comes from English 'chamber' (as in chamber of commerce jobs). Very common: 'Tengo mucha chamba' = 'I have a lot of work.' The verb form is 'chambear' = to work.",
        "context": "A friend asks why you can't go out tonight.",
    },
    {
        "question": "Translate: \"She works from Monday to Saturday\" (Mexican verb for work)",
        "answer": ["ella chambea de lunes a sábado", "chambea de lunes a sábado"],
        "hint": "Mexican slang verb meaning 'to work'",
        "explanation": "Chambea is the verb form of 'chamba' (work/job). It means 'to work' in casual Mexican Spanish. 'Ella chambea de lunes a sábado' = 'She works from Monday to Saturday.' More informal than 'trabajar.'",
        "context": "Talking about a friend's intense work schedule.",
    },
    {
        "question": "Translate: \"I don't have any money\" (Mexican slang for money)",
        "answer": ["no tengo lana", "no tengo varo", "no tengo morro"],
        "hint": "Three Mexican slang words for money",
        "explanation": "Lana, varo, and morro are all Mexican slang for 'money.' Lana (literally 'wool') is the most common. Varo is also widely used. Morro is less common but still understood. All are informal — like saying 'dough' or 'cash' in English.",
        "context": "Explaining to a friend why you can't go out.",
    },
    {
        "question": "Translate: \"I'm so hungover today\" (Mexican slang for hangover)",
        "answer": ["estoy muy crudo hoy", "estoy crudo"],
        "hint": "Mexican word for 'hungover'",
        "explanation": "Crudo literally means 'raw' but in Mexican Spanish it means 'hungover.' 'Estoy crudo' = 'I'm hungover.' The noun form is 'la cruda' = 'the hangover.' Very common after a night of tequila or mezcal.",
        "context": "The morning after a fiesta with too many micheladas.",
    },
    {
        "question": "Translate: \"That exam was really difficult\" (Mexican slang for difficult)",
        "answer": ["ese examen estuvo cañón", "ese examen estuvo bien cañón", "estuvo cañón el examen"],
        "hint": "Mexican slang word meaning 'difficult' or 'tough'",
        "explanation": "Cañón literally means 'canyon' or 'cannon' but in Mexican slang it means 'difficult, tough, or intense.' 'Estuvo cañón' = 'It was really hard.' Used for exams, situations, or anything challenging.",
        "context": "Complaining about a brutal university exam at UNAM.",
    },
    {
        "question": "Translate: \"There's going to be a fight\" (Mexican slang for fight/problem)",
        "answer": ["va a haber bronca", "se va a armar la bronca"],
        "hint": "Mexican slang for a problem, conflict, or fight",
        "explanation": "Bronca means 'problem,' 'conflict,' or 'fight' in Mexican Spanish. 'Va a haber bronca' = 'There's going to be trouble.' 'Se armó la bronca' = 'The fight broke out.' Very versatile and commonly used.",
        "context": "You see two drunk guys starting to argue at a cantina.",
    },
    {
        "question": "Translate: \"Don't be so stingy!\" (Mexican slang for stingy)",
        "answer": ["¡no seas tan codo!", "no seas codo"],
        "hint": "Mexican slang for someone who's cheap or stingy",
        "explanation": "Codo literally means 'elbow' but in Mexican slang it means 'stingy' or 'cheap.' 'No seas codo' = 'Don't be cheap/stingy.' A person who is codo doesn't like to spend money. Very common Mexican expression.",
        "context": "Your friend won't chip in for the tacos and you're annoyed.",
    },
    {
        "question": "Translate: \"Yeah, I'll be there\" (Mexican slang affirmative)",
        "answer": ["simón, ahí estoy", "simón, ahí nos vemos", "simón"],
        "hint": "Mexican slang for 'yeah' or 'yes, indeed'",
        "explanation": "Simón is Mexican slang for 'yeah' or 'yes, indeed.' It's a casual, emphatic affirmative — like saying 'heck yeah' or 'for sure.' Common among friends, especially in central and northern Mexico.",
        "context": "Confirming you'll be at the carne asada on Sunday.",
    },
    {
        "question": "Translate: \"No way, not a chance!\" (Mexican slang negative)",
        "answer": ["¡nelpas!", "nelpas", "¡nelpas, ni loco!"],
        "hint": "Mexican slang for 'no way' or 'not happening'",
        "explanation": "Nelpas is Mexican slang meaning 'no way,' 'not a chance,' or 'absolutely not.' It's the emphatic negative counterpart to 'simón.' '¡Nelpas!' = 'No way!' Often combined: '¡Nelpas, ni loco!' = 'No way, not even crazy!'",
        "context": "Someone asks you to work on a Sunday and you refuse.",
    },
    {
        "question": "Translate: \"Listen up, brother\" (Mexican slang for brother + attention-getter)",
        "answer": ["óyeme, carnal", "óyeme carnal"],
        "hint": "Mexican attention word + slang for 'brother'",
        "explanation": "Óyeme means 'listen to me' or 'listen up' — used to get someone's attention, like 'hey!' Carnal literally means 'flesh/blood' but is Mexican slang for 'brother' or 'close friend.' Together: 'Óyeme, carnal' = 'Listen up, bro.'",
        "context": "Getting your friend's attention before sharing important chisme.",
    },
    {
        "question": "Translate: \"Really? Are you serious?\" (Mexican expression of disbelief)",
        "answer": ["¿a poco?", "a poco", "¿a poco en serio?"],
        "hint": "Very common Mexican expression meaning 'really?' or 'no way?'",
        "explanation": "¿A poco? is a uniquely Mexican expression meaning 'Really?' or 'You don't say!' It expresses mild disbelief or surprise. '¿A poco en serio?' = 'Really, seriously?' It's used constantly in everyday Mexican conversation.",
        "context": "Your friend tells you they got a promotion at work.",
    },
    {
        "question": "Translate: \"Let's go! Come on!\" (Mexican expression of encouragement/movement)",
        "answer": ["¡arre!", "arre", "¡arre, vámonos!"],
        "hint": "Mexican expression meaning 'let's go!' or 'come on!'",
        "explanation": "¡Arre! is a Mexican expression meaning 'Let's go!' or 'Come on!' Originally from commands to mules/horses (like 'giddy-up'), it's now used to urge people to move. '¡Arre, vámonos!' = 'Come on, let's go!'",
        "context": "Rounding up your friends to leave for the party.",
    },
    {
        "question": "Translate: \"He's my brother\" (Mexican slang for brother)",
        "answer": ["es mi carnal", "es mi carnal, compa"],
        "hint": "Mexican slang word meaning 'brother' or 'close friend'",
        "explanation": "Carnal literally means 'flesh/blood' (from 'carne') but in Mexican slang it means 'brother' or 'very close friend.' 'Es mi carnal' can mean literal brother or best friend. The feminine form is 'carnala' = sister/close female friend.",
        "context": "Introducing your best friend or actual brother at a gathering.",
    },
    {
        "question": "Translate: \"My buddy and I went out\" (Mexican slang for buddy)",
        "answer": ["mi compa y yo salimos", "yo y mi compa salimos"],
        "hint": "Mexican slang for 'buddy' or 'pal'",
        "explanation": "Compa is short for 'compadre' and means 'buddy,' 'pal,' or 'friend' in Mexican Spanish. It's very common among men. 'Mi compa' = 'My buddy.' The full form 'compadre' is also used but 'compa' is more casual and everyday.",
        "context": "Telling someone about your night out with a close friend.",
    },
    {
        "question": "Translate: \"That dude doesn't know anything\" (Mexican slang for dude)",
        "answer": ["ese vato no sabe nada", "ese vato no sabe ni madres"],
        "hint": "Mexican slang word for 'dude' or 'guy'",
        "explanation": "Vato is Mexican slang for 'dude,' 'guy,' or 'man.' It's used mainly in northern and central Mexico. 'Ese vato' = 'That dude.' It can be slightly rough but is widely understood. The feminine form 'vata' exists but is less common.",
        "context": "Pointing out someone who's clueless about the situation.",
    },
    {
        "question": "Translate: \"The girl at the counter is really nice\" (Mexican slang for girl)",
        "answer": ["la morra del mostrador es bien amable", "la morra de mostrador es muy amable"],
        "hint": "Mexican slang for 'girl' or 'young woman'",
        "explanation": "Morra is Mexican slang for 'girl' or 'young woman.' It's informal and commonly used among young people. 'Esa morra' = 'That girl.' It can be affectionate or neutral depending on context. Not rude, but not for formal settings.",
        "context": "Noticing a friendly girl working at a store.",
    },
    {
        "question": "Translate: \"That old man has been here forever\" (Mexican slang for old person)",
        "answer": ["ese ruco lleva tiempo aquí", "ese ruco lleva mucho aquí", "ese ruco lleva años aquí"],
        "hint": "Mexican slang for 'old person' — not necessarily disrespectful",
        "explanation": "Ruco is Mexican slang for 'old person' or 'older person.' It can be used affectionately or dismissively depending on tone. 'Ese ruco' = 'That old guy.' In some contexts it's like 'that old dude' — not necessarily rude, but informal.",
        "context": "Talking about a regular customer at the tianguis who's been going there forever.",
    },
    {
        "question": "Translate: \"The kids are playing outside\" (Mexican slang for kid)",
        "answer": ["los chamacos están jugando afuera", "las chamas están jugando afuera"],
        "hint": "Very common Mexican word for 'kid' or 'child'",
        "explanation": "Chamaco (masculine) / chama (feminine) means 'kid' or 'child' in Mexican Spanish. It's very commonly used, more informal than 'niño/niña' but not rude. 'Los chamacos' = 'The kids.' Used by everyone in Mexico.",
        "context": "Describing the neighborhood kids playing in the street.",
    },
    {
        "question": "Translate: \"That brat won't behave\" (Mexican slang for brat/punk kid)",
        "answer": ["ese escuincle no se porta bien", "ese escuincle no obedece", "ese escuincle no se está quieto"],
        "hint": "Mexican slang for 'brat' or 'annoying kid' — from Nahuatl",
        "explanation": "Escuincle (from Nahuatl 'itzcuintli' — the Mexican hairless dog) means 'brat' or 'pesky kid' in Mexican Spanish. It's more negative than 'chamaco' — implying the kid is annoying or misbehaving. 'Ese escuincle' = 'That brat.'",
        "context": "A kid is running around the restaurant screaming and you're annoyed.",
    },
    {
        "question": "Translate: \"The Americans always stand out\" (Mexican word for American/foreigner)",
        "answer": ["los gabachos siempre destacan", "los gabachos siempre llaman la atención"],
        "hint": "Mexican word for Americans or foreigners, especially from the US",
        "explanation": "Gabacho in Mexican Spanish refers to Americans or people from the US (and sometimes other foreigners). It's informal and can be slightly dismissive but not always offensive — context matters. 'Los gabachos' = 'The Americans.' In Spain, 'gabacho' means 'French.'",
        "context": "Discussing how tourists from the US always seem obvious at the mercado.",
    },
    {
        "question": "Translate: \"The light-skinned guy at the door\" (Mexican word for light-skinned/blond)",
        "answer": ["el güero de la puerta", "el güero que está en la puerta"],
        "hint": "Very common Mexican word for light-skinned or light-haired person",
        "explanation": "Güero is one of the most common Mexican words. It refers to anyone with light skin or light hair — not necessarily white. Mexicans use it affectionately as a nickname. 'El güero' = 'The light-skinned guy.' It's not offensive.",
        "context": "Describing someone at a party to help your friend find them.",
    },
    {
        "question": "Translate: \"Can you wait a little bit?\" (Mexican diminutive for a short time)",
        "answer": ["¿puedes esperar un ratito?", "espera un ratito, ¿sí?"],
        "hint": "Mexican diminutive of 'rato' — softens the request",
        "explanation": "Un ratito is the diminutive of 'un rato' (a while). In Mexican Spanish, it means 'a little bit' or 'just a short time.' Adding -ito softens the request: 'Espera un ratito' sounds much gentler than 'Espera un rato.' Classic Mexican politeness through diminutives.",
        "context": "You need a friend to wait while you finish getting ready.",
    },
    {
        "question": "Translate: \"Just a little bit more, please\" (Mexican diminutive for small amount)",
        "answer": ["un poquito más, por favor", "nada más un poquito, por favor"],
        "hint": "Diminutive of 'poco' — Mexicans love their diminutives",
        "explanation": "Poquito is the diminutive of 'poco' (little). In Mexican Spanish, 'un poquito' means 'just a little bit.' Mexicans love their diminutives — they add warmth and politeness to everyday requests. 'Un poquito más, por favor' sounds much sweeter than 'un poco más.'",
        "context": "Asking for just a little more salsa at the taquería.",
    },
    {
        "question": "Translate: \"Let's go get some tacos\" (using Mexican diminutive for tacos)",
        "answer": ["vámonos por unos taquitos", "vamos por unos taquitos"],
        "hint": "Mexicans add -itos to food words for affection, not just size",
        "explanation": "Taquitos doesn't necessarily mean 'small tacos' — in Mexican Spanish, adding -itos to food words expresses affection and casualness. 'Vamos por unos taquitos' = 'Let's go grab some tacos.' It sounds friendlier and more inviting than 'vamos a comer tacos.'",
        "context": "Inviting friends for a casual late-night taco run.",
    },
    {
        "question": "Translate: \"Let me buy you a beer\" (using Mexican diminutive for politeness)",
        "answer": ["déjame invitarte una cervecita", "te invito una cervecita"],
        "hint": "Mexicans soften offers with -ita on drinks",
        "explanation": "Cervecita is the diminutive of 'cerveza' (beer). In Mexican culture, 'te invito una cervecita' sounds warmer and more casual than 'te invito una cerveza.' The -ita doesn't mean a small beer — it adds friendliness. 'Invitar' in Mexico means 'to treat/buy for.'",
        "context": "Offering a friend a drink at the cantina.",
    },
    {
        "question": "Translate: \"Give grandma a kiss\" (Mexican diminutive for affection)",
        "answer": ["dale un besito a la abuelita", "dale un besito a abuelita"],
        "hint": "Double diminutive: besito + abuelita = maximum affection",
        "explanation": "Besito (little kiss) and abuelita (grandma) both use diminutives to express affection. In Mexican culture, 'Dale un besito a la abuelita' is how you'd tell a child to kiss their grandmother. The diminutives make it tender, not about size.",
        "context": "Telling your child to go kiss their grandmother goodbye.",
    },
    {
        "question": "Translate: \"We visited a little town\" (Mexican diminutive for town)",
        "answer": ["visitamos un pueblito", "fuimos a visitar un pueblito"],
        "hint": "Diminutive of 'pueblo' — adds charm and affection",
        "explanation": "Pueblito is the diminutive of 'pueblo' (town). 'Un pueblito' means 'a little town' but also carries affection — it evokes the charm of small Mexican towns. Many Mexicans refer to their hometown with love as 'mi pueblito' regardless of its size.",
        "context": "Describing a weekend trip to a charming town in the mountains.",
    },
    {
        "question": "Translate: \"Grandma's food is the best\" (using Mexican affectionate form)",
        "answer": ["la comida de la abuelita es la mejor", "lo que cocina la abuelita es lo mejor"],
        "hint": "Mexicans say 'abuelita' not just 'abuela' — it shows love",
        "explanation": "Abuelita is the affectionate form of 'abuela' (grandmother). In Mexico, you almost always say 'abuelita' rather than 'abuela' — it's warmer and more loving. 'La comida de la abuelita' means grandma's home cooking, which in Mexico is the ultimate comfort food.",
        "context": "Telling someone why your grandma's mole is unbeatable.",
    },
    {
        "question": "Translate: \"Hello?\" (Mexican phone greeting)",
        "answer": ["¿bueno?"],
        "hint": "The uniquely Mexican way to answer the phone",
        "explanation": "¿Bueno? is the standard Mexican phone greeting. It literally means 'Good?' but functions like 'Hello?' on the phone. Other Spanish-speaking countries use 'Aló,' 'Diga,' or 'Hola,' but in Mexico, you always answer with '¿Bueno?' It's one of the most distinctive Mexicanisms.",
        "context": "Answering a phone call in Mexico.",
    },
    {
        "question": "Translate: \"Okay, sure, I'll do it\" (Mexican affirmative)",
        "answer": ["ándale, lo hago", "ándale pues", "ándale, ahí la va"],
        "hint": "One of the most versatile Mexican words",
        "explanation": "Ándale means 'okay,' 'sure,' 'go ahead,' or 'come on' depending on context and intonation. It's one of the most Mexican words there is. 'Ándale pues' = 'Alright then.' It can express agreement, encouragement, or even frustration. Uniquely Mexican.",
        "context": "Your friend asks you to help them move and you agree.",
    },
    {
        "question": "Translate: \"Go ahead, start without me\" (Mexican expression)",
        "answer": ["hágale, empiece sin mí", "hágale pues", "hágale, no me esperen"],
        "hint": "Mexican expression meaning 'go ahead' or 'do it'",
        "explanation": "Hágale means 'go ahead' or 'do it' in Mexican Spanish. It's from 'hacer' (to do) in the formal command form. '¡Hágale!' = 'Go for it!' It's used to give permission or encouragement. 'Hágale pues' = 'Go ahead then.' Very common in Mexican Spanish.",
        "context": "You're running late and tell your friends to start eating.",
    },
    {
        "question": "Translate: \"I mean, like, it's like this\" (Mexican filler phrase)",
        "answer": ["o sea, es como así", "o sea, es que"],
        "hint": "The most common Mexican filler phrase, especially among young people",
        "explanation": "O sea literally means 'that is to say' but in Mexican Spanish it's used as a filler like 'I mean' or 'like' in English. Young Mexicans use it constantly: 'O sea, es que...' = 'Like, the thing is...' Overusing it is seen as a marker of 'fresa' (preppy) speech.",
        "context": "Explaining something and pausing to think about how to phrase it.",
    },
    {
        "question": "Translate: \"Tacos al pastor are a Mexico City classic\" (Mexican food)",
        "answer": ["los tacos al pastor son un clásico de la Ciudad de México", "los tacos al pastor son un clásico de la CDMX"],
        "hint": "Iconic Mexican street food — pork on a spit with pineapple",
        "explanation": "Tacos al pastor are Mexico City's iconic street food. Thin slices of marinated pork cooked on a vertical spit (trompo), served with pineapple, onion, and cilantro. Inspired by Lebanese immigrants' shawarma. 'Al pastor' means 'shepherd style.' A must-try in Mexico.",
        "context": "Recommending the best street food to a visitor in Mexico City.",
    },
    {
        "question": "Translate: \"Cochinita pibil is from Yucatán\" (Mexican food)",
        "answer": ["la cochinita pibil es de Yucatán", "la cochinita pibil es yucateca"],
        "hint": "Slow-roasted pork marinated in achiote — a Yucatec specialty",
        "explanation": "Cochinita pibil is Yucatán's signature dish — pork marinated in achiote (annatto) and bitter orange, wrapped in banana leaves, and slow-roasted underground. It's served as tacos or tortas. In Yucatán, it's eaten for breakfast. One of Mexico's most regional and iconic dishes.",
        "context": "Explaining regional Mexican cuisine to a foodie friend.",
    },
    {
        "question": "Translate: \"I want chilaquiles for breakfast\" (Mexican food)",
        "answer": ["quiero chilaquiles para desayunar", "quiero chilaquiles verdes para desayunar"],
        "hint": "Fried tortilla chips in salsa — classic Mexican breakfast",
        "explanation": "Chilaquiles are a quintessential Mexican breakfast — fried tortilla chips simmered in green (verdes) or red (rojos) salsa, topped with cream, cheese, and often chicken or eggs. Every Mexican family has their own recipe. They cure hangovers (crudos) like nothing else.",
        "context": "Ordering breakfast at a fondita after a night of too many mezcales.",
    },
    {
        "question": "Translate: \"Corn on the cob is street food\" (Mexican street food)",
        "answer": ["el elote es comida callejera", "los esquites son comida callejera"],
        "hint": "Two Mexican ways to eat corn — on the cob or in a cup",
        "explanation": "Elote is corn on the cob slathered with mayo, cheese, chili, and lime — a beloved Mexican street food. Esquites is the same thing served in a cup with the kernels cut off. Both are essentials of Mexican street food culture. In Mexico City, you find elote carts everywhere.",
        "context": "Describing Mexican street food to someone who's never visited.",
    },
    {
        "question": "Translate: \"Red pozole is traditional for celebrations\" (Mexican food)",
        "answer": ["el pozole rojo es tradicional para las fiestas", "el pozole rojo es de tradición para celebraciones"],
        "hint": "Mexico's iconic celebratory soup with hominy and pork",
        "explanation": "Pozole is Mexico's celebration soup — hominy (maíz cacahuazintle) stewed with pork or chicken in a red (rojo), green (verde), or white (blanco) broth. Red pozole uses guajillo chiles. It's traditionally served on Mexican Independence Day and special occasions. Pozole blanco is from Jalisco.",
        "context": "Explaining why pozole is always served at your family's Independence Day party.",
    },
    {
        "question": "Translate: \"Menudo cures a hangover\" (Mexican food)",
        "answer": ["el menudo cura el crudo", "el menudo es bueno para la cruda"],
        "hint": "Traditional Mexican tripe soup — the legendary hangover cure",
        "explanation": "Menudo is a traditional Mexican soup made with tripe (beef stomach) in a red chile broth with hominy. It's legendary as a hangover cure — 'El menudo cura el crudo.' Sundays are menudo day in many Mexican families. It requires hours of cooking and patience.",
        "context": "Your friend is crudo from last night and you recommend menudo.",
    },
    {
        "question": "Translate: \"In Mexico, we use 'usted' with elders\" (Mexican politeness rule)",
        "answer": ["en México le tratamos de usted a los mayores", "en México usamos 'usted' con los mayores"],
        "hint": "Mexican Spanish strongly maintains the usted/tú distinction",
        "explanation": "In Mexico, usted is used with elders, strangers, and authority figures as a sign of respect. Many Mexicans always address their grandparents as usted. In workplaces, colleagues may start with usted and switch to tú over time. The usted/tú distinction is very much alive in Mexico.",
        "context": "Explaining Mexican politeness norms to a foreigner who keeps using tú with elders.",
    },
    {
        "question": "Translate: \"In Mexico, we say 'tomar' for 'to drink'\" (Mexican vs other dialects)",
        "answer": ["en México decimos 'tomar' por 'beber'", "en México usamos 'tomar' en vez de 'beber'"],
        "hint": "Mexican Spanish prefers 'tomar' over 'beber' for drinking",
        "explanation": "In Mexican Spanish, 'tomar' is the standard word for 'to drink.' In Spain and some other countries, 'beber' is more common. In Mexico, 'beber' sounds formal or literary. 'Vamos a tomar una cerveza' = 'Let's have a beer.' 'Tomar' also means 'to take' — context makes it clear.",
        "context": "Explaining a key Mexicanism to someone who learned European Spanish.",
    },
    {
        "question": "Translate: \"Let me check the schedule\" (Mexican loanword from English)",
        "answer": ["déjame checar el horario", "deja checo el horario", "déjame checar el itinerario"],
        "hint": "Mexican Spanish has borrowed 'check' from English as 'checar'",
        "explanation": "Checar is a Mexican loanword from English 'check.' It's extremely common in Mexican Spanish: 'Voy a checar' = 'I'm going to check.' Other Spanish speakers say 'verificar' or 'revisar,' but Mexicans say 'checar.' It's fully integrated into Mexican Spanish and appears in everyday speech.",
        "context": "At work, you need to verify the meeting time.",
    },
    {
        "question": "Translate: \"Birria is from Jalisco\" (Mexican food)",
        "answer": ["la birria es de Jalisco", "la birria es jalisciense"],
        "hint": "Slow-cooked meat stew from Jalisco — now a global taco sensation",
        "explanation": "Birria originated in Jalisco — it's meat (traditionally goat) slow-cooked in a rich chile broth. Originally a poor man's stew, birria has become globally famous through birria tacos (tacos dipped in consommé). Jalisco is also the home of tequila and mariachi.",
        "context": "Explaining the origins of birria to someone who thinks it's just a taco trend.",
    },
    {
        "question": "Translate: \"In Mexico, we say 'manejar' for 'to drive'\" (Mexican vs other dialects)",
        "answer": ["en México decimos 'manejar' por 'conducir'", "en México usamos 'manejar' en vez de 'conducir'"],
        "hint": "Mexicans say 'manejar' while Spaniards and others say 'conducir'",
        "explanation": "In Mexican Spanish, 'manejar' is the standard word for 'to drive.' In Spain and some South American countries, 'conducir' is preferred. In Mexico, 'conducir' sounds formal or foreign. 'Manejar el coche' = 'to drive the car.' This is one of the clearest Mexicanisms.",
        "context": "Explaining Mexican vocabulary to someone who learned Peninsular Spanish.",
    },
    {
        "question": "Translate: \"In Mexico, we say 'platicar' for 'to chat'\" (Mexican vs other dialects)",
        "answer": ["en México decimos 'platicar' por 'charlar'", "en México usamos 'platicar' en vez de 'hablar'"],
        "hint": "Mexicans prefer 'platicar' for casual conversation",
        "explanation": "In Mexican Spanish, 'platicar' means 'to chat' or 'to have a conversation.' In other Spanish-speaking countries, 'charlar' or 'conversar' is more common. 'Vamos a platicar' = 'Let's chat.' Platicar implies a casual, warm conversation — very Mexican.",
        "context": "Explaining why Mexicans say 'platicar' when others say 'charlar.'",
    },
    {
        "question": "Translate: \"Huevos rancheros are a classic breakfast\" (Mexican food)",
        "answer": ["los huevos rancheros son un desayuno clásico", "los huevos rancheros son un clásico del desayuno"],
        "hint": "Fried eggs on tortillas with salsa — the quintessential Mexican breakfast",
        "explanation": "Huevos rancheros are fried eggs served on corn tortillas with salsa, beans, and sometimes rice. 'Rancheros' means 'ranch-style.' They're the quintessential Mexican breakfast and appear on every breakfast menu from street stalls to fine restaurants.",
        "context": "Ordering breakfast at a traditional Mexican restaurant.",
    },
    {
        "question": "Translate: \"Carnitas are from Michoacán\" (Mexican food)",
        "answer": ["las carnitas son de Michoacán", "las carnitas son michoacanas"],
        "hint": "Slow-fried pork — Michoacán's gift to Mexican cuisine",
        "explanation": "Carnitas are small pieces of pork slow-fried in their own fat until crispy on the outside and tender inside. They're from Michoacán and are one of Mexico's most beloved taco fillings. 'Carnitas michoacanas' are famous throughout the country.",
        "context": "Ordering carnitas at a market stand and explaining their origin.",
    },
    {
        "question": "Translate: \"Atole is a warm corn-based drink\" (Mexican food/drink)",
        "answer": ["el atole es una bebida caliente de maíz", "el atole es una bebida de maíz"],
        "hint": "Traditional warm Mexican drink made from corn dough",
        "explanation": "Atole is a traditional warm Mexican drink made from corn dough (masa) dissolved in water with milk, sugar, and spices. It comes in many flavors — chocolate (champurrado), strawberry, vanilla. It's drunk during Day of the Dead celebrations and cold mornings. Very Mexican, very comforting.",
        "context": "Describing traditional Mexican beverages to a foreigner at a Day of the Dead celebration.",
    },
    {
        "question": "Translate: \"Tequila is from Jalisco, mezcal is from Oaxaca\" (Mexican drinks)",
        "answer": ["el tequila es de Jalisco, el mezcal es de Oaxaca", "el tequila es jalisciense, el mezcal es oaxaqueño"],
        "hint": "Two iconic Mexican spirits with different origins and production methods",
        "explanation": "Tequila is made from blue agave in Jalisco (especially around the town of Tequila). Mezcal is made from various agave species, primarily in Oaxaca. Tequila is distilled once, mezcal can be artisanal. Mezcal has a smokier flavor. Both are sacred to Mexican culture. 'Para todo mal, mezcal; para todo bien, también.'",
        "context": "Explaining the difference between tequila and mezcal at a cantina.",
    },
]


pairs = [
    (
        "Which is the most Mexican way to say 'What did you say?'",
        ["¿Cómo?", "¿Mande?", "¿Qué dijiste?", "¿Perdón?"],
        2,
        "¿Mande? is uniquely Mexican and more polite than ¿Qué? or ¿Cómo?.",
    ),
    (
        "What does 'ahorita' typically mean when a Mexican friend says it about doing a task?",
        ["Right this second", "Later or maybe never — it's ambiguous", "Yesterday", "Never — it always means never"],
        2,
        "Ahorita is famously ambiguous. It can mean 'right now' or 'in a bit' depending on tone and context. When friends say it, it often means 'later... maybe.'",
    ),
    (
        "Which pair are common Mexican words for 'cool'?",
        ["Guay / chévere", "Chido / padre", "Bacán / che", "Polla / fuerte"],
        2,
        "Chido and padre are distinctly Mexican. Guay is Spanish (Spain), chévere is Latin American but not Mexican, and bacán is South American.",
    ),
    (
        "What does '¡Échale ganas!' mean?",
        ["Throw it away!", "Put effort into it! / Go for it!", "Take it easy!", "Get out of here!"],
        2,
        "Échale ganas literally 'throw desire at it' — it means put effort into it, go for it, give it your all. A very Mexican motivational phrase.",
    ),
    (
        "In Mexican Spanish, why do speakers add -ito/-ita to words like 'café' (cafecito)?",
        ["Only to indicate small size", "To add warmth, affection, or soften the tone", "Because grammar requires it", "To sound more formal"],
        2,
        "In Mexican Spanish, -ito/-ita adds affection and warmth, not just size. Un cafecito is a coffee offered with warmth. Mexicans even say 'hijito' to show tenderness toward a child.",
    ),
    (
        "Which pronoun does Mexican Spanish use for informal 'you'?",
        ["Vos", "Vosotros", "Tú", "Usted"],
        3,
        "Mexico uses tú for informal 'you.' Vos is used in Argentina/Central America. Vosotros is Spain only. Usted is formal in Mexico.",
    ),
    (
        "When would a Mexican use 'usted' instead of 'tú'?",
        ["Only in writing", "With elders, strangers, and people in authority", "Never — Mexicans always use tú", "Only with children"],
        2,
        "In Mexico, usted shows respect to elders, strangers, and authority figures. Young people increasingly use tú among themselves, but usted remains important for showing respect.",
    ),
    (
        "What does 'se me hace que...' mean in Mexican Spanish?",
        ["It makes me do...", "I think that... / It seems to me that...", "I did it myself...", "It happened to me..."],
        2,
        "Se me hace que... is a uniquely Mexican hedging expression meaning 'I think that...' or 'It seems to me that...' It softens opinions and is used constantly in everyday speech.",
    ),
    (
        "What does '¡No manches!' mean in Mexican Spanish?",
        ["Don't stain it!", "No way! / You've got to be kidding!", "Don't touch!", "Stop it!"],
        2,
        "¡No manches! is the polite version of a vulgar expression, meaning 'No way!' or 'You've got to be kidding!' It's extremely common and family-friendly.",
    ),
    (
        "Which Mexican slang word means 'work' or 'job'?",
        ["Fiesta", "Chamba", "Bronca", "Cruda"],
        2,
        "Chamba is Mexican slang for 'work' or 'job.' The verb form is 'chambear' (to work). 'Tengo mucha chamba' = 'I have a lot of work.'",
    ),
    (
        "What does 'estoy crudo' mean in Mexican Spanish?",
        ["I'm raw", "I'm hungry", "I'm hungover", "I'm tired"],
        3,
        "Crudo literally means 'raw' but in Mexican slang it means 'hungover.' 'La cruda' = 'the hangover.' Very common after a night of drinking.",
    ),
    (
        "Which word is Mexican slang for 'difficult' or 'tough'?",
        ["Fresco", "Cañón", "Padre", "Chido"],
        2,
        "Cañón literally means 'canyon' or 'cannon' but in Mexican slang it means 'difficult' or 'tough.' 'Estuvo cañón' = 'It was really hard.'",
    ),
    (
        "What does 'bronca' mean in Mexican Spanish?",
        ["A canyon", "A problem, conflict, or fight", "A type of taco", "A hangover"],
        2,
        "Bronca means 'problem,' 'conflict,' or 'fight.' 'Va a haber bronca' = 'There's going to be trouble.' 'Se armó la bronca' = 'The fight broke out.'",
    ),
    (
        "If someone calls you 'codo' in Mexico, what do they mean?",
        ["You're generous", "You're tall", "You're stingy or cheap", "You're lazy"],
        3,
        "Codo literally means 'elbow' but in Mexican slang it means 'stingy' or 'cheap.' 'No seas codo' = 'Don't be cheap.'",
    ),
    (
        "What does '¡Simón!' mean in Mexican slang?",
        ["Simon! (a name)", "Yeah! / For sure!", "Sit down!", "Be quiet!"],
        2,
        "Simón is Mexican slang for 'yeah' or 'for sure!' It's an emphatic affirmative, like 'heck yeah.' Common among friends.",
    ),
    (
        "What does '¡Nelpas!' mean?",
        ["No way! / Not a chance!", "Next step!", "Never pass!", "No problem!"],
        1,
        "Nelpas is Mexican slang for 'no way' or 'not a chance.' It's the emphatic negative counterpart to 'simón.' '¡Nelpas!' = 'No way!'",
    ),
    (
        "Which Mexican word means 'brother' or 'close friend'?",
        ["Compa", "Carnal", "Vato", "Güero"],
        2,
        "Carnal literally means 'flesh/blood' but in Mexican slang it means 'brother' or 'very close friend.' 'Mi carnal' = 'My brother/best friend.' The feminine form is 'carnala.'",
    ),
    (
        "What does 'vato' mean in Mexican Spanish?",
        ["A type of hat", "A car model", "A dude or guy", "A food dish"],
        3,
        "Vato is Mexican slang for 'dude' or 'guy,' especially common in northern and central Mexico. 'Ese vato' = 'That dude.'",
    ),
    (
        "What does 'morra' mean in Mexican slang?",
        ["A type of bird", "A girl or young woman", "A car", "A headache"],
        2,
        "Morra is Mexican slang for 'girl' or 'young woman.' It's informal but commonly used among young people. 'Esa morra' = 'That girl.'",
    ),
    (
        "What does 'ruco' mean in Mexican Spanish?",
        ["A type of dog", "An old person", "A car", "A house"],
        2,
        "Ruco is Mexican slang for 'old person' or 'older person.' It can be affectionate or dismissive depending on tone. 'Ese ruco' = 'That old dude.'",
    ),
    (
        "What is a 'chamaco' in Mexican Spanish?",
        ["A teenager", "A kid or child", "A student", "A worker"],
        2,
        "Chamaco means 'kid' or 'child' in Mexican Spanish. It's informal but very common. The feminine form is 'chama.' 'Los chamacos' = 'The kids.'",
    ),
    (
        "What does 'escuincle' mean in Mexican Spanish?",
        ["A type of dog", "A brat or annoying kid", "A school", "A type of food"],
        2,
        "Escuincle (from Nahuatl 'itzcuintli,' the Mexican hairless dog) means 'brat' or 'pesky kid.' It's more negative than 'chamaco.' 'Ese escuincle' = 'That brat.'",
    ),
    (
        "What does 'gabacho' mean in Mexican Spanish?",
        ["A type of bread", "An American, especially from the US", "A type of music", "A traditional dance"],
        2,
        "Gabacho in Mexican Spanish refers to Americans or people from the US. It's informal and can be slightly dismissive. Note: In Spain, 'gabacho' means 'French.'",
    ),
    (
        "Why do Mexicans call light-skinned people 'güero'?",
        ["It's an insult", "It's a racial slur", "It's a common, often affectionate descriptor for light-skinned/light-haired people", "It means 'foreigner'"],
        3,
        "Güero refers to light-skinned or light-haired people in Mexican Spanish. It's used affectionately and is one of the most common Mexican descriptors. It's not offensive — it can even be a nickname.",
    ),
    (
        "How do Mexicans typically answer the phone?",
        ["¿Aló?", "¿Diga?", "¿Bueno?", "¿Hola?"],
        3,
        "¿Bueno? is the uniquely Mexican phone greeting. Other countries use Aló (South America), Diga (Spain), or Hola, but in Mexico you always answer with ¿Bueno?",
    ),
    (
        "What does '¡Ándale!' mean in Mexican Spanish?",
        ["Walk!", "Okay / Sure / Come on", "Andale! (a name)", "Go away!"],
        2,
        "Ándale is one of the most versatile Mexican words. It can mean 'okay,' 'sure,' 'come on,' or express agreement. Context and intonation determine the meaning. It's uniquely Mexican.",
    ),
    (
        "What does '¡Hágale!' mean in Mexican Spanish?",
        ["Do it to him!", "Go ahead! / Do it!", "Make it!", "Hit him!"],
        2,
        "Hágale means 'go ahead' or 'do it' in Mexican Spanish. It's from 'hacer' in the formal command form. '¡Hágale!' = 'Go for it!' Very common encouragement.",
    ),
    (
        "What does 'o sea' mean in Mexican Spanish?",
        ["Or the sea", "I mean / Like / That is to say", "Oh yes", "Over there"],
        2,
        "O sea literally means 'that is to say' but functions as 'I mean' or 'like' in Mexican Spanish. Young Mexicans use it constantly as a filler. Overusing it is associated with 'fresa' (preppy) speech.",
    ),
    (
        "What are 'tacos al pastor'?",
        ["Grilled chicken tacos", "Pork tacos cooked on a vertical spit with pineapple", "Fish tacos from the coast", "Beef tacos with avocado"],
        2,
        "Tacos al pastor are Mexico City's iconic street food — marinated pork cooked on a vertical spit (trompo) with pineapple. Inspired by Lebanese immigrants' shawarma. 'Al pastor' = 'shepherd style.'",
    ),
    (
        "Where does 'cochinita pibil' come from?",
        ["Oaxaca", "Jalisco", "Yucatán", "Puebla"],
        3,
        "Cochinita pibil is Yucatán's signature dish — pork marinated in achiote, wrapped in banana leaves, and slow-roasted underground. It's one of Mexico's most regional and iconic dishes.",
    ),
    (
        "What are 'chilaquiles'?",
        ["A type of enchilada", "Fried tortilla chips simmered in salsa, served for breakfast", "A type of soup", "Grilled meat tacos"],
        2,
        "Chilaquiles are a quintessential Mexican breakfast — fried tortilla chips simmered in green or red salsa, topped with cream, cheese, and often chicken or eggs. The ultimate hangover cure.",
    ),
    (
        "What is the difference between 'elote' and 'esquites'?",
        ["Elote is sweet, esquites are spicy", "Elote is corn on the cob; esquites is corn kernels in a cup", "They are the same thing", "Elote is from Spain, esquites are from Mexico"],
        2,
        "Elote is corn on the cob with mayo, cheese, chili, and lime. Esquites is the same preparation served in a cup with kernels cut off. Both are iconic Mexican street foods.",
    ),
    (
        "What are the three main types of pozole?",
        ["Rojo, verde, and blanco", "Dulce, picante, and agrio", "Grande, mediano, and chico", "Caliente, frío, and tibio"],
        1,
        "Pozole comes in three varieties: rojo (red, with guajillo chiles), verde (green, with tomatillos and green chiles), and blanco (white, from Jalisco, without chile broth). All use hominy as the base.",
    ),
    (
        "What is 'menudo' and when is it traditionally eaten?",
        ["A type of tortilla, eaten at dinner", "A tripe soup, traditionally eaten on Sunday mornings as a hangover cure", "A dessert, eaten after meals", "A type of enchilada, eaten at lunch"],
        2,
        "Menudo is a traditional Mexican tripe soup in red chile broth with hominy. It's legendary as a hangover cure and is traditionally eaten on Sunday mornings. 'El menudo cura el crudo.'",
    ),
    (
        "In Mexican Spanish, which word is used for 'to drive'?",
        ["Conducir", "Manejar", "Pilotar", "Rodar"],
        2,
        "In Mexico, 'manejar' is the standard word for 'to drive.' In Spain and some South American countries, 'conducir' is preferred. 'Manejar' is one of the clearest Mexicanisms.",
    ),
    (
        "What is the Mexican loanword 'checar' borrowed from?",
        ["French 'chèque'", "English 'check'", "Portuguese 'checar'", "Italian 'checare'"],
        2,
        "Checar is borrowed from English 'check.' It's fully integrated into Mexican Spanish: 'Voy a checar' = 'I'm going to check.' Other dialects use 'verificar' or 'revisar,' but Mexicans say 'checar.'",
    ),
    (
        "What does '¿A poco?' mean in Mexican Spanish?",
        ["Very little", "Really? / You don't say!", "A little bit", "Not much"],
        2,
        "¿A poco? is a uniquely Mexican expression meaning 'Really?' or 'You don't say!' It expresses mild disbelief or surprise. '¿A poco en serio?' = 'Really, seriously?'",
    ),
    (
        "Why do Mexicans say 'cafecito' instead of 'café' when offering coffee?",
        ["Because it's a smaller cup", "Because the -ito adds warmth, affection, and politeness to the offer", "Because it's required by grammar", "Because café is too formal"],
        2,
        "In Mexican Spanish, adding -ito to food and drink words adds warmth, affection, and politeness. 'Un cafecito' isn't necessarily small — it's a coffee offered with warmth. The diminutive softens the offer and makes it more inviting.",
    ),
]


if __name__ == "__main__":
    run_exercises(exercises, title="Lección 9: Mexican Dialect & Cultural Nuances")
    choose_translation(pairs, title="Lección 9: Choose the Best Mexican Translation")