import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

from workbook_engine import run_exercises, choose_translation


exercises = [
    {
        "question": 'Translate: "If I had told her the truth, she wouldn\'t have gotten mad."',
        "answer": ["si le hubiera dicho la verdad, no se habría enojado", "si le hubiera dicho la verdad, no se hubiera enojado"],
        "hint": "imperfect subjunctive + conditional perfect; se la would appear if 'it' were the object",
        "explanation": "This combines imperfect subjunctive (si le hubiera dicho) with conditional perfect (no se habría enojado). 'Enojarse' is the Mexican verb for 'to get mad' (not 'enfadarse').",
        "context": "Reflecting on a fight with your girlfriend after you lied.",
    },
    {
        "question": 'Translate: "The teacher wanted us to turn in the homework before we left."',
        "answer": ["la maestra quería que entregáramos la tarea antes de que nos fuéramos", "la profesora quería que entregáramos la tarea antes de que nos fuéramos"],
        "hint": "volitional subjunctive + object reference + adverbial clause with subjunctive",
        "explanation": "Three concepts: (1) quería que → subjunctive (entregáramos), (2) antes de que → always subjunctive (nos fuéramos), (3) 'la tarea' as direct object. In Mexico, 'maestra' is more common than 'profesora' for school.",
        "context": "A Mexican classroom where the teacher sets a deadline.",
    },
    {
        "question": 'Translate: "I hope you (formal) gave it to him."',
        "answer": ["espero que usted se lo haya dado", "espero que se lo haya dado"],
        "hint": "present subjunctive + se lo + perfect tense",
        "explanation": "Espero que triggers present subjunctive. With 'you formal gave it to him,' we need present perfect subjunctive (haya dado) because the action may have already happened. Se lo handles the double pronoun.",
        "context": "Confirming that your colleague handed the documents to the boss.",
    },
    {
        "question": 'Translate: "Even though it rained, we had to go out for tamales."',
        "answer": ["aunque llovió, tuvimos que salir por tamales", "aunque llovió, teníamos que salir por tamales"],
        "hint": "aunque with indicative (completed fact) + irregular verb + Mexican food word",
        "explanation": "When aunque introduces a known/completed fact, use indicative (llovió). Tamales are a quintessential Mexican dish — corn dough stuffed with meat/chile, wrapped in corn husks. In Mexico, you 'sales por tamales' (go out for tamales).",
        "context": "It was raining but nothing stops tamale day.",
    },
    {
        "question": 'Translate: "It\'s possible that they have already told her about the mole."',
        "answer": ["es posible que ya le hayan hablado del mole", "es posible que ya le hayan dicho del mole"],
        "hint": "present subjunctive trigger + perfect subjunctive + Mexican food vocabulary",
        "explanation": "Es posible que → present subjunctive. The action may have already happened, so we use present perfect subjunctive (hayan hablado/hayan dicho). Mole is a complex Mexican sauce with chiles, chocolate, and spices — a cultural icon.",
        "context": "Wondering if someone already told your aunt about the mole at the fiesta.",
    },
    {
        "question": 'Translate: "I doubt that he had put effort into it before he quit." (Mexican: echar ganas)',
        "answer": ["dudo que hubiera echado ganas antes de renunciar", "dudo que haya echado ganas antes de renunciar"],
        "hint": "subjunctive trigger + Mexican idiom + adverbial time clause",
        "explanation": "Dudo que triggers subjunctive. For a past action viewed dubiously, use imperfect or present perfect subjunctive. 'Echar ganas' is the Mexican way to say 'put effort into it.' Renunciar = to quit/resign.",
        "context": "Discussing a coworker who left the job without really trying.",
    },
    {
        "question": 'Translate: "If they had explained it to us, we wouldn\'t have made such a mistake."',
        "answer": ["si nos lo hubieran explicado, no habríamos cometido tal error", "si nos lo hubieran explicado, no hubiéramos cometido tal error"],
        "hint": "imperfect subjunctive + se lo/nos lo + conditional perfect + irregular past participle",
        "explanation": "Si clause in imperfect subjunctive (hubieran explicado). Nos lo = double pronoun. Result clause in conditional perfect (habríamos cometido). 'Cometer un error' is the standard collocation.",
        "context": "Your team made a costly mistake because the instructions weren't clear.",
    },
    {
        "question": 'Translate: "She recommended that we try the pozole, but I didn\'t want to."',
        "answer": ["recomendó que probáramos el pozole, pero no quería", "ella recomendó que probáramos el pozole, pero no quería"],
        "hint": "volitional subjunctive + Mexican food + imperfect for ongoing state",
        "explanation": "Recomendó que → subjunctive (probáramos). Pozole is a traditional Mexican soup with hominy and pork/chicken. 'No quería' uses imperfect because it describes an ongoing state of not wanting.",
        "context": "Your friend suggested pozole but you weren't in the mood.",
    },
    {
        "question": 'Translate: "Unless they send it to us right away (luego luego), we won\'t have time."',
        "answer": ["a menos que nos lo envíen luego luego, no tendremos tiempo", "a menos que nos lo manden luego luego, no tendremos tiempo"],
        "hint": "adverbial clause with subjunctive + nos lo + Mexican expression",
        "explanation": "A menos que → always subjunctive (envíen/manden). Nos lo = double pronoun. Luego luego is the Mexican reduplication meaning 'right away' — not just 'luego' which means 'later.'",
        "context": "Waiting for a shipment at work in Mexico City.",
    },
    {
        "question": 'Translate: "I think it seems to me that they gave it to him." (Mexican: se me hace que)',
        "answer": ["se me hace que se lo dieron", "se me hace que se lo entregaron"],
        "hint": "Mexican hedging expression + se lo double pronoun",
        "explanation": "Se me hace que is the Mexican way to say 'I think/I have the impression that.' Combined with se lo dieron (they gave it to him/her), we get two 'se's — one from the hedging expression, one from the pronoun transformation.",
        "context": "You vaguely remember seeing someone hand something to your brother.",
    },
    {
        "question": 'Translate: "Whatever you (informal) do, don\'t tell her about the enchiladas!"',
        "answer": ["lo que hagas, no le digas de las enchiladas", "lo que sea que hagas, no le digas sobre las enchiladas"],
        "hint": "indefinite/relative clause with subjunctive + negative command + Mexican food",
        "explanation": "Lo que hagas → subjunctive for indefinite antecedent. No le digas → negative tú command. Enchiladas are tortillas rolled around filling and covered in chile sauce — a staple of Mexican cuisine.",
        "context": "Your sister made amazing enchiladas and you want them all for yourself.",
    },
    {
        "question": 'Translate: "It\'s unfair (gacho) that they haven\'t paid us yet."',
        "answer": ["está gacho que no nos hayan pagado todavía", "está gacho que aún no nos hayan pagado", "qué gacho que no nos hayan pagado todavía", "qué gacho que aún no nos hayan pagado"],
        "hint": "Mexican slang + present perfect subjunctive + nos",
        "explanation": "Gacho = unfair/bad/uncool, very Mexican. Está gacho que / qué gacho que → subjunctive. No nos hayan pagado uses present perfect subjunctive for a not-yet-completed action.",
        "context": "Complaining about late pay at a Mexican workplace.",
    },
    {
        "question": 'Translate: "He denied that he had broken them (the dishes) on purpose."',
        "answer": ["negó que las hubiera roto a propósito", "él negó que las hubiera roto a propósito"],
        "hint": "verb of denial + imperfect subjunctive + las (feminine plural object)",
        "explanation": "Negar que → subjunctive. Since the breaking is past relative to the denial, use imperfect subjunctive (hubiera roto). Las replaces los platos (feminine plural). Roto is an irregular past participle of romper.",
        "context": "Someone broke the dishes and won't admit it was intentional.",
    },
    {
        "question": 'Translate: "We were surprised that she had already opened them (the gifts)."',
        "answer": ["nos sorprendió que ya las hubiera abierto", "nos sorprendió que las hubiera abierto ya"],
        "hint": "emotion trigger + imperfect subjunctive + irregular past participle (abrir → abierto)",
        "explanation": "Nos sorprendió que → subjunctive. The opening happened before the surprise, so imperfect subjunctive (hubiera abierto). Las = los regalos (gifts, masculine in this context — but if feminine objects, las). Abierto is the irregular participle of abrir.",
        "context": "She opened the gifts before the birthday party even started.",
    },
    {
        "question": 'Translate: "Wow (¡híjole!), I hope they bring us the tacos soon."',
        "answer": ["¡híjole! espero que nos traigan los tacos pronto", "¡híjole! espero que nos traigan los tacos luego luego"],
        "hint": "Mexican exclamation + present subjunctive + nos",
        "explanation": "Híjole is a uniquely Mexican exclamation of surprise/emphasis. Espero que → present subjunctive (traigan). Nos = to us. Tacos = iconic Mexican food. You could even say 'luego luego' instead of 'pronto' for extra Mexican flavor.",
        "context": "Waiting for food at a taquería in Mexico City.",
    },
    {
        "question": "Translate: \"I want you to give it to her before you leave\" (Mexican: wants + subjunctive + double pronoun)",
        "answer": ["quiero que se lo des antes de que te vayas", "quiero que se lo des antes de irte"],
        "hint": "volitional subjunctive + se lo + adverbial subjunctive clause",
        "explanation": "Quiero que → subjunctive (des). Se lo = 'it to her' (le lo → se lo). Antes de que → always subjunctive (te vayas). Three grammar points in one natural sentence. This is very common in everyday Mexican Spanish.",
        "context": "Telling your brother to hand the keys to Mom before he leaves.",
    },
    {
        "question": "Translate: \"If I were you, I'd tell him the truth right away (luego luego)\" (Mexican: imperfect subjunctive + conditional + Mexican expression)",
        "answer": ["si yo fuera tú, le diría la verdad luego luego", "si yo fuera tú, le diría la verdad luego luego"],
        "hint": "si + imperfect subjunctive → conditional + le (to him) + Mexican reduplication",
        "explanation": "Si yo fuera tú (imperfect subjunctive) → le diría (conditional, 'to him') + luego luego (Mexican 'right away'). The subjunctive-conditional pair plus the Mexican expression 'luego luego' creates a natural, idiomatic sentence.",
        "context": "Giving advice to a friend who's hesitating about telling the truth.",
    },
    {
        "question": "Translate: \"They should have given it to us\" (se lo + perfect tenses)",
        "answer": ["deberían habérnoslo dado", "ellos deberían habérnoslo dado"],
        "hint": "conditional perfect + nos lo with double pronoun attachment + enclitic ordering",
        "explanation": "Deberían haber + nos lo attached → habérnoslo dado. When two pronouns attach to an infinitive, the indirect goes first (nos), then direct (lo). The accent shifts to maintain stress: ha-BER-nos-lo DA-do.",
        "context": "Complaining that your colleagues didn't send the report to your team.",
    },
    {
        "question": "Translate: \"It bothers me that she told him about it\" (emotion + subjunctive + pronoun reference)",
        "answer": ["me molesta que le haya dicho sobre eso", "me molesta que le haya hablado de eso"],
        "hint": "emotion trigger → present perfect subjunctive + le (to him)",
        "explanation": "Me molesta que → subjunctive (haya dicho). Le = 'to him' (indirect object). The 'it' of 'about it' becomes 'sobre eso.' This combines emotion-triggered subjunctive with pronoun reference — a very common pattern.",
        "context": "You're annoyed that your coworker shared information with the boss.",
    },
    {
        "question": "Translate: \"I hope you put some effort into it (échale ganas)\" (Mexican idiom + subjunctive)",
        "answer": ["espero que le eches ganas", "espero que le eches ganas a esto"],
        "hint": "espero que → subjunctive + Mexican idiom with le",
        "explanation": "Espero que → subjunctive (le eches). Échale ganas is the Mexican idiom for 'put effort into it' — in subjunctive, the tú form changes to le eches ganas. The le is the indirect object pronoun referencing 'it.'",
        "context": "Encouraging a friend before a big job interview.",
    },
    {
        "question": "Translate: \"Even if they told me it's cool (chido), I wouldn't go\" (concessive subjunctive + Mexican expression)",
        "answer": ["aunque me dijeran que está chido, no iría", "aunque me digan que está chido, no iría"],
        "hint": "aunque + subjunctive (hypothetical) + chido + conditional",
        "explanation": "Aunque with subjunctive (dijeran/digan) means 'even if' — a hypothetical concession. Chido is the Mexican word for 'cool.' The conditional (no iría) follows from the hypothetical condition. Three concepts combined naturally.",
        "context": "Your friends keep saying the party will be great but you refuse to go.",
    },
    {
        "question": "Translate: \"If she had explained it to us, we would have understood\" (past perfect subjunctive + double pronouns)",
        "answer": ["si nos lo hubiera explicado, lo habríamos entendido", "si nos lo hubiera explicado, habríamos entendido"],
        "hint": "si + past perfect subjunctive + nos lo + conditional perfect",
        "explanation": "Si nos lo hubiera explicado: si clause with imperfect subjunctive (hubiera explicado), nos lo = double pronoun ('it to us'). Result clause in conditional perfect (habríamos entendido). This is the classic third conditional with pronoun stacking.",
        "context": "Your team didn't understand the project because the manager didn't explain it to you.",
    },
    {
        "question": "Translate: \"Se me hace que she would have gotten mad if you had told her\" (Mexican hedging + conditional perfect)",
        "answer": ["se me hace que se habría enojado si le hubieras dicho", "se me hace que se hubiera enojado si le hubieras dicho"],
        "hint": "se me hace que (Mexican hedging) + conditional perfect + si imperfect subjunctive",
        "explanation": "Se me hace que = Mexican hedging 'I think/I have the impression that.' Se habría enojado = conditional perfect (she would have gotten mad). Si le hubieras dicho = si clause imperfect subjunctive. Note: se me hace and se habría — two different 'se's.",
        "context": "You're guessing about how someone would have reacted to bad news.",
    },
    {
        "question": "Translate: \"Unless they send it to him right away (luego luego), it won't arrive on time\" (adverbial clause + se lo + Mexican expression)",
        "answer": ["a menos que se lo envíen luego luego, no llegará a tiempo", "a menos que se lo manden luego luego, no va a llegar a tiempo"],
        "hint": "a menos que → subjunctive + se lo + luego luego + future",
        "explanation": "A menos que → always subjunctive (envíen/manden). Se lo = 'it to him/her' (le lo → se lo). Luego luego = Mexican 'right away.' The main clause uses future (no llegará a tiempo). Four concepts in one sentence.",
        "context": "Discussing whether a package will arrive on time for the deadline.",
    },
    {
        "question": "Translate: \"It's unfair (gacho) that they haven't paid us yet, right?\" (Mexican slang + subjunctive + tag question)",
        "answer": ["está gacho que no nos hayan pagado todavía, ¿verdad?", "está gacho que aún no nos hayan pagado, ¿no?"],
        "hint": "gacho (Mexican slang) + present perfect subjunctive + nos + tag question",
        "explanation": "Está gacho que → subjunctive (hayan pagado). Nos = 'to us.' Todavía/aún = 'yet.' ¿Verdad? or ¿no? = tag questions common in Mexican Spanish. The slang 'gacho' adds Mexican flavor to a complex grammar structure.",
        "context": "Complaining to a coworker about late wages at a Mexican workplace.",
    },
    {
        "question": "Translate: \"She denied that she had given them (the documents) to him\" (verb of denial + imperfect subjunctive + se las)",
        "answer": ["negó que se las hubiera dado", "ella negó que se las hubiera dado"],
        "hint": "negar que → subjunctive + se las (los documentos a él) + imperfect subjunctive",
        "explanation": "Negó que → subjunctive. Since the giving happened before the denial, use imperfect subjunctive (hubiera dado). Se las = 'them (feminine) to him' (los documentos a él: le las → se las). Verb of denial always triggers subjunctive.",
        "context": "A colleague claimed she didn't hand over the files, but you're not sure.",
    },
    {
        "question": "Translate: \"Wow (¡híjole!), I doubt they'll send it to her on time\" (Mexican exclamation + doubt trigger + pronouns)",
        "answer": ["¡híjole! dudo que se lo envíen a tiempo", "¡híjole! dudo que se lo manden a tiempo"],
        "hint": "híjole (Mexican exclamation) + dudo que → subjunctive + se lo",
        "explanation": "Híjole is a uniquely Mexican exclamation of surprise. Dudo que → subjunctive (envíen/manden). Se lo = 'it to her' (le lo → se lo). Combining a cultural expression with subjunctive triggers and pronoun stacking.",
        "context": "You're skeptical that the delivery will arrive on time.",
    },
    {
        "question": "Translate: \"The teacher insisted that we hand it in (the assignment) before leaving\" (volitional + se lo + adverbial clause)",
        "answer": ["la maestra insistió en que se lo entregáramos antes de irnos", "la maestra insistió en que se lo entregáramos antes de que nos fuéramos"],
        "hint": "insistió en que → subjunctive + se lo + antes de + infinitive/subjunctive",
        "explanation": "Insistió en que → subjunctive (entregáramos). Se lo = 'it to him/her' (le lo → se lo — to the teacher). Antes de irnos or antes de que nos fuéramos (both valid). 'Maestra' is the common Mexican word for 'teacher.'",
        "context": "The teacher was very clear about the deadline for the essay.",
    },
    {
        "question": "Translate: \"It's possible that they've already told her about the quinceañera\" (possibility trigger + perfect subjunctive + Mexican culture)",
        "answer": ["es posible que ya le hayan hablado de la quinceañera", "es posible que ya le hayan dicho de la quinceañera"],
        "hint": "es posible que → present perfect subjunctive + le + quinceañera",
        "explanation": "Es posible que → subjunctive. For a possibly completed action, use present perfect subjunctive (hayan hablado/hayan dicho). Le = 'to her.' Quinceañera is the Mexican celebration of a girl's 15th birthday — a major cultural event.",
        "context": "Wondering if someone already informed your cousin about the upcoming party.",
    },
    {
        "question": "Translate: \"I hope you (formal) explained it to them clearly\" (espero que + perfect subjunctive + se lo)",
        "answer": ["espero que se lo haya explicado claramente", "espero que usted se lo haya explicado claramente"],
        "hint": "espero que → present perfect subjunctive + se lo (it to them)",
        "explanation": "Espero que → subjunctive. For a possibly completed action, use present perfect subjunctive (haya explicado). Se lo = 'it to them' (les lo → se lo). Claramente = adverb. Formal 'usted' is implied.",
        "context": "Hoping your lawyer explained the contract terms to the clients.",
    },
    {
        "question": "Translate: \"Whenever you (informal) want, I'll make you a little coffee (un cafecito)\" (indefinite antecedent + subjunctive + Mexican diminutive)",
        "answer": ["cuando quieras, te preparo un cafecito", "cuando quieras, te hago un cafecito"],
        "hint": "cuando + subjunctive (indefinite) + te + Mexican diminutive for warmth",
        "explanation": "Cuando quieras → subjunctive for indefinite future reference ('whenever you want'). Te = 'for you' (indirect object). Cafecito = diminutive of café, adding warmth and affection, not just indicating small size. A very natural Mexican sentence.",
        "context": "Welcoming a friend to your home in Mexico.",
    },
    {
        "question": "Translate: \"I'm surprised that she gave them (the tickets) to him so quickly\" (emotion + perfect subjunctive + se los)",
        "answer": ["me sorprende que se los haya dado tan rápido", "me sorprende que se los haya dado tan luego luego"],
        "hint": "emotion trigger → present perfect subjunctive + se los (los boletos a él)",
        "explanation": "Me sorprende que → subjunctive (haya dado). Se los = 'them (masculine plural) to him/her' (se replaces le/les before lo/la/los/las). The action may have already happened, so present perfect subjunctive.",
        "context": "You're shocked that your sister already gave your brother the concert tickets.",
    },
    {
        "question": "Translate: \"No way (¡no manches!), it's incredible that they gave it to her\" (Mexican exclamation + emotion trigger + se lo)",
        "answer": ["¡no manches! es increíble que se lo hayan dado", "¡no manches! está increíble que se lo hayan dado"],
        "hint": "no manches (polite Mexican disbelief) + es increíble que → subjunctive + se lo",
        "explanation": "¡No manches! is the polite Mexican exclamation of disbelief (the vulgar version is ¡no mames!). Es increíble que → subjunctive (hayan dado). Se lo = 'it to her' (le lo → se lo). Combining slang with complex grammar = natural Mexican Spanish.",
        "context": "You can't believe they gave the promotion to someone else.",
    },
    {
        "question": "Translate: \"I want you (informal) to send it to me right away (luego luego)\" (volitional + me lo + Mexican expression)",
        "answer": ["quiero que me lo envíes luego luego", "quiero que me lo mandes luego luego"],
        "hint": "quiero que → subjunctive + me lo (it to me) + luego luego",
        "explanation": "Quiero que → subjunctive (envíes/mandes). Me lo = 'it to me' (me before lo). Luego luego = Mexican reduplication meaning 'right away.' This is a very natural, everyday Mexican sentence combining grammar and slang.",
        "context": "You need your coworker to send you the document immediately.",
    },
    {
        "question": "Translate: \"It's great (¡qué padre!) that you gave it to them\" (Mexican expression + emotion trigger + se lo)",
        "answer": ["¡qué padre que se lo hayas dado!", "¡qué padre que se lo hayas regalado!"],
        "hint": "qué padre (Mexican 'how cool') → subjunctive + se lo (it to them)",
        "explanation": "¡Qué padre! = Mexican 'How cool!' Emotion trigger → present subjunctive (hayas dado). Se lo = 'it to them.' Note: subjunctive because it's an emotional reaction to an action. Very natural Mexican Spanish combining slang and grammar.",
        "context": "Your friend gave a gift to their family and you think it's awesome.",
    },
    {
        "question": "Translate: \"I doubt that they had put effort into it (echado ganas) before quitting\" (doubt + Mexican idiom + past action)",
        "answer": ["dudo que hayan echado ganas antes de renunciar", "dudo que hubieran echado ganas antes de renunciar"],
        "hint": "dudo que → subjunctive + echar ganas (Mexican idiom) + antes de",
        "explanation": "Dudo que → subjunctive. For a past action viewed with doubt, use present perfect subjunctive (hayan echado) or imperfect subjunctive (hubieran echado). Echar ganas = Mexican 'to put effort into it.' Renunciar = to quit/resign.",
        "context": "You're skeptical that your former colleague ever really tried before leaving.",
    },
    {
        "question": "Translate: \"As soon as you (informal) give it to her, let me know\" (temporal clause + se la + Mexican expression)",
        "answer": ["tan pronto como se lo des, avísame", "en cuanto se lo des, avísame", "luego luego que se lo des, avísame"],
        "hint": "temporal clause → subjunctive + se la (it to her) + command",
        "explanation": "Tan pronto como / en cuanto → subjunctive (des) when referring to future action. Se la = 'it to her' (le la → se la). Avísame = tú command. 'Luego luego que' is a Mexican alternative for 'as soon as.' Natural, everyday sentence.",
        "context": "You need to know when your friend hands the package to your mom.",
    },
    {
        "question": "Translate: \"It bothers me that they didn't give us (any) lana (money)\" (emotion + subjunctive + Mexican slang for money)",
        "answer": ["me molesta que no nos hayan dado lana", "me molesta que no nos dieran lana"],
        "hint": "emotion trigger → subjunctive + nos + lana (Mexican slang for money)",
        "explanation": "Me molesta que → subjunctive (hayan dado or dieran). Nos = 'to us.' Lana = Mexican slang for 'money' (literally 'wool'). Combining an emotion trigger with subjunctive and Mexican slang creates a natural, colloquial sentence.",
        "context": "You're annoyed that your boss hasn't paid you.",
    },
    {
        "question": "Translate: \"We were happy that you (informal) had made us a little coffee (un cafecito)\" (emotion + imperfect subjunctive + Mexican diminutive + nos)",
        "answer": ["nos alegró que nos hubieras hecho un cafecito", "estábamos contentos de que nos hubieras preparado un cafecito"],
        "hint": "emotion trigger → imperfect subjunctive + nos + Mexican diminutive",
        "explanation": "Nos alegró que → subjunctive. Since the happiness is about a past action, use imperfect subjunctive (hubieras hecho/preparado). Nos = 'for us.' Cafecito = Mexican diminutive adding warmth. The combination of emotion trigger, past subjunctive, and diminutive is very natural.",
        "context": "Your friend made you coffee and you're genuinely touched.",
    },
    {
        "question": "Translate: \"It's unfair (gacho) that they gave the chamba (job) to someone else\" (Mexican slang + emotion trigger + subjunctive)",
        "answer": ["está gacho que le hayan dado la chamba a alguien más", "está gacho que le dieran la chamba a otro"],
        "hint": "gacho (Mexican slang for unfair) + emotion trigger + le + chamba (Mexican slang for job)",
        "explanation": "Está gacho que → subjunctive (hayan dado or dieran). Le = 'to him/her.' Chamba = Mexican slang for 'job/work.' This sentence combines two Mexican slang words with subjunctive grammar — very natural Mexican Spanish.",
        "context": "You find out they hired someone else for the position you wanted.",
    },
    {
        "question": "Translate: \"Maybe they already gave it to the güero\" (possibility + perfect subjunctive + Mexican word for light-skinned person)",
        "answer": ["quizás ya se lo hayan dado al güero", "tal vez ya se lo hayan dado al güero", "a lo mejor ya se lo dieron al güero"],
        "hint": "quizás/tal vez → subjunctive + se lo + güero (Mexican for light-skinned person)",
        "explanation": "Quizás/tal vez with a possibly completed past action can trigger present perfect subjunctive (hayan dado). Se lo = 'it to him' (le lo → se lo). Güero = Mexican word for a light-skinned person. Note: 'a lo mejor' takes indicative, not subjunctive.",
        "context": "You're wondering if they already gave the package to your light-skinned friend.",
    },
    {
        "question": "Translate: \"It's important that you (formal) send them (the documents) to us right away (luego luego)\" (impersonal expression + nos los + Mexican expression)",
        "answer": ["es importante que nos los envíe luego luego", "es importante que nos los mande luego luego"],
        "hint": "es importante que → subjunctive (usted form) + nos los + luego luego",
        "explanation": "Es importante que → subjunctive. Since it's formal 'usted,' use 'envíe/mande.' Nos los = 'them to us' (nos before los). Luego luego = Mexican 'right away.' Combining formal register with Mexican slang creates a natural workplace sentence.",
        "context": "Instructing a colleague to send the documents to your team immediately.",
    },
    {
        "question": "Translate: \"I don't think they gave it to the escuincle (brat)\" (negation + subjunctive + Mexican slang for brat)",
        "answer": ["no creo que le hayan dado al escuincle", "no creo que le dieran al escuincle"],
        "hint": "no creo que → subjunctive + le + escuincle (Mexican slang for brat/punk kid)",
        "explanation": "No creo que → subjunctive (hayan dado or dieran). Le = 'to him/her.' Escuincle = Mexican slang for 'brat' or 'pesky kid' (from Nahuatl). This combines negation-triggered subjunctive with Mexican vocabulary.",
        "context": "You doubt that anyone gave a gift to the annoying kid next door.",
    },
    {
        "question": "Translate: \"Whatever you (informal) do, don't give it to the ruco (old man)!\" (indefinite antecedent + negative command + se lo + Mexican slang)",
        "answer": ["lo que hagas, ¡no se lo des al ruco!", "lo que sea que hagas, ¡no se lo des al ruco!"],
        "hint": "lo que + subjunctive (indefinite) + negative tú command + se lo + ruco (Mexican for old man)",
        "explanation": "Lo que hagas → subjunctive (indefinite antecedent, 'whatever you do'). No se lo des → negative tú command (no + se lo + des). Se lo = 'it to him' (le lo → se lo). Ruco = Mexican slang for 'old dude.' Three grammar concepts + slang.",
        "context": "Warning your friend not to give the old man the thing he's asking for.",
    },
    {
        "question": "Translate: \"It's possible that they haven't sent us the pozole recipe yet\" (possibility + perfect subjunctive + Mexican food)",
        "answer": ["es posible que aún no nos hayan enviado la receta del pozole", "es posible que no nos hayan mandado la receta del pozole todavía"],
        "hint": "es posible que → present perfect subjunctive + nos + pozole (Mexican soup)",
        "explanation": "Es posible que → subjunctive. For a possibly not-yet-completed action, use present perfect subjunctive (hayan enviado/manden). Nos = 'to us.' Pozole = traditional Mexican soup with hominy and pork/chicken. Natural grammar + cultural vocabulary.",
        "context": "Waiting for your aunt to send the family's pozole recipe.",
    },
    {
        "question": "Translate: \"Se me hace that they gave the chilaquiles recipe to her\" (Mexican hedging + se lo + Mexican food)",
        "answer": ["se me hace que le dieron la receta de los chilaquiles", "se me hace que le hayan dado la receta de los chilaquiles"],
        "hint": "se me hace que (Mexican hedging) + le + chilaquiles (Mexican breakfast dish)",
        "explanation": "Se me hace que = Mexican hedging 'I think/I have the impression that.' Le = 'to her.' Chilaquiles = fried tortilla chips in salsa, a classic Mexican breakfast. This combines Mexican hedging, pronoun reference, and food vocabulary naturally.",
        "context": "You vaguely remember someone sharing the chilaquiles recipe with your aunt.",
    },
    {
        "question": "Translate: \"She recommended that we try the mole, but I didn't want to\" (volitional + subjunctive + Mexican food + contrast)",
        "answer": ["recomendó que probáramos el mole, pero no quería", "ella recomendó que probáramos el mole, pero yo no quería"],
        "hint": "recomendó que → subjunctive + mole (Mexican sauce) + pero + imperfect",
        "explanation": "Recomendó que → subjunctive (probáramos). Mole = complex Mexican sauce with chiles and chocolate. Pero no quería uses imperfect (ongoing state of not wanting). Three concepts: volitional subjunctive, cultural vocabulary, and past tense contrast.",
        "context": "Your friend recommended mole at a restaurant but you weren't in the mood.",
    },
    {
        "question": "Translate: \"It surprises me that they gave the carnitas recipe to him (the compa)\" (emotion + subjunctive + se la + Mexican slang)",
        "answer": ["me sorprende que le hayan dado la receta de carnitas al compa", "me sorprende que le dieran la receta de carnitas al compa"],
        "hint": "emotion trigger → subjunctive + le + carnitas (Mexican pork) + compa (Mexican buddy)",
        "explanation": "Me sorprende que → subjunctive (hayan dado/dieran). Le = 'to him.' Carnitas = Michoacán's slow-fried pork. Compa = Mexican slang for 'buddy' (short for compadre). Emotion trigger + subjunctive + cultural vocabulary.",
        "context": "You're surprised they shared the family carnitas recipe with your buddy.",
    },
    {
        "question": "Translate: \"I insist that you (formal) give it to me before the quinceañera\" (volitional + se me + Mexican culture)",
        "answer": ["insisto en que me lo dé antes de la quinceañera", "insisto en que me lo entregue antes de la quinceañera"],
        "hint": "insisto en que → subjunctive (usted) + me lo + quinceañera (Mexican celebration)",
        "explanation": "Insisto en que → subjunctive. Usted form: dé/entregue. Me lo = 'it to me.' Quinceañera = the Mexican celebration of a girl's 15th birthday, a major cultural event. Volitional subjunctive + double pronoun + cultural reference.",
        "context": "You need the dress before your cousin's quinceañera celebration.",
    },
    {
        "question": "Translate: \"It's a shame (¡qué gacho!) that they didn't tell us about the Día de los Muertos\" (Mexican expression + emotion + subjunctive)",
        "answer": ["¡qué gacho que no nos hayan dicho del Día de los Muertos!", "¡qué gacho que no nos dijeran del Día de los Muertos!"],
        "hint": "¡qué gacho! (Mexican 'how unfair!') → subjunctive + nos + Día de los Muertos",
        "explanation": "¡Qué gacho! = Mexican 'How unfair!' or 'That sucks!' Emotion trigger → subjunctive (hayan dicho/dijeran). Nos = 'to us.' Día de los Muertos = Day of the Dead, Mexico's sacred celebration honoring deceased loved ones.",
        "context": "Your friends went to a Day of the Dead event without inviting you.",
    },
    {
        "question": "Translate: \"So that they'll give us the atole, we need to arrive early\" (purpose clause + nos lo + Mexican drink)",
        "answer": ["para que nos den el atole, necesitamos llegar temprano", "para que nos sirvan el atole, tenemos que llegar temprano"],
        "hint": "para que → subjunctive + nos (to us) + atole (Mexican warm corn drink)",
        "explanation": "Para que → always subjunctive (den/sirvan). Nos = 'to us.' Atole = traditional warm Mexican drink made from corn dough, often served during Day of the Dead and cold mornings. Purpose clause + pronoun + cultural vocabulary.",
        "context": "You want to get the atole at the Day of the Dead celebration before it runs out.",
    },
    {
        "question": "Translate: \"I'm afraid they gave the birria recipe to someone else\" (fear trigger + subjunctive + Mexican food)",
        "answer": ["tengo miedo de que le hayan dado la receta de birria a alguien más", "me da miedo que le hayan dado la receta de birria a otro"],
        "hint": "tengo miedo de que → subjunctive + le + birria (Jalisco slow-cooked meat)",
        "explanation": "Tengo miedo de que → subjunctive (hayan dado). Le = 'to him/her.' Birria = Jalisco's slow-cooked meat (traditionally goat) in chile broth, now famous worldwide as birria tacos. Fear trigger + subjunctive + cultural vocabulary.",
        "context": "You're worried the family's birria recipe was shared with someone outside the family.",
    },
    {
        "question": "Translate: \"It's necessary that you (informal) give it to the chamaco (kid)\" (impersonal expression + se lo + Mexican slang)",
        "answer": ["es necesario que se lo des al chamaco", "es necesario que se lo des al chamaco"],
        "hint": "es necesario que → subjunctive + se lo (it to him) + chamaco (Mexican for kid)",
        "explanation": "Es necesario que → subjunctive (des). Se lo = 'it to him' (le lo → se lo). Chamaco = Mexican slang for 'kid.' The child is 'him' so we use le → se before lo. Impersonal expression + pronoun stacking + Mexican slang.",
        "context": "You need to give the package to the kid waiting outside.",
    },
    {
        "question": "Translate: \"I hope they served us the huevos rancheros while they were hot\" (espero que + imperfect subjunctive + Mexican food)",
        "answer": ["espero que nos hayan servido los huevos rancheros calientitos", "espero que nos sirvieran los huevos rancheros calientitos"],
        "hint": "espero que → subjunctive + nos + huevos rancheros + calientitos (diminutive)",
        "explanation": "Espero que → subjunctive (hayan servido/sirvieran). Nos = 'to us.' Huevos rancheros = fried eggs on tortillas with salsa. Calientitos = diminutive of caliente, adding warmth and emphasis ('nice and hot'). Subjunctive + pronoun + food + diminutive.",
        "context": "Hoping the breakfast at the fondita was served hot.",
    },
    {
        "question": "Translate: \"It's a shame (¡qué gacho!) that they gave the good chamba to someone else\" (Mexican slang + emotion trigger + subjunctive + Mexican slang)",
        "answer": ["¡qué gacho que le hayan dado la buena chamba a otro", "¡qué gacho que le dieran la buena chamba a alguien más"],
        "hint": "¡qué gacho! (Mexican 'how unfair!') + emotion trigger + le + chamba (Mexican slang for job)",
        "explanation": "¡Qué gacho! = Mexican 'How unfair!' or 'That sucks!' Emotion trigger → subjunctive (hayan dado/dieran). Le = 'to him/her.' Chamba = Mexican slang for 'job/work.' Double slang + subjunctive grammar in a natural Mexican sentence.",
        "context": "You find out the good position went to an outsider instead of a local.",
    },
    {
        "question": "Translate: \"It's incredible that they charged us so much lana (money) for the tacos\" (emotion + nos + Mexican slang)",
        "answer": ["es increíble que nos hayan cobrado tanta lana por los tacos", "es increíble que nos cobraran tanta lana por los tacos"],
        "hint": "es increíble que → subjunctive + nos (to us) + lana (Mexican slang for money)",
        "explanation": "Es increíble que → subjunctive (hayan cobrado/cobraran). Nos = 'to us.' Lana = Mexican slang for 'money.' Cobrar = to charge. Combining emotion-triggered subjunctive with Mexican slang for money creates a very natural sentence.",
        "context": "You're shocked at how much the tourist trap charged for street tacos.",
    },
    {
        "question": "Translate: \"I hope they gave the little town (pueblito) a chance\" (espero que + subjunctive + Mexican diminutive)",
        "answer": ["espero que le hayan dado una oportunidad al pueblito", "espero que le dieran una oportunidad al pueblito"],
        "hint": "espero que → present perfect subjunctive + le + pueblito (Mexican diminutive for town)",
        "explanation": "Espero que → subjunctive (hayan dado/dieran). Le = 'to it' (to the town). Pueblito = Mexican diminutive of 'pueblo,' adding charm and affection. The diminutive doesn't make it a 'small town' necessarily — it adds warmth.",
        "context": "Hoping the government gave your hometown a fair chance at development funding.",
    },
    {
        "question": "Translate: \"Perhaps they already sent us the pan dulce for the merienda\" (possibility + perfect subjunctive + Mexican food)",
        "answer": ["quizás ya nos hayan enviado el pan dulce para la merienda", "tal vez ya nos hayan mandado el pan dulce para la merienda"],
        "hint": "quizás/tal vez → present perfect subjunctive + nos + pan dulce (Mexican sweet bread)",
        "explanation": "Quizás/tal vez with possibly completed action → present perfect subjunctive (hayan enviado/mandado). Nos = 'to us.' Pan dulce = Mexican sweet bread (conchas, bolillos, etc.). Merienda = afternoon snack. Combines possibility, subjunctive, and food culture.",
        "context": "Wondering if the bakery already delivered the sweet bread for the afternoon snack.",
    },
    {
        "question": "Translate: \"It's necessary that they explain it to us (the birria recipe) step by step\" (impersonal expression + nos lo + Mexican food)",
        "answer": ["es necesario que nos lo expliquen paso a paso", "es necesario que nos lo expliquen poco a poco"],
        "hint": "es necesario que → subjunctive + nos lo (it to us) + birria (Jalisco slow-cooked meat)",
        "explanation": "Es necesario que → subjunctive (expliquen). Nos lo = 'it to us.' Paso a paso = 'step by step.' Birria is Jalisco's slow-cooked meat in chile broth. Impersonal expression + double pronoun + cultural vocabulary.",
        "context": "You need your mother-in-law to explain the birria recipe clearly.",
    },
    {
        "question": "Translate: \"It's surprising that they sent us the tinga recipe so quickly (luego luego)\" (emotion + nos + Mexican expression + Mexican food)",
        "answer": ["es sorprendente que nos hayan enviado la receta de tinga luego luego", "es sorprendente que nos mandaran la receta de tinga luego luego"],
        "hint": "es sorprendente que → subjunctive + nos + luego luego (Mexican 'right away') + tinga (Mexican shredded chicken)",
        "explanation": "Es sorprendente que → subjunctive (hayan enviado/mandaran). Nos = 'to us.' Luego luego = Mexican reduplication meaning 'right away.' Tinga = Mexican shredded chicken in tomato-chile sauce. Emotion trigger + pronoun + Mexican expression + food vocabulary.",
        "context": "You're surprised the aunt sent the tinga recipe back so quickly.",
    },
]


pairs = [
    (
        "How do you say 'If I had told her the truth, she wouldn't have gotten mad' in Mexican Spanish?",
        ["Si le dije la verdad, no se enojó", "Si le hubiera dicho la verdad, no se habría enojado", "Si le diría la verdad, no se enojara", "Si le hubiera dicho la verdad, no se enoja"],
        2,
        "Si + imperfect subjunctive (hubiera dicho) → conditional perfect (habría enojado). 'Enojarse' is the Mexican verb for getting mad.",
    ),
    (
        "Which combines se lo + volitional subjunctive + Mexican food vocabulary?",
        ["Espero que se lo coma el taco", "La abuela quiere que se lo comamos el mole", "Espero que se lo coman el pozole", "Quiero que se lo prepares el tamal"],
        4,
        "Quiero que → subjunctive. Se lo prepares (you prepare it for him/her) combines se lo with subjunctive. El tamal = Mexican food. The other options have article agreement issues.",
    ),
    (
        "What does 'Se me hace que se lo dieron' mean?",
        ["It seems to me that they gave it to him/her", "They gave themselves to me", "I did it myself for them", "It made itself happen"],
        1,
        "Two different 'se's: 'se me hace que' = Mexican hedging (it seems to me that), 'se lo dieron' = they gave it to him/her (le lo → se lo).",
    ),
    (
        "Which is the correct translation of 'Unless they send it to us right away, we won't finish'?",
        ["A menos que nos lo envíen luego luego, no terminaremos", "A menos que nos lo envían luego, no terminamos", "A menos que se lo envíen luego luego, no terminaremos", "A menos que nos lo envíen luego, no terminaremos"],
        1,
        "A menos que → subjunctive (envíen). Nos lo = to us it. Luego luego = Mexican 'right away.' Future in main clause: no terminaremos.",
    ),
    (
        "In Mexican Spanish, which sentence correctly uses the subjunctive with a Mexican expression?",
        ["Está gacho que no nos paguen", "Está gacho que no nos pagan", "Es gacho que no nos pagaban", "Está gacho que no pagamos"],
        1,
        "Está gacho que → subjunctive (paguen). Gacho = unfair/uncool (Mexican). The subjunctive is required after expressions of evaluation/emotion.",
    ),
    (
        "Which correctly combines imperfect subjunctive + conditional perfect + double pronoun?",
        ["Si se lo hubiera dicho, no habría hecho eso", "Si se lo diría, no hizo eso", "Si se lo dijo, no hará eso", "Si le lo hubiera dicho, no habría hecho eso"],
        1,
        "Si + imperfect subjunctive (hubiera dicho) → conditional perfect (habría hecho). Se lo = double pronoun (le lo → se lo). Option 4 has the invalid 'le lo' combination.",
    ),
    (
        "What is the Mexican way to say 'I think they already gave it to her'?",
        ["Creo que se lo dieron", "Se me hace que ya se lo dieron", "Pienso que le lo dieron", "Me parece que se lo dieron ya"],
        2,
        "Se me hace que is the distinctly Mexican way to hedge 'I think that...' Adding ya = already. Se lo dieron = they gave it to her.",
    ),
    (
        "Which sentence correctly uses the present perfect subjunctive with a double pronoun?",
        ["Dudo que se lo hayan dado", "Dudo que se lo dieron", "Dudo que se lo habían dado", "Dudo que se lo dan"],
        1,
        "Dudo que → subjunctive. For a possibly completed past action, use present perfect subjunctive: hayan dado. Se lo = they gave it to him/her.",
    ),
    (
        "How would a Mexican say 'Even though they told her about the enchiladas, she didn't want to try them'?",
        ["Aunque le dijeran de las enchiladas, no quería probarlas", "Aunque le dijeron de las enchiladas, no quiso probarlas", "Aunque le hayan dicho de las enchiladas, no quería probarlas", "Aunque se lo dijeron, no las quería probar"],
        2,
        "Aunque with a known/completed fact takes the indicative (dijeron). Enchiladas = Mexican food. 'No quiso' (preterite) = she refused/didn't want to.",
    ),
    (
        "Which correctly uses a negative command with se lo and a Mexican expression?",
        ["¡No se lo des, está gacho!", "¡No le lo des, es malo!", "¡No se lo das, está gacho!", "¡No le des lo, es gacho!"],
        1,
        "Negative tú command: no se lo des (not le lo). Está gacho = it's uncool/bad — Mexican slang. The other options have grammatical errors (le lo, se lo das, le des lo).",
    ),
    (
        "How do you say 'I want you to give it to her before you leave' in Mexican Spanish?",
        ["Quiero que le lo des antes de que te vayas", "Quiero que se lo des antes de que te vayas", "Quiero que se la des antes de que te vas", "Quiero que le lo des antes de irte"],
        2,
        "Quiero que → subjunctive (des). Se lo = 'it to her' (le lo → se lo). Antes de que → always subjunctive (te vayas). The combination of volitional subjunctive + double pronoun + adverbial subjunctive clause is a B2/C1 challenge.",
    ),
    (
        "What is the correct translation of 'If I were you, I'd tell him the truth right away (luego luego)'?",
        ["Si yo fuera tú, le diría la verdad luego luego", "Si yo sería tú, le diría la verdad luego", "Si yo fuera tú, le diría la verdad después", "Si yo era tú, le diría la verdad luego luego"],
        1,
        "Si + imperfect subjunctive (fuera) → conditional (diría). Le = 'to him.' Luego luego = Mexican 'right away.' The combination of subjunctive-conditional + pronoun + Mexican expression is a classic B2/C1 pattern.",
    ),
    (
        "Which correctly combines conditional perfect + double pronoun in 'They should have given it to us'?",
        ["Deberían haber lo dado a nosotros", "Deberían habérnoslo dado", "Deberían nos lo haber dado", "Deberían haber dado se lo a nosotros"],
        2,
        "Deberían haber + nos lo attached → habérnoslo dado. When two pronouns attach to an infinitive, the order is indirect (nos) then direct (lo). The accent shifts to maintain stress: ha-BER-nos-lo DA-do.",
    ),
    (
        "How do you say 'It bothers me that she told him about it' in Spanish?",
        ["Me molesta que ella le dice sobre eso", "Me molesta que le haya dicho sobre eso", "Me molesta que le dijo sobre eso", "Me molesta que le dijera sobre eso"],
        2,
        "Me molesta que → subjunctive. For a possibly completed action, present perfect subjunctive (haya dicho). Le = 'to him.' Emotion trigger + perfect subjunctive + pronoun reference = B2/C1 pattern.",
    ),
    (
        "Which sentence correctly uses the Mexican idiom 'échale ganas' in the subjunctive?",
        ["Espero que le eches ganas", "Espero que échale ganas", "Espero que eches ganas", "Espero que le echan ganas"],
        1,
        "Espero que → subjunctive. Le eches ganas = tú subjunctive form of 'echarle ganas' (Mexican 'put effort into it'). The le is the indirect object pronoun. 'Echan' is indicative and doesn't follow 'espero que.'",
    ),
    (
        "What does 'Aunque me digan que está chido, no voy' mean?",
        ["They told me it's cool, so I'm going", "Even if they tell me it's cool, I won't go", "Although they told me it's cool, I didn't go", "Even though they told me it's cool, I'm going"],
        2,
        "Aunque + subjunctive (digan) = 'even if' (hypothetical). Chido = Mexican 'cool.' No voy = 'I won't go.' This combines concessive subjunctive + Mexican slang + future refusal.",
    ),
    (
        "Which is the correct translation of 'If she had explained it to us, we would have understood'?",
        ["Si ella nos lo explicó, entenderíamos", "Si nos lo hubiera explicado, habríamos entendido", "Si nos lo explicaba, entenderíamos", "Si ella nos lo hubiera explicado, nosotros habríamos entendido"],
        2,
        "Si + imperfect subjunctive (hubiera explicado) + nos lo + conditional perfect (habríamos entendido). This is the third conditional with double pronoun stacking.",
    ),
    (
        "What does 'Se me hace que se habría enojado si le hubieras dicho' mean?",
        ["It makes me do it if you told her", "I think she would have gotten mad if you had told her", "She told me that you made her mad", "It seems to me that I would have told her"],
        2,
        "Se me hace que = Mexican hedging 'I think that.' Se habría enojado = conditional perfect. Si le hubieras dicho = imperfect subjunctive. Two different 'se's — one from the hedging expression, one from pronoun transformation.",
    ),
    (
        "Which correctly combines 'a menos que' + subjunctive + 'se lo' + 'luego luego'?",
        ["A menos que se lo envíen luego luego, no llegará a tiempo", "A menos que se lo envían luego, no llega a tiempo", "A menos que le lo envíen luego luego, no va a llegar", "A menos que se lo envíen luego, no llegarán a tiempo"],
        1,
        "A menos que → subjunctive (envíen). Se lo = 'it to him/her' (not le lo). Luego luego = Mexican 'right away' (not just 'luego'). Future in main clause: no llegará a tiempo.",
    ),
    (
        "Which sentence correctly uses Mexican slang 'gacho' with the subjunctive?",
        ["Está gacho que no nos paguen todavía", "Está gacho que no nos pagan todavía", "Es gacho que no pagamos todavía", "Está gacho que no nos pagaban"],
        1,
        "Está gacho que → subjunctive (paguen). Gacho = unfair/uncool (Mexican). Nos = 'to us.' Todavía/aún = 'yet.' Emotion/evaluation triggers always take the subjunctive.",
    ),
    (
        "How do you say 'Wow, I doubt they'll send it to her on time' using Mexican expressions?",
        ["¡Híjole! Dudo que se lo envíen a tiempo", "¡Híjole! Dudo que se lo envían a tiempo", "¡Qué padre! Dudo que le lo envíen a tiempo", "¡Órale! Dudo que se lo enviarán a tiempo"],
        1,
        "Híjole = Mexican exclamation. Dudo que → subjunctive (envíen). Se lo = 'it to her' (le lo → se lo). 'Envían' is indicative (wrong after dudo que). 'Enviarán' is future (wrong after dudo que).",
    ),
    (
        "Which correctly combines volitional subjunctive + double pronoun + Mexican cultural term?",
        ["La maestra insistió en que se lo entregáramos antes de irnos", "La maestra insistió en que le lo entregamos antes de irnos", "La maestra insistió que se lo entregáramos antes de irnos", "La maestra insistió en que se lo entregaremos antes de ir"],
        1,
        "Insistió en que → subjunctive (entregáramos). Se lo = 'it to him/her' (le lo → se lo). Antes de irnos = before leaving. 'Insistió en que' requires 'en' in Mexican Spanish. The subjunctive is required after insistence.",
    ),
    (
        "What does 'Cuando quieras, te preparo un cafecito' demonstrate?",
        ["A past habit + formal pronoun + a small coffee", "An indefinite future reference + indirect object + Mexican diminutive for warmth", "A command + direct object + a small coffee", "A conditional + reflexive pronoun + diminutive for size only"],
        2,
        "Cuando quieras → subjunctive for indefinite future ('whenever you want'). Te = indirect object ('for you'). Cafecito = diminutive adding warmth and affection, not just small size. Three concepts in one natural sentence.",
    ),
    (
        "Which is the correct subjunctive form for 'I'm surprised that she gave them (the tickets) to him'?",
        ["Me sorprende que se los haya dado", "Me sorprende que se los dio", "Me sorprende que se los habían dado", "Me sorprende que le los haya dado"],
        1,
        "Me sorprende que → subjunctive. For a possibly completed action, present perfect subjunctive (haya dado). Se los = 'them to him' (les los → se los). 'Dio' is indicative (wrong). 'Le los' is invalid (le → se before lo/la/los/las).",
    ),
    (
        "How do you say 'No way, it's incredible that they gave it to her' with Mexican slang?",
        ["¡No manches! Es increíble que se lo hayan dado", "¡No mames! Es increíble que se lo dieron", "¡No manches! Es increíble que se lo dan", "¡Qué padre! Es increíble que le lo hayan dado"],
        1,
        "¡No manches! = polite Mexican 'No way!' Es increíble que → subjunctive (hayan dado). Se lo = 'it to her' (le lo → se lo). Option 2 uses indicative (dieron) — wrong. Option 4 has invalid 'le lo.'",
    ),
    (
        "Which sentence correctly combines 'quiero que' + 'me lo' + 'luego luego'?",
        ["Quiero que me lo envíes luego luego", "Quiero que me lo envías luego", "Quiero que me lo enviaré luego luego", "Quiero que me lo envíes luego"],
        1,
        "Quiero que → subjunctive (envíes). Me lo = 'it to me.' Luego luego = Mexican 'right away' (reduplication adds emphasis, not just 'luego'). This is a natural, everyday Mexican sentence combining grammar and slang.",
    ),
    (
        "What does '¡Qué padre que se lo hayas dado!' mean?",
        ["How cool that you gave it to him/her!", "What a father that you gave it!", "It's bad that you gave it to him/her", "Your dad gave it to you!"],
        1,
        "¡Qué padre! = Mexican 'How cool!' Emotion trigger → present subjunctive (hayas dado). Se lo = 'it to him/her.' This combines Mexican slang with emotion-triggered subjunctive and double pronouns.",
    ),
    (
        "How do you say 'I doubt they put effort into it before quitting' using the Mexican idiom 'echar ganas'?",
        ["Dudo que hayan echado ganas antes de renunciar", "Dudo que echaron ganas antes de renunciar", "Dudo que echan ganas antes de renunciar", "Dudo que echaban ganas antes de renunciar"],
        1,
        "Dudo que → subjunctive. For a past action viewed with doubt, present perfect subjunctive (hayan echado). Echar ganas = Mexican 'to put effort into it.' Renunciar = to quit. Indicative forms (echaron, echan, echaban) don't follow 'dudo que.'",
    ),
    (
        "Which correctly translates 'As soon as you give it to her, let me know'?",
        ["En cuanto se lo des, avísame", "En cuanto se lo das, avísame", "En cuanto le la des, avísame", "En cuanto se lo das, me avisas"],
        1,
        "En cuanto → subjunctive (des) for future/hypothetical action. Se la = 'it to her' (le la → se la). Avísame = tú command. 'Das' is indicative — wrong for future reference after en cuanto.",
    ),
    (
        "Which sentence correctly uses Mexican slang 'lana' (money) with the subjunctive?",
        ["Me molesta que no nos hayan dado lana", "Me molesta que no nos dan lana", "Me molesta que no nos dieron lana", "Me molesta que no nos darán lana"],
        1,
        "Me molesta que → subjunctive (hayan dado). Nos = 'to us.' Lana = Mexican slang for 'money.' All indicative forms (dan, dieron, darán) are incorrect after emotion triggers.",
    ),
    (
        "What is 'nos alegró que nos hubieras hecho un cafecito' combining?",
        ["Past happiness + subjunctive + double pronoun + Mexican diminutive for warmth", "Present happiness + infinitive + direct object + small coffee", "Past happiness + indicative + reflexive pronoun + informal coffee", "Happiness command + subjunctive + indirect object + tiny coffee"],
        1,
        "Nos alegró que → subjunctive. Hubieras hecho = imperfect subjunctive (past action). Nos = 'for us' (indirect object). Cafecito = Mexican diminutive adding warmth, not just small size. Four concepts combined.",
    ),
    (
        "Which sentence correctly uses 'está gacho' with subjunctive and Mexican slang 'chamba'?",
        ["Está gacho que le hayan dado la chamba a alguien más", "Está gacho que le dieron la chamba a alguien", "Está gacho que le dan la chamba a otro", "Es gacho que le darán la chamba a alguien"],
        1,
        "Está gacho que → subjunctive (hayan dado). Gacho = unfair/uncool (Mexican). Chamba = job/work (Mexican). Le = 'to him/her.' Indicative forms (dieron, dan, darán) don't follow emotion/evaluation triggers.",
    ),
    (
        "What does 'Quizás ya se lo hayan dado al güero' combine?",
        ["Certainty + indicative + direct object + physical description", "Possibility + subjunctive + se lo + Mexican word for light-skinned person", "Doubt + infinitive + le lo + foreign word", "Possibility + subjunctive + se los + Mexican word for old man"],
        2,
        "Quizás with possibly completed action → present perfect subjunctive (hayan dado). Se lo = 'it to him' (le lo → se lo). Güero = Mexican word for light-skinned/light-haired person. Combines possibility, pronoun stacking, and cultural vocabulary.",
    ),
    (
        "How do you formally say 'It's important that you send them (the documents) to us right away'?",
        ["Es importante que nos los envíe luego luego", "Es importante que nos los envía luego", "Es importante que nos los envíen luego luego", "Es importante que se los envíe luego luego"],
        1,
        "Es importante que → subjunctive. Usted form: envíe. Nos los = 'them to us' (nos before los). Luego luego = Mexican 'right away.' Option 3 uses plural ustedes (not specified). Option 4 uses se los ('them to him') instead of nos los.",
    ),
    (
        "Which correctly uses Mexican slang 'escuincle' with negation-triggered subjunctive?",
        ["No creo que le hayan dado al escuincle", "No creo que le dieron al escuincle", "No creo que le dan al escuincle", "No creo que le darán al escuincle"],
        1,
        "No creo que → subjunctive (hayan dado). Le = 'to him/her.' Escuincle = Mexican slang for 'brat' (from Nahuatl). Indicative forms (dieron, dan, darán) cannot follow 'no creo que.'",
    ),
    (
        "What does 'Lo que hagas, ¡no se lo des al ruco!' combine?",
        ["Whatever you do (subjunctive) + negative command + se lo + Mexican slang for old man", "Whatever you do (indicative) + positive command + le lo + Spanish word", "Whatever you do (subjunctive) + negative command + se las + Mexican word for dog", "Whatever you do (infinitive) + suggestion + se lo + formal term"],
        1,
        "Lo que hagas → subjunctive (indefinite antecedent). No se lo des → negative tú command (le lo → se lo). Ruco = Mexican slang for 'old dude.' Three grammar concepts + slang.",
    ),
    (
        "Which sentence correctly uses 'es posible que' with subjunctive and Mexican food vocabulary?",
        ["Es posible que aún no nos hayan enviado la receta del pozole", "Es posible que no nos envían la receta del pozole", "Es posible que no nos mandan la receta del pozole todavía", "Es posible que no nos enviaron la receta del pozole"],
        1,
        "Es posible que → subjunctive (hayan enviado). Nos = 'to us.' Pozole = traditional Mexican soup with hominy. Aún no = 'not yet.' Indicative forms (envían, mandan, enviaron) don't follow 'es posible que.'",
    ),
    (
        "What does 'Se me hace que le dieron la receta de los chilaquiles' combine?",
        ["Mexican hedging + indirect object + Mexican breakfast food", "Certainty + direct object + Spanish lunch food", "Doubt + subjunctive + Mexican sauce", "Impersonal expression + reflexive + Mexican drink"],
        1,
        "Se me hace que = Mexican hedging 'I think/I have the impression that.' Le = 'to her.' Chilaquiles = fried tortilla chips in salsa (Mexican breakfast). This combines Mexican hedging, pronoun reference, and food vocabulary.",
    ),
    (
        "Which correctly combines '¡qué gacho!' with subjunctive and Mexican slang 'chamba'?",
        ["¡Qué gacho que le hayan dado la buena chamba a otro!", "¡Qué gacho que le dieron la buena chamba a otro!", "¡Qué gacho que le dan la chamba a otro!", "¡Qué gacho que le darán la chamba a otro!"],
        1,
        "¡Qué gacho! = Mexican 'How unfair!' Emotion trigger → subjunctive (hayan dado). Chamba = Mexican slang for 'job.' Le = 'to him/her.' Indicative forms (dieron, dan, darán) don't follow emotion triggers.",
    ),
    (
        "What does 'Es increíble que nos hayan cobrado tanta lana por los tacos' combine?",
        ["Impersonal expression + infinitive + direct object + Spanish word", "Emotion trigger + subjunctive + nos (to us) + lana (Mexican slang for money)", "Doubt + indicative + reflexive + formal word", "Certainty + subjunctive + indirect object + Mexican food"],
        2,
        "Es increíble que → subjunctive (hayan cobrado). Nos = 'to us.' Lana = Mexican slang for 'money.' Cobrar = to charge. This combines an emotion trigger, subjunctive, pronoun reference, and Mexican slang for money.",
    ),
]


if __name__ == "__main__":
    run_exercises(exercises, title="Lección 10: Capstone — Mixed Translation Drills (B2/C1)")
    choose_translation(pairs, title="Lección 10: Capstone — Choose the Best Mexican Translation")